apiVersion: v1
kind: Secret
metadata:
  name: debezium-demo-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5yZWRoYXQuaW8iOnsiYXV0aCI6Ik1JVE0ifX19
# 👆 This entry needs to be updated with a Registry Service Account from 👆
#  the Red Hat Customer Portal: https://access.redhat.com/terms-based-registry/
