apiVersion: v1
kind: Secret
metadata:
  name: debezium-demo-kafka-secrets
type: Opaque
stringData:
  kafka.password: a4d20936-8e9b-daft-punk-19932021
# 👆 This entry needs to be updated with the Managed Kafka password 👆
