apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: debezium-postgres-source-connector
  labels:
    strimzi.io/cluster: dbz-mk-demo-sasl
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: dbz-mk-pg
    database.port: 5432
    database.dbname: postgres
    database.server.name: postgres1
    schema.include: inventory
    database.user: "${file:/opt/kafka/external-configuration/postgres-connector-credentials/debezium-postgres-credentials.properties:user}"
    database.password: "${file:/opt/kafka/external-configuration/postgres-connector-credentials/debezium-postgres-credentials.properties:password}"
