== Using Bin Scripts with Managed Kafka Quickstart

This project illustrates how you can interact with a Managed Kafka using
Kafka Bin Scripts.

NOTE: This guide uses rhoas cli, however users can also execute the same steps in cloud.redhat.com website

=== Prerequisites

* https://www.apache.org/dyn/closer.cgi?path=/kafka/2.6.0/kafka_2.13-2.6.0.tgz[Kafka
Bin Scripts]
* https://github.com/bf2fc6cc711aee1a0c2a/cli/releases[rhoas cli]
* https://stedolan.github.io/jq/[jq]
* https://kubernetes.io/fr/docs/reference/kubectl/overview/[kubectl].
This is temporary required

=== Creating a Managed Kafka cluster

First you need a Kafka cluster. You can follow the instructions to
create one.

Using the https://github.com/bf2fc6cc711aee1a0c2a/cli/releases[RHMAS
CLI], login and create a new cluster:

[source,bash]
----
rhoas login
rhoas kafka create --name=<your-cluster-name>
----

Wait a couple of seconds for cluster to provision.

You can use the:

[source,bash]
----
rhoas kafka list
----

=== Retrieve Bootstrap URL

[source,bash]
----
CLUSTER_ID=$(rhoas kafka list | grep '<your-cluster-name>' | awk '{print $1}')
BOOTSTRAP_URL=$(rhoas kafka get $CLUSTER_ID | jq -r '.bootstrapServerHost')
----

Where `<your-cluster-name>` is the name of the cluster.

=== Create credentials that will be used to connect to cluster

----
rhoas serviceaccount create --name=<yourname> -o=env
----

This will generate .env file with content that should look as follows:
----
USER=srvc-acct-fdsfdsf
PASSWORD=323fsdf23-fgdsgdffsadsa
----

=== Create properties file used to connect

Copy USER and PASSWORD values into placeholders

[source,properties]
----
sasl.mechanism=PLAIN
security.protocol=SASL_SSL

sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="<USER>" \
  password="<PASSWORD>";
----

=== Produce messages

[source,bash]
----
./bin/kafka-console-producer.sh -topic my-topic --bootstrap-server "$BOOTSTRAP_URL:443" --producer.config config.properties

First message
Second message
Third message
----

=== Consumimg messages

Start the consumer

[source,bash]
----
./bin/kafka-console-consumer.sh -topic my-topic --bootstrap-server "$BOOTSTRAP_URL:443" --from-beginning --consumer.config config.properties
----

You should see

[source,log]
----
First message
Second message
Third message
----
