////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////


:community:
:imagesdir: ./images
:product-version: 1
:product-long: Application Services
:product: App Services
:registry-product-long: Red Hat OpenShift Service Registry
:registry: Service Registry
// Placeholder URL, when we get a HOST UI for the service we can put it here properly
:service-url: https://console.redhat.com/beta/application-services/streams/
:registry-url: https://console.redhat.com/beta/application-services/service-registry/
:property-file-name: app-services.properties
:rhoas-version: 0.32.0

// Other upstream project names
:samples-git-repo: https://github.com/redhat-developer/app-services-guides

//URL components for cross refs
:base-url: https://github.com/redhat-developer/app-services-guides/blob/main/
:base-url-cli: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:getting-started-url: getting-started/README.adoc
:getting-started-service-registry-url: getting-started-service-registry/README.adoc
:kafka-bin-scripts-url: kafka-bin-scripts/README.adoc
:kafkacat-url: kafkacat/README.adoc
:quarkus-url: quarkus/README.adoc
:quarkus-service-registry-url: quarkus-service-registry/README.adoc
:rhoas-cli-url: rhoas-cli/README.adoc
:rhoas-cli-kafka-url: rhoas-cli-kafka/README.adoc
:rhoas-cli-service-registry-url: rhoas-cli-service-registry/README.adoc
:rhoas-cli-ref-url: commands
:topic-config-url: topic-configuration/README.adoc
:consumer-config-url: consumer-configuration/README.adoc
:service-binding-url: service-discovery/README.adoc
:access-mgmt-url: access-mgmt/README.adoc

////
END GENERATED ATTRIBUTES
////

[id="chap-getting-started-rhoas-cli"]
= Installing and configuring the rhoas CLI
:context: installing-rhoas-cli

[IMPORTANT]
====
The `rhoas` command-line interface (CLI) is currently available for Development Preview. Development Preview releases provide early access to a limited set of features that might not be fully tested and that might change in the final GA version. Users should not use Development Preview software in production or for business-critical workloads. Limited documentation is available for Development Preview releases and is typically focused on fundamental user goals.
====

[role="_abstract"]
With the `rhoas` command-line interface (CLI), you can manage your application services from a terminal.

This guide describes how to set up `rhoas` by doing the following:

--
* link:{base-url}{rhoas-cli-url}#proc-installing-rhoas_installing-rhoas-cli[Install `rhoas` on your operating system]
* link:{base-url}{rhoas-cli-url}#proc-configuring-rhoas_installing-rhoas-cli[Configure `rhoas` to enable command completion]
* link:{base-url}{rhoas-cli-url}#proc-logging-in-to-rhoas_installing-rhoas-cli[Log in to `rhoas`]
* link:{base-url}{rhoas-cli-url}#proc-logging-out-rhoas_installing-rhoas-cli[Log out of `rhoas`]
--

//Additional line break to resolve mod docs generation error

[id="proc-installing-rhoas_{context}"]
== Installing the rhoas CLI

[role="_abstract"]
You can install `rhoas` on Linux, macOS, or Windows.

NOTE: The `rhoas` link:https://github.com/redhat-developer/app-services-cli/releases[Releases page^] lists the bug fixes and new features for every `rhoas` release.

[discrete,id="installing-rhoas-cli-linux_{context}"]
=== Installing the rhoas CLI on Linux

If you are using Linux, you can install `rhoas` by either using the installation script, or the RPM.

[discrete,id="installation-script_{context}"]
==== Installation script

.Procedure

. Review the https://github.com/redhat-developer/app-services-cli/blob/main/scripts/install.sh[`install.sh` installation script^].

. Run the `install.sh` script:
+
--
[source,shell]
----
$ curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/scripts/install.sh | bash
----

[NOTE]
====
You can use the `-s` argument to install a specific version of the `rhoas` CLI. For example, this command installs version `{rhoas-version}`:

[source,shell,subs="+attributes"]
----
$ curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/scripts/install.sh | bash -s {rhoas-version}
----
====

The `rhoas` CLI is installed in `$HOME/.local/bin`.
--

. Verify that the `rhoas` installation directory is on your `$PATH`.
+
--
To check your `$PATH`, run the following command:

[source,shell]
----
$ echo $PATH
----
--

. Check the `rhoas` version to verify that the CLI is installed.
+
--
This example shows that `rhoas` {rhoas-version} is installed:

[source,shell,subs="+attributes"]
----
$ rhoas --version
rhoas version {rhoas-version}
----
--

[discrete,id="rpm-installation_{context}"]
==== RPM installation

You can install `rhoas` as an RPM if you are using Red Hat Enterprise Linux (RHEL), Fedora, or CentOS.

.Procedure

. Navigate to the `rhoas` link:https://github.com/redhat-developer/app-services-cli/releases[Releases page^] and choose the version that you'd like to download.

. Use `dnf`/`yum` to install the desired version of `rhoas`:
+
--
This example installs `rhoas` version `{rhoas-version}`:

[source,shell,subs="+attributes"]
----
$ sudo dnf install -y https://github.com/redhat-developer/app-services-cli/releases/download/v{rhoas-version}/rhoas_{rhoas-version}_linux_amd64.rpm
----
--

. Check the `rhoas` version to verify that the CLI is installed.
+
--
This example shows that `rhoas` {rhoas-version} is installed:

[source,shell,subs="+attributes"]
----
$ rhoas --version
rhoas version {rhoas-version}
----
--

[discrete,id="installing-rhoas-cli-macos_{context}"]
=== Installing the rhoas CLI on macOS

.Procedure

. Review the link:https://github.com/redhat-developer/app-services-cli/blob/main/scripts/install.sh[`install.sh` installation script^].

. Run the `install.sh` script:
+
--
[source,shell]
----
$ curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/scripts/install.sh | bash
----

[NOTE]
====
You can use the `-s` argument to install a specific version of the `rhoas` CLI. For example, this command installs version `{rhoas-version}`:

[source,shell,subs="+attributes"]
----
$ curl -o- https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/scripts/install.sh | bash -s {rhoas-version}
----
====

The `rhoas` CLI is installed in `$HOME/bin`.
--

. Verify that the `rhoas` installation directory is on your `$PATH`.
+
--
To check your `$PATH`, run the following command:

[source,shell]
----
$ echo $PATH
----
--

. Check the `rhoas` version to verify that the CLI is installed.
+
--
This example shows that `rhoas` {rhoas-version} is installed:

[source,shell,subs="+attributes"]
----
$ rhoas --version
rhoas version {rhoas-version}
----
--

[discrete,id="installing-rhoas-cli-windows_{context}"]
=== Installing the rhoas CLI on Windows

.Procedure

. Navigate to the `rhoas` link:https://github.com/redhat-developer/app-services-cli/releases[Releases page^].

. Download the latest `rhoas` .zip file.

. On your computer, create a `C:\rhoas` folder.

. Extract the `rhoas.exe` file from the .zip file that you downloaded.

. Move the `rhoas.exe` file to `C:\rhoas`.

. If you are using Windows 10, set the `PATH` variable.

.. Click *Search* and type `env` or `environment`.

.. Select *Edit environment variables for your account*.

.. In the *Variable* section, select *Path*, and click *Edit*.

.. Click *New*, and enter `C:\rhoas`.

.. Click *OK* to save changes.

. Check the `rhoas` version to verify that the CLI is installed.
+
--
This example shows that `rhoas` {rhoas-version} is installed:

[source,shell,subs="+attributes"]
----
$ rhoas --version
rhoas version {rhoas-version}
----
--

[id="proc-configuring-rhoas_{context}"]
== Configuring rhoas

[role="_abstract"]
After you install the `rhoas` CLI,
you can enable command completion to automatically complete `rhoas` commands or suggest options when you press *Tab*.

NOTE: The procedure for enabling command completion depends on the shell you are using.
To determine which shell you are using, run the `echo $0` command.

You can enable command completion for each of the following shells:

* link:{base-url}{rhoas-cli-url}#enabling-command-completion-bash_installing-rhoas-cli[Bash]
* link:{base-url}{rhoas-cli-url}#enabling-command-completion-zsh_installing-rhoas-cli[Zsh]
* link:{base-url}{rhoas-cli-url}#enabling-command-completion-fish_installing-rhoas-cli[Fish]

.Prerequisites

* You've installed the `rhoas` CLI.

[discrete,id="enabling-command-completion-bash_{context}"]
=== Enabling command completion on Bash

.Procedure

. Create the `rhoas_completions` script file.
+
[source,shell]
----
$ rhoas completion bash > rhoas_completions
----

. Move the script file to a special Bash completions directory.
+
--
.Linux
[source,shell]
----
$ sudo mv rhoas_completions /etc/bash_completion.d/rhoas
----

.macOS
[source,shell]
----
$ sudo mv rhoas_completions /usr/local/etc/bash_completion.d/rhoas
----
--

. Open a new terminal window.
+
Command completion is enabled.

[discrete,id="enabling-command-completion-zsh_{context}"]
=== Enabling command completion on Zsh

.Procedure

. Install the command completion script.
+
[source,shell]
----
$ rhoas completion zsh > "${fpath[1]}/_rhoas"
----

. Unless already installed, enable command completions.
+
[source,shell]
----
$ echo "autoload -U compinit; compinit" >> ~/.zshrc
----

. Open a new terminal window.
+
Command completion is enabled.

[discrete,id="enabling-command-completion-fish_{context}"]
=== Enabling command completion on Fish

.Procedure

. Install fish completions.
+
[source,shell]
----
$ rhoas completion -s fish > ~/.config/fish/completions/rhoas.fish
----

. Open a new terminal window.
+
Command completion is enabled.

[id="proc-logging-in-to-rhoas_{context}"]
== Logging in to rhoas

[role="_abstract"]
After `rhoas` is installed, you can log in to access your application services.

.Prerequisites

* You must have an account to access Red Hat OpenShift Application Services.
* You've installed the `rhoas` CLI.

.Procedure

. In a terminal, log in to `rhoas`.
+
--
[source,shell]
----
$ rhoas login
----

You are redirected to your web browser at https://sso.redhat.com[^].
--

. Enter your credentials to log in to your Red Hat account.
+
--
Welcome pages in the browser notify you that you have been logged in to `rhoas` successfully.

In your terminal, the `rhoas login` command indicates that you are logged in:

[source,shell]
----
$ rhoas login
Logging in...
✔️ Logged in successfully

✔️ You are now logged in as "user"
----
--

[id="proc-logging-out-rhoas_{context}"]
== Logging out of rhoas

[role="_abstract"]
You can log out from the `rhoas` CLI by using the `rhoas logout` command.

.Procedure

* Log out of `rhoas`.
+
[source,shell]
-----
$ rhoas logout
Successfully logged out
-----

[role="_additional-resources"]
.Additional resources
* {base-url}{rhoas-cli-kafka-url}[_Getting started with the rhoas CLI for OpenShift Streams for Apache Kafka_^]
* {base-url}{rhoas-cli-service-registry-url}[_Getting started with the rhoas CLI for OpenShift Service Registry_^]
* {base-url-cli}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
