---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kafka-avro-schema-quickstart
  name: kafka-avro-schema-quickstart
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: kafka-avro-schema-quickstart
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kafka-avro-schema-quickstart
  name: kafka-avro-schema-quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-avro-schema-quickstart
  
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-avro-schema-quickstart
    
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: quay.io/rhoas/kafka-avro-schema-quickstart:native
        imagePullPolicy: Always
        name: kafka-avro-schema-quickstart
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kafka-avro-schema-quickstart
  labels:
    app.kubernetes.io/name: kafka-avro-schema-quickstart
spec:
  to:
    kind: Service
    name: kafka-avro-schema-quickstart
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
