[id="registry-distros_{context}"]
= {registry} Java libraries

[role="_abstract"]

{registry} provides Java libraries for client applications to connect to {registry} instances, manage their content, or validate Kafka messages. {registry} Java client applications can: 

* Use a Maven plug-in or Java client classes to manage schema and API artifacts stored in {registry}

* Use Kafka serializers/deserializers for Apache Avro, Protobuf, or JSON schema to serialize and validate Kafka message content

* Use Kafka Connect converters to map Kafka Connect schemas into Avro or JSON schemas when streaming data to external systems


.{registry} Java library .zip downloads
[%header,cols="4,3,3"]

|===
|Distribution
|Location
|Release category
|Offline Maven repository for Maven plug-in, Java client, and serializers/deserializers
|link:{download-url-registry-distribution}[Red Hat Developer downloads]
|Development Preview
|Kafka Connect converters 
|link:{download-url-registry-distribution}[Red Hat Developer downloads]
|Development Preview
|===
