////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////


:community:
:imagesdir: ./images
:product-version: 1
:product-long: Application Services
:product: App Services
:registry-product-long: OpenShift Service Registry
:registry: Service Registry
// Placeholder URL, when we get a HOST UI for the service we can put it here properly
:service-url: https://console.redhat.com/beta/application-services/streams/
:registry-url: https://console.redhat.com/beta/application-services/service-registry/
:property-file-name: app-services.properties
:rhoas-version: 0.32.0

// Other upstream project names
:samples-git-repo: https://github.com/redhat-developer/app-services-guides

//URL components for cross refs
:base-url: https://github.com/redhat-developer/app-services-guides/blob/main/
:base-url-cli: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:getting-started-url: getting-started/README.adoc
:kafka-bin-scripts-url: kafka-bin-scripts/README.adoc
:kafkacat-url: kafkacat/README.adoc
:quarkus-url: quarkus/README.adoc
:rhoas-cli-url: rhoas-cli/README.adoc
:rhoas-cli-kafka-url: rhoas-cli-kafka/README.adoc
:rhoas-cli-service-registry-url: rhoas-cli-service-registry/README.adoc
:rhoas-cli-ref-url: commands
:topic-config-url: topic-configuration/README.adoc
:consumer-config-url: consumer-configuration/README.adoc
:service-binding-url: service-discovery/README.adoc
:access-mgmt-url: access-mgmt/README.adoc

////
END GENERATED ATTRIBUTES
////

[id="chap-getting-started-rhoas-cli-kafka"]
= Getting started with the rhoas CLI for OpenShift Streams for Apache Kafka
:context: getting-started-rhoas-kafka

[IMPORTANT]
====
The `rhoas` command-line interface (CLI) is currently available for Development Preview. Development Preview releases provide early access to a limited set of features that might not be fully tested and that might change in the final GA version. Users should not use Development Preview software in production or for business-critical workloads. Limited documentation is available for Development Preview releases and is typically focused on fundamental user goals.
====

[role="_abstract"]
With the `rhoas` command-line interface (CLI), you can manage OpenShift Streams for Apache Kafka from a terminal.

As a developer of applications and services,
you can use `rhoas` to create Kafka instances and connect your applications and services to these instances.
You can also create Kafka topics to store data for producers and consumers.

This guide describes how to get started quickly by doing the following:

* link:{base-url}{rhoas-cli-kafka-url}#proc-creating-kafka-instance-cli_getting-started-rhoas-kafka[Create a Kafka instance]
* link:{base-url}{rhoas-cli-kafka-url}#proc-creating-service-account-cli_getting-started-rhoas-kafka[Create a service account]
* link:{base-url}{rhoas-cli-kafka-url}#proc-creating-kafka-topic-cli_getting-started-rhoas-kafka[Create a Kafka topic]
* link:{base-url}{rhoas-cli-kafka-url}#proc-commands-managing-kafka_getting-started-rhoas-kafka[Use `rhoas` to manage your Kafka instances, service accounts, and Kafka topics]

//Additional line break to resolve mod docs generation error

[id="ref-kafka-cli-prereqs_{context}"]
== Prerequisites

[role="_abstract"]
* You've installed the `rhoas` CLI. For more information, see {base-url}{rhoas-cli-url}[_Installing the rhoas CLI_^].

//Additional line break to resolve mod docs generation error

[id="proc-creating-kafka-instance-cli_{context}"]
== Creating a Kafka instance

[role="_abstract"]
A Kafka instance includes a Kafka cluster, bootstrap server, and other required configurations for connecting to Kafka producer and consumer services.

.Prerequisites

* You are logged in to `rhoas`.

.Procedure

. Enter the following command to create a Kafka instance with default values.
+
--
This example creates a Kafka instance called `my-kafka`.

.Creating a Kafka instance
[source,shell]
----
$ rhoas kafka create --name my-kafka
{
  "cloud_provider": "aws",
  "created_at": "2021-03-17T18:33:50.000799005Z",
  "href": "/api/managed-services-api/v1/kafkas/1ptcsACdx7HVzacKZBA6HRRa1oW",
  "id": "1ptcsACdx7HVzacKZBA6HRRa1oW",
  "kind": "Kafka",
  "multi_az": true,
  "name": "my-kafka",
  "owner": "developer",
  "region": "us-east-1",
  "status": "accepted",
  "updated_at": "2021-03-17T18:33:50.000799005Z"
}
Kafka instance "my-kafka" is being created. To monitor its status run "rhoas status".
----

[NOTE]
====
If you do not want to use the default values,
enter the following command: `rhoas kafka create`.
You will be prompted to enter the `Name`, `Cloud Provider`, and `Cloud Region` for the Kafka instance.
====
--

. Enter the following command to verify that the Kafka instance is ready to use.
+
--
This command shows that the Kafka instance is ready to use,
because the `Status` field is `ready`.

.Reviewing details of a Kafka instance
[source,shell]
----
$ rhoas status kafka

  Kafka
  -----------------------------------------------------------------------------------
  ID:                     1ptdfZRHmLKwqW6A3YKM2MawgDh
  Name:                   my-kafka
  Status:                 ready
  Bootstrap URL:          my-kafka--ptdfzrhmlkwqw-a-ykm-mawgdh.kafka.devshift.org:443
----

[NOTE]
====
When you created the Kafka instance, it was set as the current instance automatically.
If you have multiple Kafka instances,
you can switch to a different instance by using the `rhoas kafka use` command.
====
--

[id="proc-creating-service-account-cli_{context}"]
== Creating a service account

[role="_abstract"]
To connect your applications or services to a Kafka instance, you must first create a service account with credentials.
The credentials are exported to a file on your computer,
which you can use to authenticate your application with your Kafka instance.

.Prerequisites

* You have created a Kafka instance, and it has a `ready` status.

.Procedure

. Enter the following command to create a service account.
+
--
This example creates a service account and saves the credentials in a JSON file.

.Creating a service account
[source,shell]
----
$ rhoas service-account create --file-format json --short-description="rhoas-service-account"

✔️ Service account created successfully with ID "04ba07d6-b08c-45fb-af53-3522c1b4c32f".
✔️ Credentials saved to /home/developer/my-project/credentials.json
----

Your service account credentials are created and saved to a JSON file.

[NOTE]
====
When creating a service account, you can choose the file format and location to save the credentials.
For more information, see the `rhoas service-account create` command help.
====
--

. To verify your service account credentials,
view the `credentials.json` file that you created.
+
--
.Verifying service account credentials
[source,shell]
----
$ cat credentials.json
{
	"clientID":"srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1",
	"clientSecret":"facf3df1-ab97-2253-aa87-ab97",
        "oauthTokenUrl": "https://identity.api.openshift.com/auth/realms/rhoas/protocol/openid-connect/token"
}
----
You'll use these credentials and the bootstrap server URL to connect your applications and services to your Kafka instance.

--

. Set the permissions for your service account to access the Kafka instance resources.
+
This example allows applications to produce and consume messages from topics starting with a specified prefix that belong to any consumer group.
+
--
.Assigning access permissions to a service account
[source,shell]
----
$ rhoas kafka acl grant-permissions --consumer --producer \
    --service-account srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1 --topic-prefix myapp  --group "*"
----

The permissions you assign depend on whether your application produces or consumes messages. 
--

[id="proc-creating-kafka-topic-cli_{context}"]
== Creating a Kafka topic

[role="_abstract"]
After creating a Kafka instance, you can create Kafka topics to start producing and consuming messages in your services.

.Prerequisites

* You have created a Kafka instance, and it has a `ready` status.

[NOTE]
====
You can use `rhoas kafka use` to switch to a specific Kafka instance.

.Selecting a Kafka instance to use
[source,shell]
----
$ rhoas kafka use --name my-kafka
Kafka instance "my-kafka" has been set as the current instance.
----
====

.Procedure

. Create a Kafka topic with default values.
+
--
This example creates the `my-topic` Kafka topic.

.Creating a Kafka topic with default values
[source,shell]
----
$ rhoas kafka topic create --name my-topic
Topic "my-topic" created in Kafka instance "my-kafka":
{
    "config": [
        {
            "key": "compression.type",
            "value": "producer"
        },
        {
            "key": "leader.replication.throttled.replicas",
            "value": ""
        },
        {
            "key": "min.insync.replicas",
            "value": "2"
        },
        {
            "key": "message.downconversion.enable",
            "value": "true"
        },
        {
            "key": "segment.jitter.ms",
            "value": "0"
        },
        {
            "key": "cleanup.policy",
            "value": "delete"
        },
        {
            "key": "flush.ms",
            "value": "9223372036854775807"
        },
        {
            "key": "follower.replication.throttled.replicas",
            "value": ""
        },
        {
            "key": "segment.bytes",
            "value": "1073741824"
        },
        {
            "key": "retention.ms",
            "value": "604800000"
        },
        {
            "key": "flush.messages",
            "value": "9223372036854775807"
        },
        {
            "key": "message.format.version",
            "value": "2.7-IV2"
        },
        {
            "key": "max.compaction.lag.ms",
            "value": "9223372036854775807"
        },
        {
            "key": "file.delete.delay.ms",
            "value": "60000"
        },
        {
            "key": "max.message.bytes",
            "value": "1048588"
        },
        {
            "key": "min.compaction.lag.ms",
            "value": "0"
        },
        {
            "key": "message.timestamp.type",
            "value": "CreateTime"
        },
        {
            "key": "preallocate",
            "value": "false"
        },
        {
            "key": "index.interval.bytes",
            "value": "4096"
        },
        {
            "key": "min.cleanable.dirty.ratio",
            "value": "0.5"
        },
        {
            "key": "unclean.leader.election.enable",
            "value": "false"
        },
        {
            "key": "retention.bytes",
            "value": "-1"
        },
        {
            "key": "delete.retention.ms",
            "value": "86400000"
        },
        {
            "key": "segment.ms",
            "value": "604800000"
        },
        {
            "key": "message.timestamp.difference.max.ms",
            "value": "9223372036854775807"
        },
        {
            "key": "segment.index.bytes",
            "value": "10485760"
        }
    ],
    "name": "my-topic",
    "partitions": [
        {
            "id": 0,
            "isr": [
                {
                    "id": 1
                },
                {
                    "id": 2
                },
                {
                    "id": 0
                }
            ],
            "leader": {
                "id": 1
            },
            "replicas": [
                {
                    "id": 1
                },
                {
                    "id": 2
                },
                {
                    "id": 0
                }
            ]
        }
    ]
}
----

[NOTE]
====
If you do not want to use the default values,
you can specify the number of partitions (`--partitions`) and message retention time (`--retention-ms`).
For more information, use the command help `rhoas kafka topic create -h`.
====
--

. If necessary, you can edit or delete the topic by using the `rhoas kafka topic update` and `rhoas kafka topic delete` commands.

[id="proc-commands-managing-kafka_{context}"]
== Commands for managing Kafka

[role="_abstract"]
For more information about the `rhoas` commands you can use to manage your Kafka instance,
use the following command help:

* `rhoas kafka -h` for Kafka instances
* `rhoas service-account -h` for service accounts
* `rhoas kafka acl -h` for access management
* `rhoas kafka topic -h` for Kafka topics

[role="_additional-resources"]
.Additional resources
* {base-url-cli}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
