////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////

//All OpenShift Application Services
:org-name: Application Services
:product-long-rhoas: OpenShift Application Services
:community:
:imagesdir: ./images
:property-file-name: app-services.properties
:samples-git-repo: https://github.com/redhat-developer/app-services-guides
:base-url: https://github.com/redhat-developer/app-services-guides/tree/main/docs/
:sso-token-url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
:cloud-console-url: https://console.redhat.com/
:service-accounts-url: https://console.redhat.com/application-services/service-accounts

//OpenShift Application Services CLI
:base-url-cli: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:command-ref-url-cli: commands
:installation-guide-url-cli: rhoas/rhoas-cli-installation/README.adoc
:service-contexts-url-cli: rhoas/rhoas-service-contexts/README.adoc

//OpenShift Streams for Apache Kafka
:product-long-kafka: OpenShift Streams for Apache Kafka
:product-kafka: Streams for Apache Kafka
:product-version-kafka: 1
:service-url-kafka: https://console.redhat.com/application-services/streams/
:getting-started-url-kafka: kafka/getting-started-kafka/README.adoc
:kafka-bin-scripts-url-kafka: kafka/kafka-bin-scripts-kafka/README.adoc
:kafkacat-url-kafka: kafka/kcat-kafka/README.adoc
:quarkus-url-kafka: kafka/quarkus-kafka/README.adoc
:nodejs-url-kafka: kafka/nodejs-kafka/README.adoc
:getting-started-rhoas-cli-url-kafka: kafka/rhoas-cli-getting-started-kafka/README.adoc
:topic-config-url-kafka: kafka/topic-configuration-kafka/README.adoc
:consumer-config-url-kafka: kafka/consumer-configuration-kafka/README.adoc
:access-mgmt-url-kafka: kafka/access-mgmt-kafka/README.adoc
:metrics-monitoring-url-kafka: kafka/metrics-monitoring-kafka/README.adoc
:service-binding-url-kafka: kafka/service-binding-kafka/README.adoc
:message-browsing-url-kafka: kafka/message-browsing-kafka/README.adoc

//OpenShift Service Registry
:product-long-registry: OpenShift Service Registry
:product-registry: Service Registry
:registry: Service Registry
:product-version-registry: 1
:service-url-registry: https://console.redhat.com/application-services/service-registry/
:getting-started-url-registry: registry/getting-started-registry/README.adoc
:quarkus-url-registry: registry/quarkus-registry/README.adoc
:getting-started-rhoas-cli-url-registry: registry/rhoas-cli-getting-started-registry/README.adoc
:access-mgmt-url-registry: registry/access-mgmt-registry/README.adoc
:content-rules-registry: https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1/guide/9b0fdf14-f0d6-4d7f-8637-3ac9e2069817[Supported Service Registry content and rules]
:service-binding-url-registry: registry/service-binding-registry/README.adoc

//OpenShift Connectors
:product-long-connectors: OpenShift Connectors
:product-connectors: Connectors
:product-version-connectors: 1
:service-url-connectors: https://console.redhat.com/application-services/connectors
:getting-started-url-connectors: connectors/getting-started-connectors/README.adoc
:getting-started-rhoas-cli-url-connectors: connectors/rhoas-cli-getting-started-connectors/README.adoc

//OpenShift API Designer
:product-long-api-designer: OpenShift API Designer
:product-api-designer: API Designer
:product-version-api-designer: 1
:service-url-api-designer: https://console.redhat.com/application-services/api-designer/
:getting-started-url-api-designer: api-designer/getting-started-api-designer/README.adoc

//OpenShift API Management
:product-long-api-management: OpenShift API Management
:product-api-management: API Management
:product-version-api-management: 1
:service-url-api-management: https://console.redhat.com/application-services/api-management/

////
END GENERATED ATTRIBUTES
////

[id="chap-managing-service-registry-access"]
= Managing account access in {product-long-registry}
ifdef::context[:parent-context: {context}]
:context: managing-access-service-registry

// Purpose statement for the assembly
[role="_abstract"]
As a {registry} instance owner, an instance administrator, or an organization administrator in {product-long-registry}, you can manage the level of access that other user accounts and service accounts have to your {registry} instance. You can grant or remove access to your  {registry} instance for specific user accounts in your organization based on user roles. You can also allow other users or service accounts to manage the level of access to your instance for you.

{registry} instance owners or instance administrators can manage access for only the {registry} instances that they create or for instances that the owner has allowed them to access and change. Organization administrators can manage access for all {registry} instances.

//Additional line break to resolve mod docs generation error, not sure why. Leaving for now. (Stetson, 20 May 2021)

[id="con-registry-access-management_{context}"]
== Access management in {product-long-registry}

[role="_abstract"]
{product-long-registry} uses Role-Based Access Control (RBAC) to manage how other user accounts and service accounts access the {registry} instances that you create and the artifacts that they contain. You can manage access for only the {registry} instances that you create or for instances that the owner has allowed you to access and change.

An account in {product-long-registry} is either a user account or a service account. A user account enables users in your organization to access your {registry} instances. A service account enables client applications or tools to connect securely to your {registry} instances.


=== User roles in {product-long-registry}

The {registry} web console provides an *Access* tab on the {registry} instance page. {registry} instance owners, instance administrators, and organization administrators can use this tab to manage the following user roles:

Administrator:: Users with the Administrator role can perform the following tasks in this {registry} instance:
* View or write schema and API artifacts
* Configure user roles for access
* Configure {registry} settings
* Configure global rules for artifact compatibility and validity
* Import or export {registry} data
Manager:: Users with the Manager role can view or write schema and API artifacts in this {registry} instance.
Viewer:: Users with the Viewer role can view schema and API artifacts in this {registry} instance.

IMPORTANT: The owner of a {registry} instance has the Administrator role for that instance by default, and can assign roles in the same organization. Other user accounts or service accounts in the organization have no access to that instance by default.

In addition to the web console, the `rhoas` CLI provides commands to manage user roles. The core {registry} REST API also provides Admin API endpoints for managing user roles.

[id="proc-viewing-registry-roles_{context}"]
== Viewing user roles in a {registry} instance

[role="_abstract"]
You can view the user roles assigned to your {registry} instances to manage how other user accounts or service accounts interact with the instance and the artifacts that it contains. You can view user roles and accounts only for instances that you create or for instances that the owner has assigned you access to.

.Prerequisites
* You're logged in to the {registry} web console at {service-url-registry}[^].
* The {registry} instance is created and is in *Ready* state.
* The user accounts or service accounts that you want to view are created in the organization and are assigned user roles.


.Procedure
. In the {service-url-registry}[{registry} web console], click the name of the {registry} instance that you want to view roles and accounts for.
. Click the *Access* tab to view the roles and accounts assigned for this instance:
.. To view specific accounts, click *Account*, enter the user account or service account name, and click the search button.
.. To view accounts with a specific role, click *Role*, click *Filter by role*, and select the role you want (for example, *Administrator*), and then click the search button.
. When you are finished, click *Clear all filters*.

[id="proc-setting-registry-roles_{context}"]
== Assigning user roles in a {registry} instance

[role="_abstract"]
In {product-long-registry}, you can assign user roles for your {registry} instances to manage how other user accounts or service accounts interact with the instance and the artifacts that it contains. You can assign user roles only for instances that you create or for instances that the owner has assigned you access to.

.Prerequisites
* You're logged in to the {registry} web console at {service-url-registry}[^].
* The {registry} instance is created and is in *Ready* state.
* The user accounts or service accounts that you're assigning roles to are created in the organization.

.Procedure
. In the {service-url-registry}[{registry} web console], click the name of the {registry} instance that you want to assign roles for.
. Click the *Access* tab to view the accounts and roles assigned for this instance.
. Click *Grant access* to assign roles to accounts.
. In the *Account* field, select or enter the service account or user account name that you want to assign the role to:
** A service account enables your application or tool to connect securely to your instance.
** A user account enables users in your organization to access instances.
+
NOTE: If you don't see users in the list, ask your organization administrator to grant access to view other user accounts. For more information, see {base-url}{access-mgmt-url-registry}#proc-user-account-access_managing-access-service-registry[Allowing users to view other user accounts].
. Select the *Role* that you want to assign to your account, for example, *Manager* for write access to this instance.
. Click *Save*.

[id="proc-remove-registry-roles_{context}"]
== Editing or removing user roles in a {registry} instance

[role="_abstract"]
You can edit or remove the user roles assigned in your {registry} instances to manage how other user accounts or service accounts interact with the instance and the artifacts that it contains. You can edit or remove user roles only for the instances that you create or for instances that the owner has assigned you access to.

.Prerequisites
* You're logged in to the {registry} web console at {service-url-registry}[^].
* The {registry} instance is created and is in *Ready* state.
* The user accounts or service accounts are created in the organization and the user roles are assigned.

.Procedure
. In the {service-url-registry}[{registry} web console], click the name of the {registry} instance that you want to remove a user role for.
. Click the *Access* tab to view the accounts and roles assigned for this instance.
. Click the options menu (three vertical dots) next to the assigned *Role* name:
.. To change to a different role, click *Edit*, select the new user role, for example, *Viewer* for read-only access, and then click *Save*.
.. To remove the currently assigned role, click *Remove*, and then click *Remove* again to confirm.

[id="proc-user-account-access_{context}"]
== Allowing users to view other user accounts

[role="_abstract"]
As an organization administrator, you can use Role-Based Access Control (RBAC) in the {org-name} Hybrid Cloud Console  to allow users to view other users in an organization.

You set up access by assigning a predefined role called `User Access principal viewer` to a user group.
By assigning the role, users in the group can do the following tasks:

* View and select other users when changing owners and managing access to {registry} instances in the {registry} web console.
* Specify user names when managing {registry} instances using the `rhoas` CLI for {product-long-registry}.

.Prerequisites
* You're logged in to the {registry} web console at {service-url-registry}[^] as an organization administrator.
* A user group is created that contains the users to assign the role to.

NOTE: If you want to add the `User Access principal viewer` role to a single user, create a new group for that user only.

ifndef::community[]
For more information on setting up user access in the {org-name} Hybrid Cloud Console, see the link:https://access.redhat.com/documentation/en-us/red_hat_hybrid_cloud_console/[_User Access Configuration Guide for Role-based Access Control (RBAC)_^].
endif::[]

.Procedure

. At the top of the {service-url-registry}[{registry} web console], select the gear icon. 
. Click *Settings*, then *User Access*, and then *Groups*.
. Click the name of the user group.
. From the *Roles* tab, click *Add role*, and select `User Access principal viewer`.
. Click *Add to group*.
+
The role is also added to the list of selected roles on the *Roles* tab.

[role="_additional-resources"]
.Additional resources
* {base-url}{getting-started-url-registry}[_Getting started with {product-long-registry}_^]
* {base-url}{getting-started-rhoas-cli-url-registry}[_Getting started with the rhoas CLI for {product-long-registry}_^]
* {base-url-cli}{command-ref-url-cli}[_CLI command reference (rhoas)_^]
* https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/assets-attachments/registry-rest-api.htm[_Apicurio Registry REST API documentation_^]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
