apiVersion: console.openshift.io/v1
kind: QuickStarts
metadata:
  name: getting-started
  annotations:
    order: 1
spec:
  version: 0.1
  type:
    text: Quick start
    color: green
  displayName: !snippet/title README.adoc#chap-getting-started
  durationMinutes: 10
  icon: ''
  description: !snippet README.adoc#description
  prerequisites:
    - A Red Hat identity
    - Access to the Red Hat OpenShift Streams for Apache Kafka environment at https://console.redhat.com
    - JDK 11 or later
    - For Windows, the latest version of Oracle JDK
  introduction: !snippet README.adoc#introduction
  tasks:
    - !snippet/proc README.adoc#proc-creating-kafka-instance
    - !snippet/proc README.adoc#proc-creating-service-account
    - !snippet/proc README.adoc#proc-creating-kafka-topic
  conclusion: !snippet README.adoc#conclusion
  nextQuickStart:
    - 'kafkacat'
    - 'kafka-bin-scripts'
    - 'quarkus-kafka'
