////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////

//All OpenShift Application Services
:org-name: Application Services
:product-long-rhoas: OpenShift Application Services
:community:
:imagesdir: ./images
:property-file-name: app-services.properties
:samples-git-repo: https://github.com/redhat-developer/app-services-guides
:base-url: https://github.com/redhat-developer/app-services-guides/tree/main/docs/
:sso-token-url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
:cloud-console-url: https://console.redhat.com/
:service-accounts-url: https://console.redhat.com/application-services/service-accounts

//OpenShift Application Services CLI
:base-url-cli: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:command-ref-url-cli: commands
:installation-guide-url-cli: rhoas/rhoas-cli-installation/README.adoc
:service-contexts-url-cli: rhoas/rhoas-service-contexts/README.adoc

//OpenShift Streams for Apache Kafka
:product-long-kafka: OpenShift Streams for Apache Kafka
:product-kafka: Streams for Apache Kafka
:product-version-kafka: 1
:service-url-kafka: https://console.redhat.com/application-services/streams/
:getting-started-url-kafka: kafka/getting-started-kafka/README.adoc
:kafka-bin-scripts-url-kafka: kafka/kafka-bin-scripts-kafka/README.adoc
:kafkacat-url-kafka: kafka/kcat-kafka/README.adoc
:quarkus-url-kafka: kafka/quarkus-kafka/README.adoc
:nodejs-url-kafka: kafka/nodejs-kafka/README.adoc
:getting-started-rhoas-cli-url-kafka: kafka/rhoas-cli-getting-started-kafka/README.adoc
:topic-config-url-kafka: kafka/topic-configuration-kafka/README.adoc
:consumer-config-url-kafka: kafka/consumer-configuration-kafka/README.adoc
:access-mgmt-url-kafka: kafka/access-mgmt-kafka/README.adoc
:metrics-monitoring-url-kafka: kafka/metrics-monitoring-kafka/README.adoc
:service-binding-url-kafka: kafka/service-binding-kafka/README.adoc
:message-browsing-url-kafka: kafka/message-browsing-kafka/README.adoc

//OpenShift Service Registry
:product-long-registry: OpenShift Service Registry
:product-registry: Service Registry
:registry: Service Registry
:product-version-registry: 1
:service-url-registry: https://console.redhat.com/application-services/service-registry/
:getting-started-url-registry: registry/getting-started-registry/README.adoc
:quarkus-url-registry: registry/quarkus-registry/README.adoc
:getting-started-rhoas-cli-url-registry: registry/rhoas-cli-getting-started-registry/README.adoc
:access-mgmt-url-registry: registry/access-mgmt-registry/README.adoc
:content-rules-registry: https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1/guide/9b0fdf14-f0d6-4d7f-8637-3ac9e2069817[Supported Service Registry content and rules]
:service-binding-url-registry: registry/service-binding-registry/README.adoc

//OpenShift Connectors
:connectors: Connectors
:product-long-connectors: OpenShift Connectors
:product-connectors: Connectors
:product-version-connectors: 1
:service-url-connectors: https://console.redhat.com/application-services/connectors
:getting-started-url-connectors: connectors/getting-started-connectors/README.adoc
:getting-started-rhoas-cli-url-connectors: connectors/rhoas-cli-getting-started-connectors/README.adoc

//OpenShift API Designer
:product-long-api-designer: OpenShift API Designer
:product-api-designer: API Designer
:product-version-api-designer: 1
:service-url-api-designer: https://console.redhat.com/application-services/api-designer/
:getting-started-url-api-designer: api-designer/getting-started-api-designer/README.adoc

//OpenShift API Management
:product-long-api-management: OpenShift API Management
:product-api-management: API Management
:product-version-api-management: 1
:service-url-api-management: https://console.redhat.com/application-services/api-management/

////
END GENERATED ATTRIBUTES
////

[id="chap-managing-access"]
= Managing account access in {product-long-kafka}
ifdef::context[:parent-context: {context}]
:context: managing-access

// Purpose statement for the assembly
[role="_abstract"]
As an owner of a Kafka instance in {product-long-kafka}, you can manage the level of access that other user accounts and service accounts have to your instance. You can allow or deny access to your instance for specific accounts or for all accounts in your organization. You can also allow other users or service accounts to manage the level of access to your instance for you.

You can manage access for only the Kafka instances that you create or for instances that the owner has enabled you to access and alter.

//Additional line break to resolve mod docs generation error, not sure why. Leaving for now. (Stetson, 20 May 2021)

[id="con-access-management_{context}"]
== Access management in {product-kafka}

[role="_abstract"]
{product-long-kafka} uses Access Control Lists (ACLs) provided by Apache Kafka that enable you to manage how other user accounts and service accounts are permitted to access the Kafka resources that you create. You can manage access for only the Kafka instances that you create or for instances that the owner has enabled you to access and alter.

An account in {product-kafka} is either a user account or a service account. A user account enables users in your organization to access your resources. A service account enables your application or tool to connect securely to your instance and access your resources.

A resource in an ACL can be a Kafka instance, topic, consumer group, or producer transaction. You use the ACL to define how specific accounts or all accounts in an organization are permitted to access these resources.

An ACL permission setting typically consists of the following components:

* A single named account or all accounts within the organization that you want to manage access for
* A single named resource, all resources of a particular type (such as a topic, consumer group, or transactional ID), or all resources of a particular type with a specified prefix
* A single operation (such as `Write`) or all operations for the specified resource or resources

You can also allow other users or service accounts to manage access to the resources in your instance for you.

If two or more permission settings in an ACL match a request being made to the Kafka broker and at least one of the matching permissions specifies that the action is denied, then the request is denied.

[role="_additional-resources"]
.Additional resources
* link:https://kafka.apache.org/documentation/#security_authz[Authorization and ACLs^] in Kafka documentation

=== Supported ACL permissions in {product-kafka}

An ACL acts as a mapping of permitted operations on specified resources for a selected account or for all accounts in an organization. An account can be either a user account or a service account. Operations correspond to Kafka APIs or request types that relate to the specified resource.

For example, a `Read` operation for a `Topic` resource corresponds to the `Fetch`, `OffsetCommit`, and `TxnOffsetCommit` Kafka requests. A `Write` operation for a `Topic` resource corresponds to the `Produce` and `AddPartitionsToTxn` Kafka requests.

The following table lists the supported ACL permissions in {product-kafka}.

NOTE: The resource identifier `Is` supports the wildcard character `*` to denote any occurrences of the specified resource. For example, `Topic is *` means any topic in a Kafka instance.

.Supported ACL permissions
[cols="25%,25%,25%,25%"]
|===
h|Resource type
h|Resource identifier
h|Access type
h|Operations

|`Consumer group`

(For consumer group access to a resource)
a|
* `Starts with`
* `Is`
a|
* `Allow`
* `Deny`
a|
* `All`
* `Read`
* `Delete`
* `Describe`

|`Topic`

(For access to a topic)
a|
* `Starts with`
* `Is`
a|
* `Allow`
* `Deny`
a|
* `All`
* `Read`
* `Write`
* `Create`
* `Delete`
* `Alter`
* `Alter configs`
* `Describe`
* `Describe configs`

|`Transactional ID`

(For producer access to a resource)
a|
* `Starts with`
* `Is`
a|
* `Allow`
* `Deny`
a|
* `All`
* `Write`
* `Describe`

|`Kafka instance`

(For access to Kafka instance permissions in ACLs)
|None
a|
* `Allow`
* `Deny`
a|
* `Alter`
* `Describe`
|===

By default, new Kafka instances contain the permissions shown in the following table. These permissions allow all accounts in the organization to view the instance permissions and to view topics in the instance, but not to produce or consume messages.

.Default ACL permissions for new Kafka instances
[cols="25%,25%,25%,25%"]
|===
h|Account
h|Resource
h|Access type
h|Operation

|`All accounts`
|`Topic is *`

(Any topic)
|`Allow`
|`Describe`, `Describe configs`

|`All accounts`
|`Consumer group is *`

(Any consumer group)
|`Allow`
|`Describe`

|`All accounts`
|`Kafka instance`

(Kafka instance permissions in ACLs)
|`Allow`
|`Describe`
|===

[role="_additional-resources"]
.Additional resources
https://kafka.apache.org/documentation/#security_authz_primitives[Authorization Primitives^] in Kafka documentation

[id="proc-setting-permissions_{context}"]
== Setting account permissions in a Kafka instance in {product-kafka}

[role="_abstract"]
In {product-long-kafka}, you can create Access Control Lists (ACLs) in your Kafka instances and set permissions for how other user accounts or service accounts can interact with an instance and its resources. You can manage access for only the Kafka instances that you create or for the instances that the owner has enabled you to access and alter.

.Prerequisites
* You've created a Kafka instance and the instance is in the *Ready* state.
* The user account or service account that you're setting permissions for has been created in the organization.

.Procedure
. On the {service-url-kafka}[Kafka Instances^] page of the {product-kafka} web console, click the name of the Kafka instance that you want to set permissions for.
. Click the *Access* tab to view the current ACL permissions for this instance.
. Use this *Access* page to set permissions for a new account, add permissions to an existing account, or delete account permissions in this instance.
+
* To set permissions for a new account in this instance, follow these steps:

.. Click *Manage access*.
.. In the *Account* list, select the new user account or service account that you want to set permissions for. You can also select *All accounts* to set permissions for all user accounts and service accounts in the organization.
+
If you don't see users in the *Account* list, ask your organization administrator to grant access to view other user accounts. For more information, see {base-url}{access-mgmt-url-kafka}#proc-user-account-access_managing-access[Allowing users to view other user accounts].
.. Click *Next*.
+
--
The *Review existing permissions* section lists any permission settings in this instance that are already defined for all accounts in the organization and for the same account that you previously selected, if applicable. You can delete existing permissions now if needed, or you can wait to delete existing permissions later from the main *Access* page.

If you previously selected a specific account, you can delete only permission entries that apply to individual accounts. If you previously selected *All accounts*, you can delete only permission entries that apply to all accounts.
--
.. Under *Assign Permissions*, use the list to select and define the permissions for the specified account or all accounts for a resource type, such as a topic.
+
--
The following permission options are available:

** *Add permission*: Empty permission entry that you must define manually
** *Consume from a topic*: Predefined permission entry for consuming from one or more specified topics
** *Produce to a topic*: Predefined permission entry for producing to one or more specified topics
** *Manage access*: Predefined permission entry for allowing other user accounts or service accounts to access and alter the permissions in the Kafka instance

For example, when you create a new service account, select the *Consume from a topic* and *Produce to a topic* predefined options and set all resource identifiers and values to `Is *`. These permissions enable applications associated with the service account to create and delete topics in the Kafka instance, to produce and consume messages in any topic in the instance, and to use any consumer group and any producer.

These permission settings result in the following ACL permissions for the new service account:

.Example ACL permissions for a new service account
[cols="25%,25%,25%,25%"]
|===
h|Resource type
h|Resource identifier and value
h|Access type
h|Operation

|`Topic`

(For consuming)
|`Is` = `*`
|`Allow`
|`Read`, `Describe`

|`Consumer group`

(For consuming)
|`Is` = `*`
|`Allow`
|`Read`

|`Topic`

(For producing)
|`Is` = `*`
|`Allow`
|`Write`, `Create`, `Describe`
|===

NOTE: Alternatively, you can click *Add permission* to individually create one `Topic` entry and one `Consumer group` entry, both with `Allow` access to `All` operations. This enables both consuming and producing for the topic in a single entry, and enables all permissions for the consumer group in a single entry. But you must configure these entries individually without using the predefined permission options.

--
.. Click *Save* to finish.

* To add permissions to an existing account in this instance, follow these steps:

.. For the account that you want to add permissions to, select the options icon (three vertical dots) for that entry and click *Manage*.
+
--
The *Review existing permissions* section lists any permission settings in this instance that are already defined for all accounts in the organization and for the same account that you previously selected, if applicable. You can delete existing permissions now if needed, or you can wait to delete existing permissions later from the main *Access* page.

If you selected a permission entry that applies to a specific account, you can delete only permission entries that apply to individual accounts. If you selected a permission entry that applies to all accounts, you can delete only permission entries that apply to all accounts.
--
.. Under *Assign Permissions*, use the list to select and define the permissions for the specified account or all accounts for a resource type, such as a topic. You can click *Add permission* to add permissions individually, or you can select from the predefined permission options as described previously.
.. Click *Save* to finish.

* To delete existing account permissions in this instance, use the following options:

 ** Select one or more permission entries, select the options icon (three vertical dots) at the top of the table, and click *Delete selected permissions*.
 ** For the account that you want to delete, select the options icon (three vertical dots) for that entry and click *Delete*.

+
IMPORTANT: If you delete a user account or service account, you must also delete any ACL permissions associated with that account. If you don't delete unused ACL permissions, then a future account with the same ID of a previously deleted account could inherit the ACL permissions and have automatic access to a Kafka instance.


[role="_additional-resources"]
.Additional resources
* link:https://kafka.apache.org/documentation/#security_authz[Authorization and ACLs^] in Kafka documentation

[id="ref-example-access-scenarios_{context}"]
== Example account access scenarios in {product-kafka}

[role="_abstract"]
The following example Access Control Lists (ACLs) illustrate common scenarios for managing the level of access for user accounts or service accounts in {product-long-kafka}. Some examples differ from the predefined permissions in {product-kafka} to demonstrate various possible ACL scenarios. Use these examples as a guide for your own ACLs.

Access for a new service account in a Kafka instance::
+
--
You’ve created a new service account and you want to allow it to create and delete topics in the instance, to produce and consume messages in any topic in the instance, and to use any consumer group and any producer.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource type
h|Resource identifier and value
h|Access type
h|Operation

|`srvc-acct-1a2b3c4d-...`
|`Topic`
|`Is` = `*`
|`Allow`
|`All`

|`srvc-acct-1a2b3c4d-...`
|`Consumer group`
|`Is` = `*`
|`Allow`
|`Read`
|===
--

Access for all accounts in a Kafka instance::
+
--
You want this Kafka instance to be fully accessible to all accounts in the organization. You want any user to be able to read all topics, write to all topics, use any consumer group, and use any producer.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource
h|Resource identifier and value
h|Access type
h|Operations

|`All accounts`
|`Topic`
|`Is` = `*`
|`Allow`
|`All`

|`All accounts`
|`Consumer group`
|`Is` = `*`
|`Allow`
|`All`
|===
--

Access for a specific user in a Kafka instance::
+
--
You want this Kafka instance to be fully accessible to a specific user. You don't know which topics or consumer groups the user will use, so you want the user to be able to read any topic, write to any topic, and join any consumer group in the instance.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource
h|Resource identifier and value
h|Access type
h|Operations

|`usr-acct-1a2b3c4d-...`
|`Topic`
|`Is` = `*`
|`Allow`
|`All`

|`usr-acct-1a2b3c4d-...`
|`Consumer group`
|`Is` = `*`
|`Allow`
|`All`
|===
--

Access for a specific producer to write to a topic::
+
--
You want to allow a user account with a producer that is associated with a specific `transactional.id` value to produce messages to a specific topic in this Kafka instance.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource
h|Resource identifier and value
h|Access type
h|Operations

|`usr-acct-1a2b3c4d-...`
|`Topic`
|`Is` = `topic-1`
|`Allow`
|`Write`

|`usr-acct-1a2b3c4d-...`
|`Transactional ID`
|`Is` = `producer-1`
|`Allow`
|`All`
|===
--

Access for specific consumer groups to consume from a topic::
+
--
You want to allow a service account with consumers from consumer groups whose names start with `app` to consume messages from a specific topic in this Kafka instance.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource
h|Resource identifier and value
h|Access type
h|Operations

|`srvc-acct-1a2b3c4d-...`
|`Topic`
|`Is` = `topic-1`
|`Allow`
|`Read`

|`srvc-acct-1a2b3c4d-...`
|`Consumer group`
|`Starts with` = `app`
|`Allow`
|`Read`
|===
--

Access for a specific user to manage all permissions in the ACL of a Kafka instance::
+
--
You want to allow a user account to manage all permissions in the ACL for this Kafka instance. You've removed all other permissions from this instance so that the new authorized user can define the new ACL as needed.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource
h|Resource identifier and value
h|Access type
h|Operations

|`usr-acct-1a2b3c4d-...`
|`Kafka instance`
|None
|`Allow`
|`Alter`

|`usr-acct-1a2b3c4d-...`
|`Kafka instance`
|None
|`Allow`
|`Describe`
|===
--

[id="proc-user-account-access_{context}"]
== Allowing users to view other user accounts

[role="_abstract"]
As an organization administrator, you can use Role-Based Access Control (RBAC) to allow users to view other users in an organization.

You set up access by assigning a predefined role called `User Access principal viewer` to a user group.
By assigning the role, users within the group are able to perform the following actions:

* View and select other users when changing owners and managing access to Kafka instances in the {service-url-kafka}[Openshift Streams for Apache Kafka] web console.
* Specify user names when using the `rhoas` CLI for {product-long-kafka}.

.Prerequisites
* You're logged into the {cloud-console-url}[Red Hat Hybrid Cloud Console] as an organization administrator.
* A user group contains the users to assign the role to.

NOTE: If you want to add the `User Access principal viewer` role to a single user, create a new group for that user only.

ifndef::community[]
For more information on setting up user access in the Red Hat Hybrid Cloud Console, see the link:https://access.redhat.com/documentation/en-us/red_hat_hybrid_cloud_console/[User Access Configuration Guide for Role-based Access Control (RBAC)^].
endif::[]

.Procedure

. In the upper-right corner of the {product-kafka} web console, select the gear icon, and click *Settings* > *User Access* > *Groups*
. Click the name of the user group.
. From the *Roles* tab, click *Add role* and select `User Access principal viewer`.
. Click *Add to group* to add the role to the group.
+
The role is added to the list of selected roles on the *Roles* tab.

[role="_additional-resources"]
.Additional resources
* {base-url}{getting-started-url-kafka}[Getting started with {product-long-kafka}^]
* {base-url}{getting-started-rhoas-cli-url-kafka}[Getting started with the `rhoas` CLI for {product-long-kafka}^]
* {base-url-cli}{command-ref-url-cli}[CLI command reference (rhoas)^]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
