////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////


:org-name: Application Services
:community:
:imagesdir: ./images
:product-version: 1
:product-long: OpenShift Streams for Apache Kafka
:product: Streams for Apache Kafka
:registry-product-long: OpenShift Service Registry
:registry-product: Service Registry
:registry: Service Registry
// Placeholder URL, when we get a HOST UI for the service we can put it here properly
:service-url: https://console.redhat.com/application-services/streams/
:registry-url: https://console.redhat.com/application-services/service-registry/
:property-file-name: app-services.properties

// Other upstream project names
:samples-git-repo: https://github.com/redhat-developer/app-services-guides

//URL components for cross refs
:base-url: https://github.com/redhat-developer/app-services-guides/blob/main/
:base-url-cli: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:getting-started-url: getting-started/README.adoc
:getting-started-service-registry-url: getting-started-service-registry/README.adoc
:kafka-bin-scripts-url: kafka-bin-scripts/README.adoc
:kafkacat-url: kafkacat/README.adoc
:quarkus-url: quarkus/README.adoc
:quarkus-service-registry-url: quarkus-service-registry/README.adoc
:rhoas-cli-url: rhoas-cli/README.adoc
:rhoas-cli-kafka-url: rhoas-cli-kafka/README.adoc
:rhoas-cli-service-registry-url: rhoas-cli-service-registry/README.adoc
:rhoas-cli-ref-url: commands
:topic-config-url: topic-configuration/README.adoc
:consumer-config-url: consumer-configuration/README.adoc
:service-binding-url: service-discovery/README.adoc
:access-mgmt-url: access-mgmt/README.adoc
:access-mgmt-service-registry-url: access-mgmt-service-registry/README.adoc
:metrics-monitoring-url: metrics-monitoring/README.adoc

////
END GENERATED ATTRIBUTES
////

[id="chap-getting-started-rhoas-cli-registry"]
= Getting started with the rhoas CLI for {registry-product-long}
:context: getting-started-rhoas-service-registry

[role="_abstract"]
With the `rhoas` command-line interface (CLI), you can manage OpenShift Service Registry from a terminal.

As a developer of applications and services,
you can use `rhoas` to create Service Registry instances and connect your applications and services to these instances.
You can also manage artifacts.
Artifacts are items stored in Service Registry, like schemas and API specifications.

This guide describes how to get started quickly by doing the following tasks:

* link:{base-url}{rhoas-cli-service-registry-url}#proc-creating-service-registry-instance-cli_getting-started-rhoas-service-registry[Create a Service Registry instance]
* link:{base-url}{rhoas-cli-service-registry-url}#proc-creating-service-registry-account_getting-started-rhoas-service-registry[Create a service account]
* link:{base-url}{rhoas-cli-service-registry-url}#proc-uploading-service-registry-artifacts_getting-started-rhoas-service-registry[Upload Service Registry artifacts]
* link:{base-url}{rhoas-cli-service-registry-url}#proc-downloading-service-registry-artifacts_getting-started-rhoas-service-registry[Download Service Registry artifacts]
* link:{base-url}{rhoas-cli-service-registry-url}#proc-updating-service-registry-artifacts_getting-started-rhoas-service-registry[Update Service Registry artifacts]
* link:{base-url}{rhoas-cli-service-registry-url}#proc-commands-managing-registry_getting-started-rhoas-service-registry[Use `rhoas` to manage your Service Registry instance, service accounts, and artifacts]

//Additional line break to resolve mod docs generation error

[id="ref-service-registry-cli-prereqs_{context}"]
== Prerequisites

[role="_abstract"]
* You've installed the `rhoas` CLI. For more information, see {base-url}{rhoas-cli-url}[_Installing the rhoas CLI_^].

[id="proc-creating-service-registry-instance-cli_{context}"]
== Creating a Service Registry instance

[role="_abstract"]
A Service Registry instance serves as a central location for storing artifacts.

.Prerequisites

* You are logged in to `rhoas`.

.Procedure

. Enter the following command to create a Service Registry instance with default values.
+
--
This example creates a Service Registry instance called `my-registry`.

.Creating a Service Registry instance
[source,shell]
----
$ rhoas service-registry create --name my-registry
Creating Service Registry instance with name: my-registry
✔️ Successfully created Service Registry instance
{
  "browserUrl": "https://console.redhat.com/beta/application-services/service-registry/t/63620903-4a29-4ba4-8229-7ab793bf73f3",
  "created_at": "2021-09-27T15:35:01Z",
  "href": "/api/serviceregistry_mgmt/v1/registries/63620903-4a29-4ba4-8229-7ab793bf73f3",
  "id": "63620903-4a29-4ba4-8229-7ab793bf73f3",
  "instance_type": "standard",
  "kind": "ServiceRegistry",
  "name": "my-registry",
  "owner": "User",
  "status": "accepted",
  "updated_at": "2021-09-27T15:35:01Z"
}
----

[NOTE]
====
If you do not want to use the default values,
enter the following command: `rhoas service-registry create`.
You are prompted to enter the `Name` for the Service Registry instance.
====
--

. Enter the following command to verify that the Service Registry instance is ready to use.
+
--
This command shows that the Service Registry instance is ready to use,
because the `Status` field is `ready`.

.Reviewing details of a Service Registry instance
[source,shell]
----
$ rhoas status service-registry

  Service Registry
  -----------------------------------------------------------
  ID:                    63620903-4a29-4ba4-8229-7ab793bf73f3
  Name:                  my-registry
  Status:                ready
  Registry URL:          https://service-registry-service-registry-production.apps.app-sre-prod-04.i5h0.p1.openshiftapps.com/t/63620903-4a29-4ba4-8229-7ab793bf73f3
----

[NOTE]
====
When you created the Service Registry instance, it was set as the current instance automatically.
If you have multiple Service Registry instances,
you can switch to a different instance by using the `rhoas service-registry use` command.
====
--

[id="proc-creating-service-registry-account_{context}"]
== Creating a service account

[role="_abstract"]
To connect your applications or services to a Service Registry instance, you must first create a service account with credentials.
The credentials are exported to a file on your computer,
which you can use to authenticate your application with your Service Registry instance.

.Prerequisites

* You have created a Service Registry instance, and it has a `ready` status.

.Procedure

. Enter the following command to create a service account.
+
--
This example creates a service account and saves the credentials in a JSON file.

.Creating a service account
[source,shell]
----
$ rhoas service-account create --short-description="rhoas-service-account" --file-format json
Creating service account
✔️ Service account created successfully with ID "04ba07d6-b08c-45fb-af53-3522c1b4c32f".
✔️ Credentials saved to /home/developer/my-project/credentials.json

You can now set access rules for your current services.
To grant full access to produce and consume Kafka messages, enter this command:

 $ rhoas kafka acl grant-access --producer --consumer --service-account srvc-acct-04ba07d6-b08c-45fb-af53-3522c1b4c32f --topic all --group all

To grant read and write access to the currently selected Service Registry instance, enter this command:

 $ rhoas service-registry role add --role DEVELOPER --service-account srvc-acct-04ba07d6-b08c-45fb-af53-3522c1b4c32f
----

Your service account credentials are created and saved to a JSON file.

[NOTE]
====
When creating a service account, you can choose the file format and location to save the credentials.
For more information, see the `rhoas service-account create` command help.
====
--

. To verify your service account credentials,
view the `credentials.json` file that you created.
+
--
.Verifying service account credentials
[source,shell]
----
$ cat credentials.json
{
	"clientID":"srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1",
	"clientSecret":"facf3df1-ab97-2253-aa87-ab97",
    "oauthTokenUrl": "https://identity.api.openshift.com/auth/realms/rhoas/protocol/openid-connect/token"
}
----
You'll use these credentials and the Service Registry URL to connect your applications and services to your Service Registry instance.

[NOTE]
====
By connecting your applications to your Service Registry instance, you can retrieve artifacts and use them directly in your service.
====
--

. Create a role for the new service account that can read and write artifacts.
+
This example creates a role called `DEVELOPER` for the service account.
+
--
.Creating a role for the service account
[source,shell]
----
$ rhoas service-registry role add --role DEVELOPER --service-account=srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1
Creating new role for principal
Role was successfuly applied
----
--

[id="proc-uploading-service-registry-artifacts_{context}"]
== Uploading Service Registry artifacts

[role="_abstract"]
After creating a Service Registry instance, you can start uploading Service Registry artifacts.
Artifacts might include, for example, schemas that define the structure of Kafka data or OpenAPI documents to define an API.

.Prerequisites

* You have created a Service Registry instance, and it has a `ready` status.

[NOTE]
====
You can use `rhoas service-registry use` to switch to a specific Service Registry instance.

.Selecting a Service Registry instance to use
[source,shell]
----
$ rhoas service-registry use --name my-registry
Service Registry instance "my-registry" has been set as the current instance.
----
====

.Procedure

. Upload a Service Registry artifact.
+
--
This example uploads a Service Registry artifact called `my-artifact` to the Service Registry instance.
The artifact is an Apache Kafka Avro schema in JSON format.

.Uploading an artifact
[source,shell]
----
$ wget https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/docs/resources/avro-userInfo.json
--2021-09-27 16:17:18--  https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/docs/resources/avro-userInfo.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 732 [text/plain]
Saving to: ‘avro-userInfo.json’

avro-userInfo.json  100%[==================>]     732  --.-KB/s    in 0.001s

2021-09-27 16:17:18 (746 KB/s) - ‘avro-userInfo.json’ saved [732/732]


$ rhoas service-registry artifact create --type=AVRO --artifact-id=my-artifact avro-userInfo.json
Using default artifacts group.
Opening file: avro-userInfo.json
Artifact created
You can view or manage this artifact in your browser by accessing:
https://console.redhat.com/application-services/service-registry/t/63620903-4a29-4ba4-8229-7ab793bf73f3/artifacts/default/my-artifact/versions/1

{
  "contentId": 29,
  "createdBy": "User",
  "createdOn": "2021-09-27T16:17:35+0000",
  "globalId": 28,
  "id": "my-artifact",
  "modifiedBy": "User",
  "modifiedOn": "2021-09-27T16:17:35+0000",
  "name": "userInfo",
  "state": "ENABLED",
  "type": "AVRO",
  "version": "1"
}
----
--

. Verify that the artifact was registered.
+
--
This example lists all artifacts belonging to the Service Registry instance.

.Listing artifact details for a Service Registry instance
[source,shell]
----
$ rhoas service-registry artifact list
Using default artifacts group.

  ID            NAME      CREATED ON                 CREATED BY   TYPE   STATE
 ------------- --------- -------------------------- ------------ ------ --------
  my-artifact   userInfo  2021-09-27T16:17:35+0000   User         AVRO   ENABLED
----
--

. Check the version and metadata information for the artifact.
+
--
.Checking the version information of an artifact
[source,shell]
----
$ rhoas service-registry artifact versions --artifact-id=my-artifact
{
  "count": 1,
  "versions": [
    {
      "contentId": 29,
      "createdBy": "User",
      "createdOn": "2021-09-27T16:17:35+0000",
      "globalId": 28,
      "name": "userInfo",
      "state": "ENABLED",
      "type": "AVRO",
      "version": "1"
    }
  ]
}
----

.Checking the metadata information of an artifact
[source,shell]
----
$ rhoas service-registry artifact metadata-get --artifact-id=my-artifact
Using default artifacts group.
Fetching artifact metadata
✔️ Successfully fetched artifact metadata
You can view or manage this artifact in your browser by accessing:
https://console.redhat.com/application-services/service-registry/t/63620903-4a29-4ba4-8229-7ab793bf73f3/artifacts/default/my-artifact/versions/1

{
  "contentId": 29,
  "createdBy": "User",
  "createdOn": "2021-09-27T16:17:35+0000",
  "globalId": 28,
  "id": "my-artifact",
  "modifiedBy": "User",
  "modifiedOn": "2021-09-27T16:17:35+0000",
  "name": "userInfo",
  "state": "ENABLED",
  "type": "AVRO",
  "version": "1"
}
----

[NOTE]
====
You can use additional options, such as `--group`, `--version`, and  `--description`, to modify the metadata of the artifact you're creating.
For more information about any of the options, view the command help `rhoas service-registry artifact metadata-set -h`.
====
--

[id="proc-downloading-service-registry-artifacts_{context}"]
== Downloading Service Registry artifacts

[role="_abstract"]
After you register a Service Registry artifact, you can download the artifact to update it.

.Prerequisites

* You have created a Service Registry instance with at least one artifact.

.Procedure

Download the artifact in either of the following ways:

* Use the `rhoas service-registry artifact get` command and specify the artifact ID.
* Use the `rhoas service-registry artifact download` command and specify the global ID.

[NOTE]
====
To find the artifact ID, use the `rhoas service-registry artifact list` command.

To find the global ID, see the Kafka Message payload.
====

--
The following example downloads the `my-artifact` artifact by using its ID.

.Downloading an artifact by using the artifact ID
[source,shell]
----
$ rhoas service-registry artifact get --artifact-id=my-artifact
----

The following example downloads the `my-artifact` artifact by using its global ID.

.Downloading an artifact by using the global ID
[source,shell]
----
$ rhoas service-registry artifact download --global-id=28
----
--

[NOTE]
====
You can use additional options, such as `--group` and `--instance-id`, to specify the artifact to download.
For more information about any of the options, view the command help `rhoas service-registry artifact download -h` and `rhoas service-registry artifact get -h`.
====

[id="proc-updating-service-registry-artifacts_{context}"]
== Updating Service Registry artifacts

[role="_abstract"]
You can update an artifact with content from a file or from standard input.

.Prerequisites

* You have created a Service Registry instance with at least one artifact.
* The type of the updated content is compatible with the current artifact type.

.Procedure

. Update a Service Registry artifact.
+
--
This example updates a Service Registry artifact called `my-artifact` with content from a file in JSON format.

.Updating an artifact from a file
[source,shell]
----
$ rhoas service-registry artifact update --artifact-id=my-artifact my-artifact.json
----

[NOTE]
====
If you want to update the artifact from standard input,
enter the following command:

`$ rhoas service-registry artifact update --artifact-id=my_artifact`

Paste the updated artifact content on the command line, and then press Ctrl+D to save.
====
--

. Verify that the artifact was updated. The updated artifact is saved as a new version.
+
--
.Checking the version number and modified date of an artifact
[source,shell]
----
$ rhoas service-registry artifact metadata-get --artifact-id=my-artifact
Using default artifacts group.
Fetching artifact metadata
✔️ Successfully fetched artifact metadata
You can view or manage this artifact in your browser by accessing:
https://console.redhat.com/application-services/service-registry/t/63620903-4a29-4ba4-8229-7ab793bf73f3/artifacts/default/my-artifact/versions/2

{
  "contentId": 30,
  "createdBy": "User",
  "createdOn": "2021-09-27T16:17:35+0000",
  "globalId": 29,
  "id": "my-artifact",
  "modifiedBy": "User",
  "modifiedOn": "2022-01-17T12:19:56+0000",
  "state": "ENABLED",
  "type": "AVRO",
  "version": "2"
}
----

[NOTE]
====
You can use additional options, such as `--group` and `--version`, to specify the artifact to update.
For more information about any of the options, view the command help `rhoas service-registry artifact update -h`.
====
--

[id="proc-commands-managing-registry_{context}"]
== Commands for managing Service Registry

[role="_abstract"]
For more information about the `rhoas` commands you can use to manage your Service Registry instance,
use the following command help:

* `rhoas service-registry -h` for Service Registry instances
* `rhoas service-account -h` for service accounts
* `rhoas service-registry artifact -h` for Service Registry artifacts

[role="_additional-resources"]
.Additional resources
* {base-url-cli}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
