[id='assembly-kafka-bin-scripts']
= Configuring and connecting Kafka scripts with {product-long}
ifdef::context[:parent-context: {context}]
:context: using-kafka-bin-scripts
:imagesdir: _images

// Purpose statement for the assembly
[role="_abstract"]
As a developer of applications and services, you can use Kafka scripts to manage your Kafka instances in {product-long}.
The Kafka scripts are a set of shell scripts that are included with the https://kafka.apache.org/downloads[Apache Kafka distribution^].
With these scripts, you can produce and consume messages for your Kafka instances.

ifndef::community[]
NOTE: The Kafka scripts are part of the open source community version of Apache Kafka. The scripts are not a part of {product} and are therefore not supported by Red Hat.
endif::[]

When you download and extract the Apache Kafka distribution, the `bin/` directory (or the `bin\windows\` directory if you're using Windows) of the distribution contains a set of shell scripts that enable you to interact with your Kafka instance.
With the scripts, you can produce and consume messages, and perform various operations against the Kafka APIs to administer topics, consumer groups, and other resources.

NOTE: The command examples in this quick start demonstrate how to use the Kafka scripts on Linux and macOS. If you're using Windows, use the Windows versions of the scripts. For example, instead of the `__<Kafka-distribution-dir>__/bin/kafka-console-producer.sh` script, use the `__<Kafka-distribution-dir>__\bin\windows\kafka-console-producer.bat` script.

.Prerequisites
ifndef::community[]
* You have a Red Hat account.
endif::[]
* You have a running Kafka instance in {product}.
* https://adoptopenjdk.net/[JDK^] 11 or later is installed.
* For Windows, the latest version of https://www.oracle.com/java/technologies/javase-downloads.html[Oracle JDK^] is installed.
* You've downloaded the latest supported binary version of the https://kafka.apache.org/downloads[Apache Kafka distribution^].
+
.Verifying Kafka scripts
[source]
----
$ ./kafka-console-producer.sh --version
3.0.0 (Commit:8cb0a5e9d3441962)
----

ifdef::qs[]
[#description]
Learn how to use Kafka scripts to interact with a Kafka instance in {product-long}.

[#introduction]
Welcome to the quick start for {product-long} with Kafka scripts. In this quick start, you'll learn how to use the Kafka scripts to produce and consume messages for your Kafka instances in {product}.
endif::[]
ifndef::community[]
endif::[]
ifndef::community[]
endif::[]
ifdef::qs[]
endif::[]
include::modules/guides/proc-configuring-kafka-bin-scripts.adoc[leveloffset=+1]

include::modules/guides/proc-producing-messages-kafka-bin-scripts.adoc[leveloffset=+1]

include::modules/guides/proc-consuming-messages-kafka-bin-scripts.adoc[leveloffset=+1]


