[id='assembly-connectors-rhoas-cli']
= Managing {product-connectors} by using the {product-rhoas} CLI
ifdef::context[:parent-context: {context}]
:context: connectors-rhoas-cli
:imagesdir: _images

// Purpose statement for the assembly
[role="_abstract"]
As a developer of {product-long-connectors}, you can use the `rhoas` command-line interface (CLI) to create and configure connections between {product-long-kafka} and third-party systems.

You can use a *source* connector to send data from an external system to {product-kafka}. You can use a *sink* connector to send data from {product-kafka} to an external system.

For the example in this guide, you create a source connector that sends data from a simple data generator to a Kafka topic. You also create a sink connector that sends data from the Kafka topic to an HTTP site.

Use this guide to complete the following tasks:

* {base-url}{getting-started-rhoas-cli-url-connectors}#proc-create-connector-namespace_connectors-rhoas-cli[Create a namespace to host your {product-connectors} instances]
* {base-url}{getting-started-rhoas-cli-url-connectors}#proc-building-connector-configuration-cli_connectors-rhoas-cli[Build a configuration file for each type of connector that you want to create]
* {base-url}{getting-started-rhoas-cli-url-connectors}#proc-create-connector-instances_connectors-rhoas-cli[Create {connectors} instances]

.Prerequisites

* You have a {org-name} account.
* You've installed the latest version of the `rhoas` CLI. See {base-url}{installation-guide-url-cli}[Installing and configuring the rhoas CLI^].
* You've completed the following tasks:
+
*Note:* You can find detailed instructions for these tasks in {base-url}{getting-started-rhoas-cli-url-kafka}[Getting started with the rhoas CLI for {product-long-kafka}^].

** Create a Kafka instance.
[source,subs="+quotes"]
+
----
$ rhoas kafka create --name=my-kafka-instance
----

** Verify that the Kafka instance is in the *Ready* state.
+
[source,subs="+quotes"]
----
$ rhoas context status kafka
----

** Create a service account and copy the service account ID and secret. You must use a service account to connect and authenticate your {product-connectors} instances with your Kafka instance.
+
[source,subs="+quotes"]
----
$ rhoas service-account create --file-format=json --short-description=test-service-account
----

** For your Kafka instance, set the permissions for the service account to enable {connectors} instances (that are configured with the service account credentials) to produce and consume messages in any topic in the Kafka instance.
+
[source,subs="+quotes"]
----
$ rhoas kafka acl grant-access --producer --consumer --service-account=<service-acct-id> --topic all --group all
----

** Create a Kafka topic named `test-topic`. The Kafka topic stores messages sent by producers (data sources) and makes them available to consumers (data sinks).
+
[source,subs="+quotes"]
----
$ rhoas kafka topic create --name=test-topic
----

include::modules/guides/proc-create-connector-namespace.adoc[leveloffset=+1]

include::modules/guides/proc-building-connector-configuration-cli.adoc[leveloffset=+1]

include::modules/guides/proc-create-connector-instances.adoc[leveloffset=+1]

include::modules/guides/proc-commands-managing-connectors.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

