[id='assembly-using-kafkacat']
= Configuring and connecting Kcat with {product-long-kafka}
ifdef::context[:parent-context: {context}]
:context: using-kafkacat
:imagesdir: _images

// Purpose statement for the assembly
[role="_abstract"]
As a developer of applications and services, you can use https://github.com/edenhill/kcat[Kcat^] to test and debug your Kafka instances in {product-long-kafka}.
Kcat is a command-line utility for messaging in Apache Kafka 0.8 and later.
With Kcat, you can produce and consume messages directly from the command line. You can also list topic and partition information for your Kafka instances.

ifndef::community[]
NOTE: Kcat is an open source community tool. Kcat is not a part of {product-kafka} and is therefore not supported by Red Hat.
endif::[]

.Prerequisites
* You have a running Kafka instance in {product-kafka}.
* https://adoptopenjdk.net/[JDK^] 11 or later is installed. (The latest LTS version of OpenJDK is recommended.)
* You've installed the latest supported version of https://github.com/edenhill/kcat[Kcat^] for your operating system. To verify your Kcat version, enter the following command:
+
[source]
----
$ kcat -V
----
+
You see output like the following example:
+
[source]
----
kcat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kcat
Copyright (c) 2014-2021, Magnus Edenhill
Version 1.7.0 (librdkafka 1.3.0 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer)
----

// Condition out QS-only content so that it doesn't appear in docs.
// All QS anchor IDs must be in this alternate anchor ID format `[#anchor-id]` because the ascii splitter relies on the other format `[id="anchor-id"]` to generate module files.
ifdef::qs[]
[#description]
====
Learn how to use Kcat to interact with a Kafka instance in {product-long-kafka}.
====

[#introduction]
====
Welcome to the quick start for {product-long-kafka} with Kcat. In this quick start, you'll learn how to use https://github.com/edenhill/kcat[Kcat^] to produce and consume messages for your Kafka instances in {product-kafka}.
====
endif::[]

include::modules/guides/proc-configuring-kafkacat.adoc[leveloffset=+1]

include::modules/guides/proc-producing-messages-kafkacat.adoc[leveloffset=+1]

include::modules/guides/proc-consuming-messages-kafkacat.adoc[leveloffset=+1]

ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed the {product-kafka} Kcat quick start, and are now ready to produce and consume messages in the service.
====
endif::[]
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

