[id='assembly-getting-started-rhoas-cli-kafka']
= Getting started with the rhoas CLI for {product-long-kafka}
:context: getting-started-rhoas-kafka
:imagesdir: _images

[role="_abstract"]
With the {product-long-rhoas} `rhoas` command-line interface (CLI), you can manage OpenShift Streams for Apache Kafka from a terminal.

As a developer of applications and services,
you can use `rhoas` to create Kafka instances and connect your applications and services to these instances.
You can also create Kafka topics to store data for producers and consumers.

This guide describes how to get started quickly by doing the following:

* {base-url}{getting-started-rhoas-cli-url-kafka}#proc-creating-kafka-instance-cli_getting-started-rhoas-kafka[Create a Kafka instance]
* {base-url}{getting-started-rhoas-cli-url-kafka}#proc-creating-service-account-cli_getting-started-rhoas-kafka[Create a service account]
* {base-url}{getting-started-rhoas-cli-url-kafka}#proc-creating-kafka-topic-cli_getting-started-rhoas-kafka[Create a Kafka topic]
* {base-url}{getting-started-rhoas-cli-url-kafka}#proc-commands-managing-kafka_getting-started-rhoas-kafka[Use `rhoas` to manage your Kafka instances, service accounts, and Kafka topics]
* {base-url}{getting-started-rhoas-cli-url-kafka}#proc-generating-kafka-configs-cli_getting-started-rhoas-kafka[Generate configurations for a Kafka instance]

//Additional line break to resolve mod docs generation error

include::modules/guides/ref-kafka-cli-prereqs.adoc[leveloffset=+1]

include::modules/guides/proc-creating-kafka-instance-cli.adoc[leveloffset=+1]

include::modules/guides/proc-creating-service-account-cli.adoc[leveloffset=+1]

include::modules/guides/proc-creating-kafka-topic-cli.adoc[leveloffset=+1]

include::modules/guides/proc-generating-kafka-configs-cli.adoc[leveloffset=+1]

include::modules/guides/proc-commands-managing-kafka.adoc[leveloffset=+1]


