[id='assembly-getting-started-rhoas-cli-registry']
= Getting started with the rhoas CLI for {product-long-registry}
:context: getting-started-rhoas-service-registry
:imagesdir: _images

[role="_abstract"]
With the {product-long-rhoas} `rhoas` command-line interface (CLI), you can manage {product-long-registry} from a terminal.

As a developer of applications and services,
you can use `rhoas` to create {registry} instances and connect your applications and services to these instances.
You can also manage artifacts.
Artifacts are items stored in {registry}, such as schemas and API specifications.

You can get started with {product-long-registry} by doing the following tasks:

* {base-url}{getting-started-rhoas-cli-url-registry}#proc-creating-service-registry-instance-cli_getting-started-rhoas-service-registry[Create a {registry} instance]
* {base-url}{getting-started-rhoas-cli-url-registry}#proc-creating-service-registry-account_getting-started-rhoas-service-registry[Create a service account]
* {base-url}{getting-started-rhoas-cli-url-registry}#proc-uploading-service-registry-artifacts_getting-started-rhoas-service-registry[Upload {registry} artifacts]
* {base-url}{getting-started-rhoas-cli-url-registry}#proc-downloading-service-registry-artifacts_getting-started-rhoas-service-registry[Download {registry} artifacts]
* {base-url}{getting-started-rhoas-cli-url-registry}#proc-updating-service-registry-artifacts_getting-started-rhoas-service-registry[Update {registry} artifacts]
* {base-url}{getting-started-rhoas-cli-url-registry}#proc-configuring-service-registry-rules_getting-started-rhoas-service-registry[Configure {registry} rules]
* {base-url}{getting-started-rhoas-cli-url-registry}#proc-generating-registry-configs_getting-started-rhoas-service-registry[Generating {registry} configurations]
* {base-url}{getting-started-rhoas-cli-url-registry}#proc-commands-managing-registry_getting-started-rhoas-service-registry[Use `rhoas` to manage your {registry} instance, service accounts, and artifacts]

//Additional line break to resolve mod docs generation error

include::modules/guides/ref-service-registry-cli-prereqs.adoc[leveloffset=+1]

include::modules/guides/proc-creating-service-registry-instance-cli.adoc[leveloffset=+1]

include::modules/guides/proc-creating-service-registry-account.adoc[leveloffset=+1]

include::modules/guides/proc-uploading-service-registry-artifacts.adoc[leveloffset=+1]

include::modules/guides/proc-downloading-service-registry-artifacts.adoc[leveloffset=+1]

include::modules/guides/proc-updating-service-registry-artifacts.adoc[leveloffset=+1]

include::modules/guides/proc-configuring-service-registry-rules.adoc[leveloffset=+1]

include::modules/guides/proc-generating-registry-configs.adoc[leveloffset=+1]

include::modules/guides/proc-commands-managing-registry.adoc[leveloffset=+1]


