[id='assembly-generate-configurations-rhoas']
= Generating configurations for managed services using RHOAS CLI
:context: getting-started-generate-configurations
:imagesdir: _images

[role="_abstract"]
As a developer of applications and services, you can group service instances for specific use-cases, projects or environments and generate connection configuration details to connect applications to instances of managed services.

For example, suppose you have the following applications running locally in your machine:

* Application that publishes price updates for a variety of stocks
* Application that consumes the price updates and publishes them on a web page

In addition to the applications, you have a Kafka instance in Streams for Apache Kafka. Each time the first application produces a price update, you want to use the Kafka instance to forward the update as an event to the second, consuming application.

You need to connect your applications to the Kafka Instance in OpenSift Streams for Apache Kafka.

In this scenario, you can use the RHOAS CLI to generate the connection configuration details required to connect to the Kafka instance.

== RHOAS Context

Service context is an abstraction for which configurations are generated. A service context contains references to service instances used for specific projects or environments. With the `generate-config` command you can generate connection configuration details for your applications to connect to the service instances specified in the context. This gives you the flexibility to quickly and seamlessly switch between sets of service instances and generate connection configurations.

This guide describes how to generate connection configurations to connect Quarkus application to Kafka Instance in OpenShift Streams for Apache Kafka:

* {base-url}{rhoas-cli-getting-started-url-generate-config}#proc-creating-context-cli_getting-started-generate-config[Create a service context]
* {base-url}{rhoas-cli-getting-started-url-generate-config}#proc-creating-services-cli_getting-started-generate-config[Create services in service context]
* {base-url}{rhoas-cli-getting-started-url-generate-config}#proc-generating-config-cli_getting-started-generate-config[Generating application configurations]

include::modules/guides/ref-kafka-cli-prereqs.adoc[leveloffset=+1]

include::modules/guides/proc-creating-context-cli.adoc[leveloffset=+1]

include::modules/guides/proc-creating-services-cli.adoc[leveloffset=+1]

include::modules/guides/proc-generating-config-cli.adoc[leveloffset=+1]


