[id='assembly-browsing-messages']
= Browsing messages in the {product-long-kafka} web console
ifdef::context[:parent-context: {context}]
:context: browsing-messages
:imagesdir: _images

// Purpose statement for the assembly
[role="_abstract"]

As a developer or administrator, you can use the {product-long-kafka} web console to view and inspect messages for a Kafka topic. You might use this functionality, for example, to verify that a client is producing messages to the expected topic partition, that your topic is storing messages correctly, or that messages have the expected content.

When you select a topic in the console, you can use the *Messages* tab to view a list of messages for that topic. You can filter the list of messages in the following ways:

* Specify a partition and see messages sent to the partition.
* Specify a partition and offset and see messages sent to the partition from that offset.
* Specify a partition and a timestamp (that is, date and time) value. See messages sent to the partition from that date and time.
* Specify a partition and a Unix epoch timestamp value and see messages sent to the partition from that epoch timestamp value.

//Additional line break to resolve mod docs generation error.

include::modules/guides/proc-browsing-messages-for-a-topic.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

