[id='assembly-getting-started-api-designer']
= Getting started with {product-long-api-designer}
ifdef::context[:parent-context: {context}]
:context: getting-started-ad
:imagesdir: _images

// Purpose statement for the assembly
[role="_abstract"]
As an API owner or developer, you can use {product-long-api-designer} to design event schemas and API definitions that comply with vendor-neutral and portable open specifications.
{product-long-api-designer} is a managed cloud service that enables you to design schemas and API definitions without having to install, configure, run, and maintain your own {product-api-designer} infrastructure.

For more overview information, see the https://access.redhat.com/documentation/en-us/red_hat_openshift_api-designer/1[{product-long-api-designer} user documentation^].

ifndef::community[]
.Prerequisites
* You have a {org-name} account.
* If you plan to store your designs in {product-long-registry}, you have a running {registry} instance (see {base-url}{getting-started-url-registry}[Getting started with {product-long-registry}^]).
//For more information about signing up, see *<@SME: Where to link?>*.
endif::[]

// Condition out QS-only content so that it doesn't appear in docs.
// All QS anchor IDs must be in this alternate anchor ID format `[#anchor-id]` because the ascii splitter relies on the other format `[id="anchor-id"]` to generate module files.
ifdef::qs[]
[#description]
====
Learn how to create your first API or schema design in {product-long-api-designer}.
====

[#introduction]
====
Welcome to the quick start for {product-long-api-designer}.
In this quick start, you'll learn how to create an API definition or event schema from a simple or detailed template, import an existing design to edit it, test a design against rules configured in {product-long-registry}, and export a finished design to {product-registry}.
====
endif::[]

include::modules/guides/proc-creating-api-design.adoc[leveloffset=+1]

include::modules/guides/proc-creating-schema-design.adoc[leveloffset=+1]

include::modules/guides/proc-importing-schema-api-design.adoc[leveloffset=+1]

include::modules/guides/proc-testing-schema-api-design.adoc[leveloffset=+1]

include::modules/guides/proc-exporting-schema-api-design.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources
* https://access.redhat.com/documentation/en-us/red_hat_openshift_api_designer/1[{product-long-api-designer} user documentation^]
* https://access.redhat.com/documentation/en-us/red_hat_openshift_api_management/1[{product-long-api-management} user documentation^]
* https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1[{product-long-registry} user documentation^]
* https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/1[{product-long-kafka} user documentation^]

ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed the {product-long-api-designer} Getting Started quick start, and are now ready to use the service.
====
ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed the {product-long-api-designer} Getting Started quick start, and are now ready to use the service.
====
endif::[]
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

