[id='assembly-using-servicediscovery']
=  Connecting {product-long} Service to your OpenShift cluster
ifdef::context[:parent-context: {context}]
:context: using-servicediscovery
:imagesdir: _images

[IMPORTANT]
====
{product-long} is currently available for Development Preview. Development Preview releases provide early access to a limited set of features that might not be fully tested and that might change in the final GA version. Users should not use Development Preview software in production or for business-critical workloads. Limited documentation is available for Development Preview releases and is typically focused on fundamental user goals.
====

// Purpose statement for the assembly
[role="_abstract"]
As a developer of applications and services, you can connect Quarkus applications to Kafka instances in {product-long}. https://quarkus.io/[Quarkus^] is a Kubernetes-native Java framework made for Java virtual machines (JVMs) and native compilation, and optimized for serverless, cloud, and Kubernetes environments. Quarkus is designed to work with popular Java standards, frameworks, and libraries like Eclipse MicroProfile and Spring, as well as Apache Kafka, RESTEasy (JAX-RS), Hibernate ORM (JPA), Infinispan, Camel, and many more.

OpenShift is an Enteprise Kuberentes Platform. When deploying Quarkus and any other type of application, developers can use
the https://developers.redhat.com/blog/2019/12/19/introducing-the-service-binding-operator/[Service Binding Operator] to
enable your applications to discover service configuration automatically in your OpenShift or Kubernetes instance.

You can review all possible commands in https://github.com/redhat-developer/app-services-cli/blob/main/docs/commands/rhoas_cluster.adoc[cli documentation].


In this Quick Start, you'll connect your OpenShift Streams for Apache Kafka cloud service to your OpenShift cluster using the Red Hat OpenShift Application Services. (RHOAS) Operator and CLI. For more information on Red Hat OpenShift Application Services, please visit link:https://cloud.redhat.com/application-services[cloud.redhat.com.]

.Prerequisites
ifndef::community[]
* You have a Red Hat account.
endif::[]
* You have a running Kafka instance in {product}.

// Condition out QS-only content so that it doesn't appear in docs.
// All QS anchor IDs must be in this alternate anchor ID format `[#anchor-id]` because the ascii splitter relies on the other format `[id="anchor-id"]` to generate module files.
ifdef::qs[]
[#description]
Using the {product-long} services in your OpenShift cluster{product-long}.

[#introduction]
Welcome to the {product-long} Service Discovery quick start. In this quick start, you'll learn how to connect your {product} services with https://quarkus.io/[Quarkus^]. Tutorial will connect Kafka with your Application to produce and consume messages from your Kafka instances in {product}.
endif::[]
ifndef::community[]
endif::[]
ifdef::qs[]
endif::[]
include::modules/guides/proc-installing-cli.adoc[leveloffset=+1]

include::modules/guides/proc-installing-operator.adoc[leveloffset=+1]

include::modules/guides/proc-inspecting-operator.adoc[leveloffset=+1]

include::modules/guides/proc-connecting-kafka.adoc[leveloffset=+1]

include::modules/guides/proc-create-prices-topic-for-operator.adoc[leveloffset=+1]

include::modules/guides/proc-running-quarkus-example-application-for-operator.adoc[leveloffset=+1]

include::modules/guides/proc-binding-kafka.adoc[leveloffset=+1]


