[id='assembly-kafka-bin-scripts']
= Configuring and connecting Kafka scripts with {product-long-kafka}
ifdef::context[:parent-context: {context}]
:context: using-kafka-bin-scripts
:imagesdir: _images

// Purpose statement for the assembly
[role="_abstract"]
As a developer of applications and services, you can use Kafka scripts to produce and consume messages for Kafka instances in {product-long-kafka}. This is a useful way to test and debug your Kafka instances.
The Kafka scripts are a set of shell scripts that are included with the https://kafka.apache.org/downloads[Apache Kafka distribution^].

ifndef::community[]
NOTE: The Kafka scripts are part of the open source community version of Apache Kafka. The scripts are not a part of {product-kafka} and are therefore not supported by Red Hat.
endif::[]

When you download and extract the Apache Kafka distribution, the `bin/` directory of the distribution (or the `bin\windows\` directory if you're using Windows) contains a set of shell scripts that enable you to interact with your Kafka instance.
With the scripts, you can produce and consume messages using your Kafka instances. You can also perform various other operations against the Kafka APIs to administer topics, consumer groups, and other resources.

NOTE: The command examples in this quick start show how to use the Kafka scripts on Linux and macOS. If you're using Windows, use the Windows versions of the scripts. For example, instead of the `__<Kafka-distribution-dir>__/bin/kafka-console-producer.sh` script, use the `__<Kafka-distribution-dir>__\bin\windows\kafka-console-producer.bat` script.

.Prerequisites
* You have a running Kafka instance in {product-kafka} (see {base-url}{getting-started-url-kafka}[Getting started with {product-long-kafka}^]).
* You have a command-line terminal application.
* https://adoptopenjdk.net/[JDK^] 11 or later is installed. (The latest LTS version of OpenJDK is recommended.)
* You've downloaded the latest supported binary version of the https://kafka.apache.org/downloads[Apache Kafka distribution^]. You can check your Kafka version using the following command:
+
[source]
----
$ ./kafka-console-producer.sh --version
----

ifdef::qs[]
[#description]
====
Learn how to use Kafka scripts to interact with a Kafka instance in {product-long-kafka}.
====

[#introduction]
====
Welcome to the quick start for {product-long-kafka} with Kafka scripts. In this quick start, you'll learn how to use the Kafka scripts to produce and consume messages for your Kafka instances in {product-kafka}.
====
endif::[]

include::modules/guides/proc-configuring-kafka-bin-scripts.adoc[leveloffset=+1]

include::modules/guides/proc-producing-messages-kafka-bin-scripts.adoc[leveloffset=+1]

include::modules/guides/proc-consuming-messages-kafka-bin-scripts.adoc[leveloffset=+1]

ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed the {product-kafka} Kafka scripts quick start, and are now ready to produce and consume messages in the service.
====
endif::[]
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

