[id='assembly-getting-started-rhoas-cli']
= Getting started with the rhoas CLI
:context: getting-started-rhoas
:imagesdir: _images

[IMPORTANT]
====
The `rhoas` command-line interface (CLI) is currently available for Development Preview. Development Preview releases provide early access to a limited set of features that might not be fully tested and that might change in the final GA version. Users should not use Development Preview software in production or for business-critical workloads. Limited documentation is available for Development Preview releases and is typically focused on fundamental user goals.
====

[role="_abstract"]
With the `rhoas` command-line interface (CLI), you can manage your application services from a terminal.

This guide describes how to get started quickly by doing the following:

--
* Install `rhoas` on your Operating System.

* Configure `rhoas` to enable command completion.

* Start using `rhoas` by creating a simple Kafka instance, connecting to it, and creating a Kafka topic to produce and consume messages.
--
include::modules/guides/proc-installing-rhoas.adoc[leveloffset=+1]

include::modules/guides/proc-configuring-rhoas.adoc[leveloffset=+1]

include::modules/guides/proc-logging-in-to-rhoas.adoc[leveloffset=+1]

include::modules/guides/proc-using-rhoas.adoc[leveloffset=+1]

include::modules/guides/proc-logging-out-rhoas.adoc[leveloffset=+1]


