[id='assembly-using-quarkus']
= Using Quarkus applications with Kafka instances in {product-long-kafka}
ifdef::context[:parent-context: {context}]
:context: using-quarkus
:imagesdir: _images

// Purpose statement for the assembly
[role="_abstract"]
As a developer of applications and services, you can connect Quarkus applications to Kafka instances in {product-long-kafka}. https://quarkus.io/[Quarkus^] is a Kubernetes-native Java framework made for Java virtual machines (JVMs) and native compilation, and optimized for serverless, cloud, and Kubernetes environments. Quarkus is designed to work with popular Java standards, frameworks, and libraries like Eclipse MicroProfile and Spring, as well as Apache Kafka, RESTEasy (JAX-RS), Hibernate ORM (JPA), Infinispan, Camel, and many more.

In this quick start, you'll use the {product-kafka} web console to collect connection information for a Kafka instance. Then you'll manually configure a connection from an example Quarkus application to the Kafka instance and start producing and consuming messages.

NOTE: When you've completed this quick start and understand the required connection configuration for a Kafka instance, you can use the {product-long-rhoas} command-line interface (CLI) to generate this type of configuration in a more automated way. To learn more, see {base-url}{service-contexts-url-cli}[Connecting client applications to {product-long-rhoas} using the rhoas CLI^].

.Prerequisites
ifndef::community[]
* You have a {org-name} account.
endif::[]
* You have a running Kafka instance in {product-kafka} (see {base-url}{getting-started-url-kafka}[Getting started with {product-long-kafka}^]).
* You have a command-line terminal application.
* https://github.com/git-guides/[Git^] is installed.
* You have an IDE such as https://www.jetbrains.com/idea/download/[IntelliJ IDEA^], https://www.eclipse.org/downloads/[Eclipse^], or https://code.visualstudio.com/Download[Visual Studio Code^].
* https://adoptopenjdk.net/[JDK^] 11 or later is installed. (The latest LTS version of OpenJDK is recommended.)

* https://maven.apache.org/[Apache Maven^] 3.6.2 (or a later Maven 3 release) is installed.

// Condition out QS-only content so that it doesn't appear in docs.
// All QS anchor IDs must be in this alternate anchor ID format `[#anchor-id]` because the ascii splitter relies on the other format `[id="anchor-id"]` to generate module files.
ifdef::qs[]
[#description]
====
Learn how to manually connect a Quarkus application to a Kafka instance in {product-long-kafka} and then produce and consume messages.
====

[#introduction]
====
Welcome to the quick start for {product-long-kafka} with Quarkus. In this quick start, you'll use the web console to collect connection information for a Kafka instance in {product-kafka}. Then you'll manually configure a connection from an example https://quarkus.io/[Quarkus^] application to the Kafka instance and start producing and consuming messages.
====
endif::[]

include::modules/guides/proc-importing-quarkus-sample-code.adoc[leveloffset=+1]

include::modules/guides/proc-configuring-quarkus.adoc[leveloffset=+1]

include::modules/guides/proc-create-prices-topic.adoc[leveloffset=+1]

include::modules/guides/proc-running-quarkus-example-application.adoc[leveloffset=+1]

ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed the {product-kafka} Quarkus quick start, and are now ready to connect your own Quarkus applications to {product-kafka}.
====
endif::[]
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

