[id='assembly-getting-started-rhoas-cli-kafka']
= Getting started with the rhoas CLI for OpenShift Streams for Apache Kafka
:context: getting-started-rhoas-kafka
:imagesdir: _images

[IMPORTANT]
====
The `rhoas` command-line interface (CLI) is currently available for Development Preview. Development Preview releases provide early access to a limited set of features that might not be fully tested and that might change in the final GA version. Users should not use Development Preview software in production or for business-critical workloads. Limited documentation is available for Development Preview releases and is typically focused on fundamental user goals.
====

[role="_abstract"]
With the `rhoas` command-line interface (CLI), you can manage OpenShift Streams for Apache Kafka from a terminal.

As a developer of applications and services,
you can use `rhoas` to create Kafka instances and connect your applications and services to these instances.
You can also create Kafka topics to store data for producers and consumers.

This guide describes how to get started quickly by doing the following:

* link:{base-url}{rhoas-cli-kafka-url}#proc-creating-kafka-instance-cli_getting-started-rhoas-kafka[Create a Kafka instance]
* link:{base-url}{rhoas-cli-kafka-url}#proc-creating-service-account-cli_getting-started-rhoas-kafka[Create a service account]
* link:{base-url}{rhoas-cli-kafka-url}#proc-creating-kafka-topic-cli_getting-started-rhoas-kafka[Create a Kafka topic]
* link:{base-url}{rhoas-cli-kafka-url}#proc-commands-managing-kafka_getting-started-rhoas-kafka[Use `rhoas` to manage your Kafka instances, service accounts, and Kafka topics]

//Additional line break to resolve mod docs generation error
include::modules/guides/ref-kafka-cli-prereqs.adoc[leveloffset=+1]

include::modules/guides/proc-creating-kafka-instance-cli.adoc[leveloffset=+1]

include::modules/guides/proc-creating-service-account-cli.adoc[leveloffset=+1]

include::modules/guides/proc-creating-kafka-topic-cli.adoc[leveloffset=+1]

include::modules/guides/proc-commands-managing-kafka.adoc[leveloffset=+1]


