[id='assembly-kafka-bin-scripts']
= Using Kafka bin scripts with {product-long}
ifdef::context[:parent-context: {context}]
:context: using-kafka-bin-scripts
:imagesdir: _images

[IMPORTANT]
====
{product-long} is currently available for Development Preview. Development Preview releases provide early access to a limited set of features that might not be fully tested and that might change in the final GA version. Users should not use Development Preview software in production or for business-critical workloads. Limited documentation is available for Development Preview releases and is typically focused on fundamental user goals.
====

// Purpose statement for the assembly
[role="_abstract"]
As a developer of applications and services, you can use the Kafka bin scripts to manage your Kafka instances in {product-long}.
The Kafka bin scripts are a set of shell scripts that are included with the Apache Kafka distribution.
With these bin scripts, you can produce and consume messages for your Kafka instances.

NOTE: The command examples in this quick start demonstrate how to use the Kafka bin scripts on Linux and macOS. If you're using Windows, use the Windows versions of the bin scripts. For example, instead of the `__<Kafka-distribution-dir>__/bin/kafka-console-producer.sh` script, use the `__<Kafka-distribution-dir>__\bin\windows\kafka-console-producer.bat` script.

.Prerequisites
ifndef::community[]
* You have a Red Hat account.
endif::[]
* You have a running Kafka instance in {product}.
* https://adoptopenjdk.net/[JDK^] 11 or later is installed.
* For Windows, the latest version of https://www.oracle.com/java/technologies/javase-downloads.html[Oracle JDK^] is installed.

ifdef::qs[]
[#description]
Learn how to use Kafka bin scripts to interact with a Kafka instance in {product-long}.

[#introduction]
Welcome to the quick start for {product-long} with Kafka bin scripts. In this quick start, you'll learn how to use the Kafka bin scripts to produce and consume messages for your Kafka instances in {product}.
endif::[]
ifndef::community[]
endif::[]
ifdef::qs[]
endif::[]
include::modules/guides/proc-downloading-kafka-bin-scripts.adoc[leveloffset=+1]

include::modules/guides/proc-configuring-kafka-bin-scripts.adoc[leveloffset=+1]

include::modules/guides/proc-producing-messages-kafka-bin-scripts.adoc[leveloffset=+1]

include::modules/guides/proc-consuming-messages-kafka-bin-scripts.adoc[leveloffset=+1]


