[id='assembly-getting-started-service-registry']
= Getting started with {product-long-registry}
ifdef::context[:parent-context: {context}]
:context: getting-started-sr
:imagesdir: _images

// Purpose statement for the assembly
[role="_abstract"]
As a developer of applications and services, you can use {product-long-registry} to create and set up {registry} instances and connect your applications and services to these instances. {product-long-registry} is a managed cloud service that enables you to manage schema and API definitions in your applications without having to install, configure, run, and maintain your own {registry} clusters.

For more overview information, see the https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1[{product-long-registry} user documentation^].

ifndef::community[]
.Prerequisites
* You have a {org-name} account.
* You have a subscription to {product-long-kafka} or {product-long-api-management}.
//For more information about signing up, see *<@SME: Where to link?>*.
endif::[]

// Condition out QS-only content so that it doesn't appear in docs.
// All QS anchor IDs must be in this alternate anchor ID format `[#anchor-id]` because the ascii splitter relies on the other format `[id="anchor-id"]` to generate module files.
ifdef::qs[]
[#description]
====
Use the web console to create a {registry} instance, service account, and schema or API artifact.
====

[#introduction]
====
Welcome to the quick start for {product-long-registry}. In this quick start, you'll learn how to create and view a {registry} instance, create a schema in this instance, and create a service account to connect an application or service to this instance.
====
endif::[]

include::modules/guides/proc-creating-service-registry-instance.adoc[leveloffset=+1]

include::modules/guides/proc-uploading-registry-schema.adoc[leveloffset=+1]

include::modules/guides/proc-connecting-registry-clients.adoc[leveloffset=+1]

include::modules/guides/proc-setting-service-account-user-roles.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources
* {base-url}{access-mgmt-url-registry}[Managing account access in {product-long-registry}^]
* https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1[{product-long-registry} user documentation^]
* https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/1[{product-long-kafka} user documentation^]

ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed the {registry} Getting Started quick start, and are now ready to use the service.
====
ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed the {registry} Getting Started quick start, and are now ready to use the service.
====
endif::[]
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

