[id='assembly-getting-started']
= Getting started with {product-long-kafka}
ifdef::context[:parent-context: {context}]
:context: getting-started
:imagesdir: _images

// Purpose statement for the assembly
[role="_abstract"]
As a developer of applications and services, you can use {product-long-kafka} to create and set up Kafka instances and connect your applications and services to these instances. {product-kafka} is a managed cloud service that enables you to add Kafka data-streaming functionality in your applications without having to install, configure, run, and maintain your own Kafka clusters.

//For more overview information about {product-kafka}, see [variablized link to overview here https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/].


ifndef::community[]
.Prerequisites
* You have a {org-name} account.
//* You have a subscription to {product-long-kafka}. For more information about signing up, see *<@SME: Where to link?>*.
endif::[]

// Condition out QS-only content so that it doesn't appear in docs.
// All QS anchor IDs must be in this alternate anchor ID format `[#anchor-id]` because the ascii splitter relies on the other format `[id="anchor-id"]` to generate module files.
ifdef::qs[]
[#description]
====
Use the web console to create a Kafka instance, service account, and Kafka topic.
====

[#introduction]
====
Welcome to the quick start for {product-long-kafka}. In this quick start, you'll learn how to create and inspect a Kafka instance, create a service account to connect an application or service to the instance, and create a topic in the instance.
====
endif::[]

include::modules/guides/proc-creating-kafka-instance.adoc[leveloffset=+1]

include::modules/guides/proc-creating-service-account.adoc[leveloffset=+1]

include::modules/guides/proc-setting-service-account-permissions.adoc[leveloffset=+1]

include::modules/guides/proc-creating-kafka-topic.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources
* https://console.redhat.com/application-services/streams/overview[Purchase a subscription to {product-long-kafka}]
* https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/1/guide/7d28aec8-e146-44db-a4a5-fafc1f426ca5[Configuring topics in {product-long-kafka}^]
* {base-url}{getting-started-rhoas-cli-url-kafka}[Getting started with the rhoas CLI for {product-long-kafka}^]
* {base-url-cli}{command-ref-url-cli}[CLI command reference (rhoas)^]
* {base-url}{kafkacat-url-kafka}[Configuring and connecting Kcat with {product-long-kafka}^]
* {base-url}{kafka-bin-scripts-url-kafka}[Configuring and connecting Kafka scripts with {product-long-kafka}^]
* {base-url}{quarkus-url-kafka}[Using Quarkus applications with Kafka instances in {product-long-kafka}^]

ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed the {product-kafka} Getting Started quick start, and are now ready to use the service.

You can use either Kcat or the Kafka scripts to check that you can connect with your Kafka instance.
====
ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed the {product-kafka} Getting Started quick start, and are now ready to use the service.

You can use either Kcat or the Kafka scripts to check that you can connect with your Kafka instance.
====
endif::[]
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]

