//OpenShift Streams for Apache Kafka
:base-url: https://github.com/redhat-developer/app-services-guides/tree/main/docs/
:product-long-rhoas: OpenShift Application Services
:rhoas-cli-base-url: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:rhoas-cli-ref-url: commands
:rhoas-cli-getting-started-url-context: cli-context/

[id="chap-getting-started-rhoas-cli-context"]
= Getting started with the rhoas CLI for context management
:context: getting-started-rhoas-context

[role="_abstract"]
With the {product-long-rhoas} `rhoas` command-line interface (CLI), you can manage service contexts.

As a developer of applications and services,
you can use `rhoas` to manage service contexts that can be used to generate application configurations.
Contexts allow you to work with multiple projects using different services easily.

[role="_abstract"]
A service context is a group of application service instances and their service identifiers.
By using service contexts, you can group together application service instances that you want to use together.

This guide describes how to get started quickly by doing the following:

* {base-url}{rhoas-cli-getting-started-url-context}#proc-creating-context-cli_getting-started-rhoas-context[Create a service context]
* {base-url}{rhoas-cli-getting-started-url-context}#proc-setting-services-cli_getting-started-rhoas-context[Set services in service context]
* {base-url}{rhoas-cli-getting-started-url-context}#proc-generating-config-cli_getting-started-rhoas-context[Generating application configurations for Quarkus]
* {base-url}{rhoas-cli-getting-started-url-context}#proc-switching-context-cli_getting-started-rhoas-context[Switch between contexts]
* {base-url}{rhoas-cli-getting-started-url-context}#proc-unsetting-services-cli_getting-started-rhoas-context[Unset services in service context]
* {base-url}{rhoas-cli-getting-started-url-context}#proc-deleting-context-cli_getting-started-rhoas-context[Delete a service context]
* {base-url}{rhoas-cli-getting-started-url-context}#proc-sharing-context-cli_getting-started-rhoas-context[Sharing contexts]


[id="ref-kafka-cli-prereqs_{context}"]
== Prerequisites

[role="_abstract"]
* You've installed the `rhoas` CLI. For more information, see {base-url}{rhoas-cli-installation-url}[_Installing the rhoas CLI_^].

[id="proc-creating-context-cli_{context}"]
== Creating a service context

.Procedure

Enter the following command to create a context named `my-context`

.Creating a context
[source,shell]
----
$ rhoas context create --name my-context
----

[NOTE]
====
By default, the created context is set as the current context.
All the service based commands are executed against the service instances set in the current context.
====

[id="proc-setting-services-cli_{context}"]
== Setting services in a context

[role="_abstract"]
Context contains identifiers to service instances.
All the service based commands are executed against the service instances set in the current context.

.Procedure

. Setting Kafka Instance in the current context
+
--
.Set Kafka instance in the current context
[source,shell]
----
$ rhoas context set-kafka
----
--

. Setting Service Registry Instance in the current context
+
--
.Set Service Registry instance in the current context
[source,shell]
----
$ rhoas context set-service-registry
----

[NOTE]
====
Creating a new service instance automatically sets it in the current context.
====
--

. Check status of the current context
+
--
After setting service(s) in the current context, their staus can be checked using the `rhoas context status` command
.View status of the current context
[source,shell]
----
$ rhoas context status
----
--

[id="proc-generating-config-cli_{context}"]
== Generating application configurations for contexts

`rhoas generate-config` command generates application configurations that can be used to connect to the services set in context.

.Generating configurations for context named as my "my-context"
source,shell
----
$ rhoas generate-config --name my-context  -type json
----

=== Generating configurations for quarkus applications

[id="proc-importing-quarkus-sample-code_{context}"]
==== Importing the Quarkus sample code

[role="_abstract"]
For this quick start, you'll use the Quarkus sample code from the {product-kafka} {samples-git-repo}[Guides and Samples^] repository in GitHub.
After you understand the concepts and tasks in this quick start, you can use your own Quarkus applications with {product-kafka} in the same way.

.Procedure
. On the command line, clone the {product-kafka} {samples-git-repo}[Guides and Samples^] repository from GitHub.
+
.Cloning the guides and samples repository
[source,subs="+attributes"]
----
git clone {samples-git-repo} app-services-guides
----
. In your IDE, open the `code-examples/quarkus-kafka-quickstart` directory from the repository that you cloned.
. Generate the application configurations for the quarkus application.
+
--
[source,shell]
----
$ rhoas generate-config --type env --output-file .env 
----
--
. Create the "prices" Kafka topic.
+
--
[source,shell]
----
$ rhoas kafka topic create --name prices
----
--
. Create ACLs for the service account created using the `rhoas generate-config` command.
+
--
[source,shell]
----
$ rhoas kafka acl grant-access --producer --consumer --service-account <client_id> --topic prices --group all
----
--
. Run the Quarkus application in dev mode.
+
--
[source,shell]
----
./mvnw quarkus:dev
----
--

[role="_abstract"]
The Quarkus application starts produces and consumes messages to and from the "prices" Kafka topic.
After the application is running, in a web browser, go to http://localhost:8080/prices.html[^] and verify that the `Last price` is updated.

If the Quarkus application fails to run, review the error log in the terminal and address any problems. Also review the steps to ensure that the Quarkus application and Kafka topic are configured correctly.

[id="proc-switching-context-cli_{context}"]
== Switching between contexts

User can switch between different contexts to work with different set of service instances.

.Procedure

. List the service contexts
+
--
[source,shell]
----
$ rhoas context list
----
--

. Set the current context
+
--
----
$ rhoas context use --name my-context
----
--

[id="proc-unsetting-services-cli_{context}"]
== Unsetting services from the context

.Unsetting services from current context
----
$ rhoas context unset --services kafka,service-registry
----

[id="proc-deleting-context-cli_{context}"]
== Deleting a service context

.Deleting the current context
----
$ rhoas context delete
----

[id="proc-sharing-context-cli_{context}"]
== Sharing service contexts

[role="_abstract"]
Contexts can be shared with other users.

.Procedure

. Use status command to view location of context file
+
--
----
$ rhoas context status
----
--

. Use copy command to copy the context file. Example(linux):
+
--
----
cp /home/username/.config/rhoas/contexts.json shared.json
----
--

[role="_additional-resources"]
.Additional resources
* {rhoas-cli-base-url}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]