// Metadata created by nebel
// ParentAssemblies: assemblies/getting-started/as_managing-registry-artifacts.adoc

[id="exporting-importing-using-rest-api"]
= Exporting and importing registry content using Registry REST API commands

[role="_abstract"]
This section shows a simple curl-based example of using the registry v2 core REST API to export and import existing registry data in `.zip` format from one {registry} instance to another. For example, this is useful when migrating or upgrading from one {registry} v2.x instance to another. 

.Prerequisites

ifdef::apicurio-registry,rh-service-registry[]
* {registry} must be installed and running in your environment
endif::[]
ifdef::rh-openshift-sr[]
* You must have access to the {registry} web console
endif::[]

.Procedure

ifdef::rh-openshift-sr[]
. Connect to the {registry} web console on:
+
`*{console-url}*`

. For the relevant {registry} instance that you want to connect to, select the options icon (three vertical dots) and click *View connection information*.
. In the *Connection* page, copy the URL for the core registry API to a secure location. This is the registry API endpoint that you need for connecting to this {registry} instance. 
endif::[]

. Export the registry data from your existing source {registry} instance:
+
[source,bash]
----
$ curl http://MY-REGISTRY-URL/apis/registry/v2/admin/export \ 
  --output my-registry-data.zip
----
+
`MY-REGISTRY-URL` is the 
ifdef::apicurio-registry[]
host name on which the source {registry} is deployed. For example: `\http://my-source-registry:8080`.
endif::[]
ifdef::rh-service-registry[]
host name on which the source {registry} is deployed. For example: `my-cluster-source-registry-myproject.example.com`. 
endif::[]
ifdef::rh-openshift-sr[]
URL on which the source {registry} is deployed. For example: `\https://service-registry-source.apps.app-sre-0.k3s7.p1.openshiftapps.com/t/f301375a-18a7-426c-bbd8-8e626a0a1d0e`. 
endif::[]

. Import the registry data into your target {registry} instance:
+
[source,bash]
----
$ curl -X POST "http://MY-REGISTRY-URL/apis/registry/v2/admin/import" \ 
  -H "Content-Type: application/zip" --data-binary @my-registry-data.zip
----
+
`MY-REGISTRY-URL` is the 
ifdef::apicurio-registry[]
host name on which the target {registry} is deployed. For example: `\http://my-target-registry:8080`.
endif::[]
ifdef::rh-service-registry[]
host name on which the target {registry} is deployed. For example: `my-cluster-target-registry-myproject.example.com`. 
endif::[]
ifdef::rh-openshift-sr[]
URL on which the target {registry} is deployed. For example: `\https://service-registry-target.apps.app-sre-0.k3s7.p1.openshiftapps.com/t/f301375a-18a7-426c-bbd8-8e626a0a1d0e`. 
endif::[]


[role="_additional-resources"]
.Additional resources
* For more details, see the `admin` endpoint in the link:{attachmentsdir}/registry-rest-api.htm[Apicurio Registry REST API documentation]
ifdef::apicurio-registry,rh-service-registry[]
* For details on export tools for migrating from {registry} version 1.x to 2.x, see link:https://github.com/Apicurio/apicurio-registry/tree/master/utils/exportV1[Apicurio Registry export utility for 1.x versions]
endif::[]
