////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////

//All OpenShift Application Services
:org-name: Application Services
:product-long-rhoas: OpenShift Application Services
:product-rhoas: OpenShift Application Services
:community:
:imagesdir: ./images
:property-file-name: app-services.properties
:samples-git-repo: https://github.com/redhat-developer/app-services-guides
:base-url: https://github.com/redhat-developer/app-services-guides/tree/main/docs/
:sso-token-url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
:cloud-console-url: https://console.redhat.com/
:service-accounts-url: https://console.redhat.com/application-services/service-accounts
:rh-sso-url: https://sso.redhat.com
:rh-customer-portal: Red Hat Customer Portal

//OpenShift
:openshift: OpenShift
:osd-name: OpenShift Dedicated
:osd-name-short: OpenShift Dedicated
:rosa-name: OpenShift Service on AWS
:rosa-name-short: OpenShift Service on AWS

//OpenShift Application Services CLI
:base-url-cli: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:command-ref-url-cli: commands
:installation-guide-url-cli: rhoas/rhoas-cli-installation/README.adoc
:service-contexts-url-cli: rhoas/rhoas-service-contexts/README.adoc

//OpenShift Streams for Apache Kafka
:product-long-kafka: OpenShift Streams for Apache Kafka
:product-kafka: Streams for Apache Kafka
:product-version-kafka: 1
:service-url-kafka: https://console.redhat.com/application-services/streams/
:getting-started-url-kafka: kafka/getting-started-kafka/README.adoc
:kafka-bin-scripts-url-kafka: kafka/kafka-bin-scripts-kafka/README.adoc
:kafkacat-url-kafka: kafka/kcat-kafka/README.adoc
:quarkus-url-kafka: kafka/quarkus-kafka/README.adoc
:nodejs-url-kafka: kafka/nodejs-kafka/README.adoc
:getting-started-rhoas-cli-url-kafka: kafka/rhoas-cli-getting-started-kafka/README.adoc
:topic-config-url-kafka: kafka/topic-configuration-kafka/README.adoc
:consumer-config-url-kafka: kafka/consumer-configuration-kafka/README.adoc
:access-mgmt-url-kafka: kafka/access-mgmt-kafka/README.adoc
:metrics-monitoring-url-kafka: kafka/metrics-monitoring-kafka/README.adoc
:service-binding-url-kafka: kafka/service-binding-kafka/README.adoc
:message-browsing-url-kafka: kafka/message-browsing-kafka/README.adoc

//OpenShift Service Registry
:product-long-registry: OpenShift Service Registry
:product-registry: Service Registry
:registry: Service Registry
:product-version-registry: 1
:service-url-registry: https://console.redhat.com/application-services/service-registry/
:getting-started-url-registry: registry/getting-started-registry/README.adoc
:quarkus-url-registry: registry/quarkus-registry/README.adoc
:getting-started-rhoas-cli-url-registry: registry/rhoas-cli-getting-started-registry/README.adoc
:access-mgmt-url-registry: registry/access-mgmt-registry/README.adoc
:content-rules-registry: https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1/guide/9b0fdf14-f0d6-4d7f-8637-3ac9e2069817[Supported Service Registry content and rules]
:service-binding-url-registry: registry/service-binding-registry/README.adoc

//OpenShift Connectors
:connectors: Connectors
:product-long-connectors: OpenShift Connectors
:product-connectors: Connectors
:product-version-connectors: 1
:service-url-connectors: https://console.redhat.com/application-services/connectors
:getting-started-url-connectors: connectors/getting-started-connectors/README.adoc
:getting-started-rhoas-cli-url-connectors: connectors/rhoas-cli-getting-started-connectors/README.adoc
:addon-url-connectors: https://access.redhat.com/documentation/en-us/openshift_connectors/1/guide/15a79de0-8827-4bf1-b445-8e3b3eef7b01


//OpenShift API Designer
:product-long-api-designer: OpenShift API Designer
:product-api-designer: API Designer
:product-version-api-designer: 1
:service-url-api-designer: https://console.redhat.com/application-services/api-designer/
:getting-started-url-api-designer: api-designer/getting-started-api-designer/README.adoc

//OpenShift API Management
:product-long-api-management: OpenShift API Management
:product-api-management: API Management
:product-version-api-management: 1
:service-url-api-management: https://console.redhat.com/application-services/api-management/

////
END GENERATED ATTRIBUTES
////

[id="chap-getting-started-rhoas-cli-kafka"]
= Creating Kafka resources by using the {product-rhoas} CLI
:context: getting-started-rhoas-kafka

[role="_abstract"]
With the {product-long-rhoas} `rhoas` command-line interface (CLI), you can manage OpenShift Streams for Apache Kafka from a terminal.

As a developer of applications and services,
you can use `rhoas` to create Kafka instances and connect your applications and services to these instances.
You can also create Kafka topics to store data for producers and consumers.

This guide describes how to get started quickly by doing the following:

* {base-url}{getting-started-rhoas-cli-url-kafka}#proc-creating-kafka-instance-cli_getting-started-rhoas-kafka[Create a Kafka instance]
* {base-url}{getting-started-rhoas-cli-url-kafka}#proc-creating-service-account-cli_getting-started-rhoas-kafka[Create a service account]
* {base-url}{getting-started-rhoas-cli-url-kafka}#proc-creating-kafka-topic-cli_getting-started-rhoas-kafka[Create a Kafka topic]
* {base-url}{getting-started-rhoas-cli-url-kafka}#proc-commands-managing-kafka_getting-started-rhoas-kafka[Use `rhoas` to manage your Kafka instances, service accounts, and Kafka topics]
* {base-url}{getting-started-rhoas-cli-url-kafka}#proc-generating-kafka-configs-cli_getting-started-rhoas-kafka[Generate configurations for a Kafka instance]

//Additional line break to resolve mod docs generation error

[id="ref-kafka-cli-prereqs_{context}"]
== Prerequisites

[role="_abstract"]
* You have a command-line terminal application.
* You have a registered OpenShift cluster.
* You've installed the `rhoas` CLI. For more information, see {base-url}{installation-guide-url-cli}[_Installing the rhoas CLI_^].

//Additional line break to resolve mod docs generation error

[id="proc-creating-kafka-instance-cli_{context}"]
== Creating a Kafka instance

[role="_abstract"]
A Kafka instance includes a Kafka cluster, bootstrap server, and other required configurations for connecting to Kafka producer and consumer services.

.Prerequisites

* You are logged in to `rhoas`.

.Procedure

. Enter the following command to create a Kafka instance with default values.
+
--
.Creating a Kafka instance
[source,shell]
----
$ rhoas kafka create
----
--

. Enter Name: `my-kafka`.
. Use the arrows on your keyboard to select your OpenShift cluster for your Kafka instance.
. Select an instance size of 1 (x1) or 2 (x2) streaming units. 
+
--
A streaming unit determines the default maximum capacity of a Kafka instance. An instance with a larger size can handle higher loads and process more events, has more storage, and can handle more clients and connections.

The CLI displays information about the created instance including billing model, cloud provider, cluster id of the cluster the instance is provisioned on, and instance type.

CLI uses service contexts to group service instances against which commands are executed.
The created Kafka instance is set automatically in the current context.

[NOTE]
====
Alternatively, to provision a Kafka instance by specifying the kafka name and cluster-id, enter the following command: `rhoas kafka create --name my-kafka --cluster-id <CLUSTER_ID>`. This takes on the default value size 1 streaming unit.
====
--
. Verify that the Kafka instance has a `ready` status.
+
--
[source,shell]
----
$ rhoas kafka list
----

.Reviewing details of a Kafka instance
[source,shell]
----
$ rhoas context status kafka
----
[NOTE]
====
If you have multiple Kafka instances,
you can make the current context switch to a different instance by using the `rhoas context set-kafka` command.
====
--

[id="proc-creating-service-account-cli_{context}"]
== Creating a service account

[role="_abstract"]
To connect your applications or services to a Kafka instance, you must first create a service account with credentials.
The credentials are exported to a file on your computer,
which you can use to authenticate your application with your Kafka instance.

.Prerequisites

* You've created a Kafka instance, and it has a `ready` status.

.Procedure

. Create a service account.
+
--
This example creates a service account and saves the credentials in a JSON file.

.Creating a service account
[source,shell]
----
$ rhoas service-account create --file-format json --short-description="rhoas-service-account"
----

[NOTE]
====
When creating a service account, you can choose the file format and location to save the credentials.
For more information, see the `rhoas service-account create` command help.
====
--

. To verify your service account credentials,
view the `credentials.json` file that you created.
+
--
.Example `credentials.json` file
[source,json,subs="+attributes,+quotes"]
----
{
	"clientID":"_<client-id>_",
	"clientSecret":"_<client-secret>_",
    "oauthTokenUrl": "{sso-token-url}"
}
----
You use these credentials and the bootstrap server URL to connect your applications and services to your Kafka instance.
--

. Set the permissions for your service account to access the Kafka instance resources.
+
--
This example allows applications to produce and consume messages from topics starting with a specified prefix that belong to any consumer group. The service account information you input here is the `clientID` value from the previous step.

.Assigning access permissions to a service account
[source,shell,subs="+quotes"]
----
$ rhoas kafka acl grant-access --consumer --producer \
    --service-account _<client-id>_ --topic-prefix myapp  --group all
----

The permissions you assign depend on whether your application produces or consumes messages.
--

[id="proc-creating-kafka-topic-cli_{context}"]
== Creating a Kafka topic

[role="_abstract"]
After creating a Kafka instance, you can create Kafka topics to start producing and consuming messages in your services.

.Prerequisites

* You've created a Kafka instance, and it has a `ready` status.

[NOTE]
====
You can use `rhoas kafka list` and `rhoas context set-kafka` to switch to a specific Kafka instance.

.List Kafka instances
[source,shell]
----
$ rhoas kafka list
----
.Selecting a Kafka instance to use
[source,shell]
----
$ rhoas context set-kafka --name my-kafka
----
====

.Procedure

. Create a Kafka topic with default values.
+
--
This example creates the `my-topic` Kafka topic.

.Creating a Kafka topic with default values
[source,shell]
----
$ rhoas kafka topic create --name my-topic
----

[NOTE]
====
If you do not want to use the default values,
you can specify the number of partitions (`--partitions`) and message retention time (`--retention-ms`).
For more information, use the command help `rhoas kafka topic create -h`.
====
--

. If necessary, you can edit or delete the topic by using the `rhoas kafka topic update` and `rhoas kafka topic delete` commands.

[id="proc-generating-kafka-configs-cli_{context}"]
== Generating configurations for a Kafka instance

[role="_abstract"]
After creating a Kafka instance, you can generate a configuration file that your applications can use to connect to your Kafka instance.

.Prerequisites

* You've created a Kafka instance, and it has a `ready` status.
* The Kafka instance is set in the current context.
* Your user account and org have quota for creating service accounts.

.Procedure

* Generate a configuration file for the current service context.
+
--
This example generates a JSON file with configurations for the Kafka instance you created.

.Generating a configuration file
[source,shell]
----
$ rhoas generate-config --type json
----
--

[id="proc-commands-managing-kafka_{context}"]
== Commands for managing Kafka

[role="_abstract"]
For more information about the `rhoas` commands you can use to manage your Kafka instance,
use the following command help:

* `rhoas kafka -h` for Kafka instances
* `rhoas service-account -h` for service accounts
* `rhoas kafka acl -h` for access management
* `rhoas kafka topic -h` for Kafka topics

[role="_additional-resources"]
.Additional resources
* {base-url-cli}{command-ref-url-cli}[_CLI command reference (rhoas)_^]
