////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////

//OpenShift Application Services
:org-name: Application Services
:product-long-rhoas: OpenShift Application Services
:community:
:imagesdir: ./images
:property-file-name: app-services.properties
:samples-git-repo: https://github.com/redhat-developer/app-services-guides
:base-url: https://github.com/redhat-developer/app-services-guides/tree/main/docs/

//OpenShift Application Services CLI
:rhoas-cli-base-url: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:rhoas-cli-ref-url: commands
:rhoas-cli-installation-url: rhoas/rhoas-cli-installation/README.adoc

//OpenShift Streams for Apache Kafka
:product-long-kafka: OpenShift Streams for Apache Kafka
:product-kafka: Streams for Apache Kafka
:product-version-kafka: 1
:service-url-kafka: https://console.redhat.com/application-services/streams/
:getting-started-url-kafka: kafka/getting-started-kafka/README.adoc
:kafka-bin-scripts-url-kafka: kafka/kafka-bin-scripts-kafka/README.adoc
:kafkacat-url-kafka: kafka/kcat-kafka/README.adoc
:quarkus-url-kafka: kafka/quarkus-kafka/README.adoc
:nodejs-url-kafka: kafka/nodejs-kafka/README.adoc
:rhoas-cli-getting-started-url-kafka: kafka/rhoas-cli-getting-started-kafka/README.adoc
:topic-config-url-kafka: kafka/topic-configuration-kafka/README.adoc
:consumer-config-url-kafka: kafka/consumer-configuration-kafka/README.adoc
:access-mgmt-url-kafka: kafka/access-mgmt-kafka/README.adoc
:metrics-monitoring-url-kafka: kafka/metrics-monitoring-kafka/README.adoc
:service-binding-url-kafka: kafka/service-binding-kafka/README.adoc

//OpenShift Service Registry
:product-long-registry: OpenShift Service Registry
:product-registry: Service Registry
:registry: Service Registry
:product-version-registry: 1
:service-url-registry: https://console.redhat.com/application-services/service-registry/
:getting-started-url-registry: registry/getting-started-registry/README.adoc
:quarkus-url-registry: registry/quarkus-registry/README.adoc
:rhoas-cli-getting-started-url-registry: registry/rhoas-cli-getting-started-registry/README.adoc
:access-mgmt-url-registry: registry/access-mgmt-registry/README.adoc
:content-rules-registry: https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1/guide/9b0fdf14-f0d6-4d7f-8637-3ac9e2069817[Supported Service Registry content and rules]

////
END GENERATED ATTRIBUTES
////

[id="chap-getting-started-rhoas-cli-kafka"]
= Getting started with the rhoas CLI for {product-long-kafka}
:context: getting-started-rhoas-kafka

[role="_abstract"]
With the {product-long-rhoas} `rhoas` command-line interface (CLI), you can manage OpenShift Streams for Apache Kafka from a terminal.

As a developer of applications and services,
you can use `rhoas` to create Kafka instances and connect your applications and services to these instances.
You can also create Kafka topics to store data for producers and consumers.

This guide describes how to get started quickly by doing the following:

* {base-url}{rhoas-cli-getting-started-url-kafka}#proc-creating-kafka-instance-cli_getting-started-rhoas-kafka[Create a Kafka instance]
* {base-url}{rhoas-cli-getting-started-url-kafka}#proc-creating-service-account-cli_getting-started-rhoas-kafka[Create a service account]
* {base-url}{rhoas-cli-getting-started-url-kafka}#proc-creating-kafka-topic-cli_getting-started-rhoas-kafka[Create a Kafka topic]
* {base-url}{rhoas-cli-getting-started-url-kafka}#proc-commands-managing-kafka_getting-started-rhoas-kafka[Use `rhoas` to manage your Kafka instances, service accounts, and Kafka topics]

//Additional line break to resolve mod docs generation error

[id="ref-kafka-cli-prereqs_{context}"]
== Prerequisites

[role="_abstract"]
* You've installed the `rhoas` CLI. For more information, see {base-url}{rhoas-cli-installation-url}[_Installing the rhoas CLI_^].

//Additional line break to resolve mod docs generation error

[id="proc-creating-kafka-instance-cli_{context}"]
== Creating a Kafka instance

[role="_abstract"]
A Kafka instance includes a Kafka cluster, bootstrap server, and other required configurations for connecting to Kafka producer and consumer services.

.Prerequisites

* You are logged in to `rhoas`.

.Procedure

. Enter the following command to create a Kafka instance with default values.
+
--
This example creates a Kafka instance called `my-kafka`.

.Creating a Kafka instance
[source,shell]
----
$ rhoas kafka create --name my-kafka
----

[NOTE]
====
If you do not want to use the default values,
enter the following command: `rhoas kafka create`.
You will be prompted to enter the `Name`, `Cloud Provider`, and `Cloud Region` for the Kafka instance.
====
--

. Verify that the Kafka instance is ready to use.
+
--
.Reviewing details of a Kafka instance
[source,shell]
----
$ rhoas status kafka
----

This command shows that the Kafka instance is ready to use,
because the `Status` field is `ready`.

[NOTE]
====
When you created the Kafka instance, it was set as the current instance automatically.
If you have multiple Kafka instances,
you can switch to a different instance by using the `rhoas kafka use` command.
====
--

[id="proc-creating-service-account-cli_{context}"]
== Creating a service account

[role="_abstract"]
To connect your applications or services to a Kafka instance, you must first create a service account with credentials.
The credentials are exported to a file on your computer,
which you can use to authenticate your application with your Kafka instance.

.Prerequisites

* You've created a Kafka instance, and it has a `ready` status.

.Procedure

. Create a service account.
+
--
This example creates a service account and saves the credentials in a JSON file.

.Creating a service account
[source,shell]
----
$ rhoas service-account create --file-format json --short-description="rhoas-service-account"
----

[NOTE]
====
When creating a service account, you can choose the file format and location to save the credentials.
For more information, see the `rhoas service-account create` command help.
====
--

. To verify your service account credentials,
view the `credentials.json` file that you created.
+
--
.Example `credentials.json` file
[source,json]
----
{
	"clientID":"srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1",
	"clientSecret":"facf3df1-ab97-2253-aa87-ab97",
    "oauthTokenUrl": "https://identity.api.openshift.com/auth/realms/rhoas/protocol/openid-connect/token"
}
----
You use these credentials and the bootstrap server URL to connect your applications and services to your Kafka instance.
--

. Set the permissions for your service account to access the Kafka instance resources.
+
--
This example allows applications to produce and consume messages from topics starting with a specified prefix that belong to any consumer group. The service account information you input here is the clientID from the previous step.

.Assigning access permissions to a service account
[source,shell]
----
$ rhoas kafka acl grant-access --consumer --producer \
    --service-account srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1 --topic-prefix myapp  --group all
----

The permissions you assign depend on whether your application produces or consumes messages.
--

[id="proc-creating-kafka-topic-cli_{context}"]
== Creating a Kafka topic

[role="_abstract"]
After creating a Kafka instance, you can create Kafka topics to start producing and consuming messages in your services.

.Prerequisites

* You've created a Kafka instance, and it has a `ready` status.

[NOTE]
====
You can use `rhoas kafka list` and `rhoas kafka use` to switch to a specific Kafka instance.

.List Kafka instances
[source,shell]
----
$ rhoas kafka list
----
.Selecting a Kafka instance to use
[source,shell]
----
$ rhoas kafka use --name my-kafka
----
====

.Procedure

. Create a Kafka topic with default values.
+
--
This example creates the `my-topic` Kafka topic.

.Creating a Kafka topic with default values
[source,shell]
----
$ rhoas kafka topic create --name my-topic
----

[NOTE]
====
If you do not want to use the default values,
you can specify the number of partitions (`--partitions`) and message retention time (`--retention-ms`).
For more information, use the command help `rhoas kafka topic create -h`.
====
--

. If necessary, you can edit or delete the topic by using the `rhoas kafka topic update` and `rhoas kafka topic delete` commands.

[id="proc-commands-managing-kafka_{context}"]
== Commands for managing Kafka

[role="_abstract"]
For more information about the `rhoas` commands you can use to manage your Kafka instance,
use the following command help:

* `rhoas kafka -h` for Kafka instances
* `rhoas service-account -h` for service accounts
* `rhoas kafka acl -h` for access management
* `rhoas kafka topic -h` for Kafka topics

[role="_additional-resources"]
.Additional resources
* {rhoas-cli-base-url}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
