//OpenShift Streams for Apache Kafka
:base-url: https://github.com/redhat-developer/app-services-guides/tree/main/docs/
:product-long-rhoas: OpenShift Application Services
:rhoas-cli-base-url: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:rhoas-cli-ref-url: commands
:rhoas-cli-getting-started-url-context: cli-context/
:samples-git-repo: https://github.com/redhat-developer/app-services-guides
:product-kafka: Streams for Apache Kafka

[id="chap-getting-started-rhoas-cli-context"]
= Getting started with the rhoas CLI for context management
:context: getting-started-rhoas-context

[role="_abstract"]
As a developer of applications and services,
you can use `rhoas` to group service instances for specific use-cases, projects or environments in contexts and generate connection configuration details to connect applications to the service instances.

Service contexts contain references to service instances used for specific projects or environments. With the `generate-config` command you can generate connection configuration details for your applications to connect to the service instances. This gives you the flexibility to quickly and seamlessly switch between sets of service instances and generate connection configurations.

This guide describes how to get started quickly by doing the following:

* {base-url}{rhoas-cli-getting-started-url-context}#proc-creating-context-cli_getting-started-rhoas-context[Create a service context]
* {base-url}{rhoas-cli-getting-started-url-context}#proc-creating-services-cli_getting-started-rhoas-context[Create services in service context]
* {base-url}{rhoas-cli-getting-started-url-context}#proc-generating-config-cli_getting-started-rhoas-context[Generating application configurations]

[id="ref-kafka-cli-prereqs_{context}"]
== Prerequisites

[role="_abstract"]
* You've installed the `rhoas` CLI. For more information, see {base-url}{rhoas-cli-installation-url}[_Installing the rhoas CLI_^].

[id="proc-creating-context-cli_{context}"]
== Creating a service context

.Procedure

Enter the following command to create a context named `my-context`

.Creating a context
[source,shell]
----
$ rhoas context create --name my-context
----

[NOTE]
====
By default, the created context is set as the current context.
All the service based commands are executed against the service instances set in the current context.
====

[id="proc-creating-services-cli_{context}"]
== Creating services in a context

[role="_abstract"]
Context contains identifiers to service instances.
All the service based commands are executed against the service instances set in the current context.

.Procedure

. Creating a Kafka Instance
+
--
[source,shell]
----
$ rhoas kafka create
----
--

. Setting Service Registry Instance in the current context
+
--
[source,shell]
----
$ rhoas service-registry create
----

[NOTE]
====
Creating a new service instance automatically sets it in the current context.
====
--

. Check status of the current context
+
--
After creating service(s) in the current context, their status can be checked using the `rhoas context status` command
.View status of the current context
[source,shell]
----
$ rhoas context status
----
--

[id="proc-generating-config-cli_{context}"]
== Generating application configurations for contexts

`rhoas generate-config` command generates application configurations that can be used to connect to the services set in context.
The configurations can be saved in yaml, json, env file or as kubernetes secret. Connection configuration consists of credentials and endpoints that will be used by applications to connect to the services.

.Generating configurations for context named as my "my-context"
[source,shell]
----
$ rhoas generate-config --name my-context --type json
----

=== Generating configurations for Quarkus applications

[role="_abstract"]
For this quick start, you'll use the Quarkus sample code from the {product-kafka} {samples-git-repo}[Guides and Samples^] repository in GitHub.
The quick start will walk you through how you can generate connection configurations for Quarkus applications using a single command.

.Procedure
. On the command line, clone the {product-kafka} {samples-git-repo}[Guides and Samples^] repository from GitHub.
+
.Cloning the guides and samples repository
[source,subs="+attributes"]
----
git clone {samples-git-repo} app-services-guides
----
. In your IDE, open the `code-examples/quarkus-kafka-quickstart` directory from the repository that you cloned.
. Generate the application configurations for the Quarkus application.
+
--
[source,shell]
----
$ rhoas generate-config --type env --output-file .env 
----
--
. Create the "prices" Kafka topic.
+
--
[source,shell]
----
$ rhoas kafka topic create --name prices
----
--
. Create ACLs for the service account created using the `rhoas generate-config` command.
+
--
[source,shell]
----
$ rhoas kafka acl grant-access --producer --consumer --service-account <client_id> --topic prices --group all
----
--
. Run the Quarkus application in dev mode.
+
--
[source,shell]
----
./mvnw quarkus:dev
----
--

[role="_abstract"]
The Quarkus application starts producing and consuming messages to and from the "prices" Kafka topic.
After the application is running, in a web browser, go to http://localhost:8080/prices.html[^] and verify that the `Last price` is updated.

If the Quarkus application fails to run, review the error log in the terminal and address any problems. Also, review the steps to ensure that the Quarkus application and Kafka topic are configured correctly.

[role="_additional-resources"]
.Additional resources
* {rhoas-cli-base-url}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]