////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////


:community:
:imagesdir: ./images
:product-version: 1
:product-long: Application Services
:product: App Services
:registry-product-long: OpenShift Service Registry
:registry: Service Registry
// Placeholder URL, when we get a HOST UI for the service we can put it here properly
:service-url: https://console.redhat.com/beta/application-services/streams/
:registry-url: https://console.redhat.com/beta/application-services/service-registry/
:property-file-name: app-services.properties
:rhoas-version: 0.29.0

// Other upstream project names
:samples-git-repo: https://github.com/redhat-developer/app-services-guides

//URL components for cross refs
:base-url: https://github.com/redhat-developer/app-services-guides/blob/main/
:base-url-cli: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:getting-started-url: getting-started/README.adoc
:kafka-bin-scripts-url: kafka-bin-scripts/README.adoc
:kafkacat-url: kafkacat/README.adoc
:quarkus-url: quarkus/README.adoc
:rhoas-cli-url: rhoas-cli/README.adoc
:rhoas-cli-ref-url: commands
:topic-config-url: topic-configuration/README.adoc
:consumer-config-url: consumer-configuration/README.adoc
:service-binding-url: service-discovery/README.adoc

////
END GENERATED ATTRIBUTES
////

[id="chap-getting-started-rhoas-cli-registry"]
= Getting started with the Service Registry using rhoas CLI
:context: getting-started-rhoas-registry

[IMPORTANT]
====
The `rhoas` command-line interface (CLI) is currently available for Development Preview. Development Preview releases provide early access to a limited set of features that might not be fully tested and that might change in the final GA version. Users should not use Development Preview software in production or for business-critical workloads. Limited documentation is available for Development Preview releases and is typically focused on fundamental user goals.
====

[role="_abstract"]
With the `rhoas` command-line interface (CLI), you can manage your application services from a terminal.
This guide describes how to get started quickly with Service Registry and the RHOAS CLI.

--
* Using `rhoas` CLI to manage Service Registry instances .

* Retrieve configuration to use Service Registry instance in your application

* Manage Service Registry Artifacts directly from command line
--

[id="proc-installing-rhoas_{context}"]
== Installing the rhoas CLI

[role="_abstract"]
If you haven't installed RHOAS CLI you can install it using the following guide
 TODO link to CLI installation guide

NOTE:  Service Registry integration requires *latest* version of RHOAS CLI


[id="proc-using-rhoas_registry{context}"]
== Using rhoas CLI to manage Service Registry instances

[role="_abstract"]
As a developer of applications and services,
you can use `rhoas` to create Service Registry instances and connect your applications and services to these instances.

The following procedures demonstrate a basic workflow to get you started:

> TODO - correct urls

* link:{base-url}{rhoas-cli-url}#creating-registry-instance[Create a Service Registry instance]

* link:{base-url}{rhoas-cli-url}#creating-service-account_registry[Create a service account for Service Registry ]

* link:{base-url}{rhoas-cli-url}#managing-artifacts[Creating and managing artifacts]


[discrete,id="creating-registry-instance_{context}"]
=== Creating a Service Registry instance

Service Registry instance will let us to upload and manage various types of artifacts - ranging from Kafka Avro Schemas that can be used with Managed Kafka to OpenAPI documents describing your API.

.Prerequisites

* You are logged in to `rhoas`.

.Procedure

. Enter the following command to create an instance with default configuration.
+
--
This example creates a Service Registry instance called `my-registry`.

.Creating a Service Registry instance
[source,shell]
----
$ rhoas service-registry create --name my-registry
Creating Service Registry instance with name: my-registry
✔️ Successfully created Service Registry instance
{
  "browserUrl": "https://console.redhat.com/beta/application-services/service-registry/t/63620903-4a29-4ba4-8229-7ab793bf73f3",
  "created_at": "2021-09-27T15:35:01Z",
  "href": "/api/serviceregistry_mgmt/v1/registries/63620903-4a29-4ba4-8229-7ab793bf73f3",
  "id": "63620903-4a29-4ba4-8229-7ab793bf73f3",
  "instance_type": "eval",
  "kind": "ServiceRegistry",
  "name": "my-registry",
  "owner": "wtrocki@redhat.com",
  "status": "accepted",
  "updated_at": "2021-09-27T15:35:01Z"
}
----

[NOTE]
====
After creation your service registry instance will be added to service context and used by default
when executing other instance specific commands
====
--

. Enter the following command to verify that the instance is ready to use.
+
--
This command shows that the Service Registry instance is ready to use,
because the `Status` field is `ready`.

.Reviewing details of a Registry instance
[source,shell]
----
$ rhoas status service-registry

  Service Registry
  -----------------------------------------------------------------------------------------------------------------------------------------------------------------
  ID:                    63620903-4a29-4ba4-8229-7ab793bf73f3
  Name:                  my-registry
  Status:                ready
  Registry URL:          https://service-registry-service-registry-production.apps.app-sre-prod-04.i5h0.p1.openshiftapps.com/t/63620903-4a29-4ba4-8229-7ab793bf73f3
----

[NOTE]
====
When you created the Service Registry instance, it was set as the current instance automatically.
If you have multiple Service Registry instances,
you can switch to a different instance by using the `rhoas service-registy use` command.
====
--

[discrete,id="creating-service-account_registry_{context}"]
=== Creating a service account for Service Registry

To connect your applications or services to a Service Registry instance, you must first create a service account with credentials.
The credentials are exported to a file on your computer,
which you can use to authenticate your application with your Kafka instance.

.Prerequisites

* You have created a Service Registry instance, and it has a `ready` status.

.Procedure

. Enter the following command to create a service account.
+
--
This example creates a service account called `my-service-acct` and saves the credentials in a JSON file.

.Creating a service account
[source,shell]
----
$ rhoas service-account create --name "my-service-acct" --file-format json

Service account my-service-account created
Credentials saved to /home/developer/my-project/credentials.json
----

Your service account credentials are created and saved to a JSON file.

[NOTE]
====
When creating a service account, you can choose the file format and location to save the credentials.
For more information, see the `rhoas service-account create` command help.
====
--

. To verify your service account credentials,
view the `credentials.json` file that you created.
+
--
.Verifying service account credentials
[source,shell]
----
$ cat credentials.json
{
	"user":"srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1",
	"password":"facf3df1-ab97-2253-aa87-ab97",
  "oauth_token_endpoint_url": https://identity.api.openshift.com/auth/realms/rhoas/protocol/openid-connect/token
}
----
You'll use these credentials and the URL to connect your applications and services to your Service Registry instance in 
order to retrieve artifacts and use them directly in your service. 
RHOAS CLI can be also used to manage artifacts directly from command line without using created service account.
--

[discrete,id="managing-artifacts{context}"]
=== Creating and Managing a Service Registry Artifacts 

After creating a Service registry instance, you can use RHOAS CLI to create and manage artifacts.

.Prerequisites

* You have created a Service Registry instance, and it has a `ready` status.

.Procedure

. Verify that you are using the Service Registry instance that you created.
+
--
This example switches to the `my-registry` instance that was previously created.

.Selecting a Registry instance to use
[source,shell]
----
$ rhoas service-registry use --name my-registry
Service Registry instance "my-registry" has been set as the current instance.
----
--

. Create a Service Registry artifact using example .
+
--
This example creates a Avro Schema artifact under `my-artifact` id and default group

.Creating artifact
[source,shell]
----
wget https://github.com/redhat-developer/app-services-cli/blob/main/docs/resources/avro-userInfo.json
$ rhoas service-registry artifact create --type=AVRO --artifact-id=my-artifact avro-userInfo.json 
----

[NOTE]
====
You can setup custom values like --group,--version, --description, --name and --type to modify the artifact metadata when creating it.
====
--

. If necessary, you can perform additional operation on artifacts like `rhoas service-registry artifact metadata-set`  

. Manage a Service Registry artifacts.
+
--
This example we can list all artifacts for service registry and view their metadata

.Listing artifact
[source,shell]
----
rhoas service-registry artifact list 
Using default artifacts group.
  ID            NAME   CREATED ON                 CREATED BY             TYPE   STATE    
 ------------- ------ -------------------------- ---------------------- ------ --------- 
  my-artifact          2021-09-27T16:17:35+0000   wtrocki_kafka_devexp   AVRO   ENABLED  
----

Fetch their version information
[source,shell]
----
rhoas service-registry artifact versions --artifact-id=my-artifact
{
  "count": 1,
  "versions": [
    {
      "contentId": 29,
      "createdBy": "wtrocki_kafka_devexp",
      "createdOn": "2021-09-27T16:17:35+0000",
      "globalId": 28,
      "state": "ENABLED",
      "type": "AVRO",
      "version": "1"
    }
  ]
}
----

and view metadata

----
rhoas service-registry artifact metadata-get --artifact-id=my-artifact
Using default artifacts group.
Fetching artifact metadata
✔️ Successfully fetched artifact metadata
{
  "contentId": 29,
  "createdBy": "wtrocki_kafka_devexp",
  "createdOn": "2021-09-27T16:17:35+0000",
  "globalId": 28,
  "id": "my-artifact",
  "modifiedBy": "wtrocki_kafka_devexp",
  "modifiedOn": "2021-09-27T16:17:35+0000",
  "state": "ENABLED",
  "type": "AVRO",
  "version": "1"
}
----

--

 

[discrete,id="commands-managing-registry_{context}"]
=== Commands for managing Service Registry Instance

The following tables show the `rhoas` commands you can use to manage your Service Registry instances and associated artifacts.
For more information about any of the commands,
view the command help (for example, `rhoas service-registry -h` or `rhoas service-registry artifact -h`).

TODO ? Do we need that considering there is reference guide?


