////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////


:org-name: Application Services
:community:
:imagesdir: ./images
:product-version: 1
:product-long: OpenShift Streams for Apache Kafka
:product: Streams for Apache Kafka
:registry-product-long: OpenShift Service Registry
:registry-product: Service Registry
:registry: Service Registry
:cli-product-long: OpenShift Application Services
// Placeholder URL, when we get a HOST UI for the service we can put it here properly
:service-url: https://console.redhat.com/application-services/streams/
:registry-url: https://console.redhat.com/application-services/service-registry/
:property-file-name: app-services.properties

// Other upstream project names
:samples-git-repo: https://github.com/redhat-developer/app-services-guides

//URL components for cross refs
:base-url: https://github.com/redhat-developer/app-services-guides/blob/main/
:base-url-cli: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:getting-started-url: getting-started/README.adoc
:getting-started-service-registry-url: getting-started-service-registry/README.adoc
:kafka-bin-scripts-url: kafka-bin-scripts/README.adoc
:kafkacat-url: kcat/README.adoc
:quarkus-url: quarkus/README.adoc
:quarkus-service-registry-url: quarkus-service-registry/README.adoc
:rhoas-cli-url: rhoas-cli/README.adoc
:rhoas-cli-kafka-url: rhoas-cli-kafka/README.adoc
:rhoas-cli-service-registry-url: rhoas-cli-service-registry/README.adoc
:rhoas-cli-ref-url: commands
:topic-config-url: topic-configuration/README.adoc
:consumer-config-url: consumer-configuration/README.adoc
:service-binding-url: service-binding/README.adoc
:access-mgmt-url: access-mgmt/README.adoc
:access-mgmt-service-registry-url: access-mgmt-service-registry/README.adoc
:metrics-monitoring-url: metrics-monitoring/README.adoc

////
END GENERATED ATTRIBUTES
////

[id="chap-managing-service-registry-access"]
= Managing account access in {registry-product-long}
ifdef::context[:parent-context: {context}]
:context: managing-access-service-registry

// Purpose statement for the assembly
[role="_abstract"]
As a {registry} instance owner, an instance administrator, or an organization administrator in {registry-product-long}, you can manage the level of access that other user accounts and service accounts have to your {registry} instance. You can grant or remove access to your  {registry} instance for specific user accounts in your organization based on user roles. You can also allow other users or service accounts to manage the level of access to your instance for you.

{registry} instance owners or instance administrators can manage access for only the {registry} instances that they create or for instances that the owner has allowed them to access and change. Organization administrators can manage access for all {registry} instances.

//Additional line break to resolve mod docs generation error, not sure why. Leaving for now. (Stetson, 20 May 2021)

[id="con-registry-access-management_{context}"]
== Access management in {registry-product-long}

[role="_abstract"]
{registry-product-long} uses Role-Based Access Control (RBAC) to manage how other user accounts and service accounts access the {registry} instances that you create and the artifacts that they contain. You can manage access for only the {registry} instances that you create or for instances that the owner has allowed you to access and change.

An account in {registry-product-long} is either a user account or a service account. A user account enables users in your organization to access your {registry} instances. A service account enables your client application or tool to connect securely and to access your {registry} instances.


=== User roles in {registry-product-long}

The {registry} web console provides an *Access* tab on the {registry} instance page. {registry} instance owners, instance administrators, and organization administrators can use this tab to manage the following user roles:

* *Administrator* - Can perform the following in this {registry} instance:
** View or write user roles
** View or write schema and API artifacts 
** Configure global rules for compatibility and validity
** Import/export {registry} data 
* *Manager* - Can view or write schema and API artifacts in this {registry} instance
* *Viewer* - Can view schema and API artifacts in this {registry} instance

IMPORTANT: The owner of a {registry} instance has the administrator role for that instance by default, and can assign roles in the same organization. Other user accounts or service accounts in the organization have no access to that instance by default.

In addition to the web console, the `rhoas` CLI provides commands to manage user roles, and the core {registry} REST API also provides Admin API endpoints for managing user roles.

[id="proc-viewing-registry-roles_{context}"]
== Viewing user roles in a {registry} instance 

[role="_abstract"]
You can view the user roles assigned to your {registry} instances that manage how other user accounts or service accounts interact with the instance and the artifacts that it contains. You can view user roles and accounts only for instances that you create or for instances that the owner has assigned you access to.

.Prerequisites
* The {registry} instance has been created and is in *Ready* state.
* The user accounts or service accounts that you want to view have been created in the organization and have already been assigned user roles.

.Procedure
. In the web console, go to *{registry}* > *{registry} Instances* and click the name of the {registry} instance that you want to view roles and accounts for.
. Click the *Access* tab to view the roles and accounts assigned for this instance:
.. To view specific accounts, click *Account*, enter the user account or service account name, and click the search button.
.. To view accounts with a specific role, click *Role*, select *Filter by role* and then the role you want (for example, *Administrator*), and click the search button.
. Click *Clear all filters* when done.

[id="proc-setting-registry-roles_{context}"]
== Assigning user roles in a {registry} instance 

[role="_abstract"]
In {registry-product-long}, you can assign user roles in your {registry} instances to manage how other user accounts or service accounts interact with the instance and the artifacts that it contains. You can assign user roles only for instances that you create or for instances that the owner has assigned you access to.

.Prerequisites
* The {registry} instance has been created and is in *Ready* state.
* The user accounts or service accounts that you're assigning roles to have been created in the organization.

.Procedure
. In the web console, go to *{registry}* > *{registry} Instances* and click the name of the {registry} instance that you want to assign roles for.
. Click the *Access* tab to view the accounts and roles already assigned for this instance.
. Click *Grant access* to assign roles to accounts.
. In the *Account* field, select or enter the service account or user account name that you want to assign the role to: 
** A service account enables your application or tool to connect securely to your instance
** A user account enables users in your organization to access instances
. Select the *Role* that you want to assign to your account, for example, *Manager* for write access to this instance.
. Click *Save*.

[id="proc-remove-registry-roles_{context}"]
== Editing or removing user roles in a {registry} instance 

[role="_abstract"]
You can edit or remove the user roles assigned in your {registry} instances that manage how other user accounts or service accounts interact with the instance and the artifacts that it contains. You can edit or remove user roles only for the instances that you create or for instances that the owner has assigned you access to.

.Prerequisites
* The {registry} instance has been created and is in *Ready* state.
* The user accounts or service accounts have been created in the organization and the user roles have already been assigned.

.Procedure
. In the web console, go to *{registry}* > *{registry} Instances* and click the name of the {registry} instance that you want to remove a user role for.
. Click the *Access* tab to view the accounts and roles assigned for this instance.
. Select the options menu (three vertical dots) next to the assigned *Role* name: 
.. To change to a different role, click *Edit* and select the new user role, for example, *Viewer* for read-only access to this instance.  
.. To remove the currently assigned role, click *Remove* and confirm in the dialog.



[role="_additional-resources"]
.Additional resources
* {base-url}{getting-started-service-registry-url}[_Getting started with {registry-product-long}_^]
* {base-url}{rhoas-cli-service-registry-url}[_Getting started with the rhoas CLI for {registry-product-long}_^]
* {base-url-cli}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
* https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/assets-attachments/registry-rest-api.htm[_Apicurio Registry REST API documentation_^]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
