////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////

//OpenShift Application Services
:org-name: Application Services
:product-long-rhoas: OpenShift Application Services
:community:
:imagesdir: ./images
:property-file-name: app-services.properties
:samples-git-repo: https://github.com/redhat-developer/app-services-guides
:base-url: https://github.com/redhat-developer/app-services-guides/tree/main/docs/

//OpenShift Application Services CLI
:rhoas-cli-base-url: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:rhoas-cli-ref-url: commands
:rhoas-cli-installation-url: rhoas/rhoas-cli-installation/README.adoc

//OpenShift Streams for Apache Kafka
:product-long-kafka: OpenShift Streams for Apache Kafka
:product-kafka: Streams for Apache Kafka
:product-version-kafka: 1
:service-url-kafka: https://console.redhat.com/application-services/streams/
:getting-started-url-kafka: kafka/getting-started-kafka/README.adoc
:kafka-bin-scripts-url-kafka: kafka/kafka-bin-scripts-kafka/README.adoc
:kafkacat-url-kafka: kafka/kcat-kafka/README.adoc
:quarkus-url-kafka: kafka/quarkus-kafka/README.adoc
:nodejs-url-kafka: kafka/nodejs-kafka/README.adoc
:rhoas-cli-getting-started-url-kafka: kafka/rhoas-cli-getting-started-kafka/README.adoc
:topic-config-url-kafka: kafka/topic-configuration-kafka/README.adoc
:consumer-config-url-kafka: kafka/consumer-configuration-kafka/README.adoc
:access-mgmt-url-kafka: kafka/access-mgmt-kafka/README.adoc
:metrics-monitoring-url-kafka: kafka/metrics-monitoring-kafka/README.adoc
:service-binding-url-kafka: kafka/service-binding-kafka/README.adoc

//OpenShift Service Registry
:product-long-registry: OpenShift Service Registry
:product-registry: Service Registry
:registry: Service Registry
:product-version-registry: 1
:service-url-registry: https://console.redhat.com/application-services/service-registry/
:getting-started-url-registry: registry/getting-started-registry/README.adoc
:quarkus-url-registry: registry/quarkus-registry/README.adoc
:rhoas-cli-getting-started-url-registry: registry/rhoas-cli-getting-started-registry/README.adoc
:access-mgmt-url-registry: registry/access-mgmt-registry/README.adoc
:content-rules-registry: https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1/guide/9b0fdf14-f0d6-4d7f-8637-3ac9e2069817[Supported Service Registry content and rules]
:service-binding-url-registry: registry/service-binding-registry/README.adoc

//OpenShift Connectors
:product-long-connectors: OpenShift Connectors
:service-url-connectors: https://console.redhat.com/application-services/connectors
////
END GENERATED ATTRIBUTES
////

[id="chap-adding-connectors-addon"]
= Adding the Red Hat {product-long-connectors} add-on to an OpenShift Dedicated trial cluster 
ifdef::context[:parent-context: {context}]
:context: adding-connectors-addon

[role="_abstract"]
This document describes how to add Red Hat OpenShift Connectors to an OpenShift Dedicated (OSD) Customer Cloud Subscription (CCS) trial cluster in your own OSD environment.

The OSD CCS trial has a 60-day lifespan and the number of Connectors instances that you create is not limited. The trial environment is useful when you want to create Proof of Concept solutions.

NOTE: Alternatively, for quick access, you can try OpenShift Connectors on the Service Preview Evaluation site.  The evaluation site involves 48 hour expiration windows and limits you to four Connectors instances at a time, as described in Service Preview guidelines.

.Prerequisites
* You must install the OpenShift Connectors service on an OSD trial cluster. 
* You must have an existing Amazon Web Service (AWS) account.
* Your trial cluster must use CCS on your existing AWS account. For information, see About the OpenShift Dedicated Trial. For more information on CCS, see Customer Cloud Subscriptions on AWS .
* Your trial cluster cannot have the strimzi operator nor the Camel K operator installed (to avoid possible conflicts with the strimzi and Camel K operators that are installed as part of the Connectors Add-on).
* You have cluster administrator permissions for your OSD account    
* You downloaded and installed the following command line (CLI) tools:
+
`curl`
+
`jq`

.Procedure

. Request a Red Hat OpenShift Connectors namespace for your trial OSD cluster:
.. Login to the Hybrid Cloud Console (https://console.redhat.com/openshift) and then navigate to the Downloads page.
.. Scroll down to the bottom of the page and then click View API Token.
.. Click Load Token and then follow the 'Using your token in the command line' instructions to install the ocm command-line tool and run the authentication command in a terminal window.
.. In your terminal window, set the following environment variable to the URL for the Red Hat OpenShift Connecters API:
+
----
export CONNECTORS_CLUSTERS=<BASE_PATH>/api/connector_mgmt/v1/kafka_connector_clusters
Send a request for a Connectors Namespace with the following command:
curl --insecure --oauth2-bearer "$(ocm token)" -S -s -D /dev/stderr "${CONNECTORS_CLUSTERS}" -d '{ "name": "'"${USER}"'"}' | jq
----
+
The Red Hat OpenShift Connecters API creates a new Connectors Namespace (a logical space where your Connectors will be deployed) and assigns it a unique ID. It returns information about your Connectors Namespace, including a unique ID value, for example:
+
----
{
  "id": "c97iarsotd37bufhsta0",
  "kind": "ConnectorCluster",
  "href": "/api/connector_mgmt/v1/kafka_connector_clusters/c97iarsotd37bufhsta0",
  "owner": "bob",
  "created_at": "2022-04-07T17:54:55.873600399Z",
  "modified_at": "2022-04-07T17:54:55.867541723Z",
  "name": "bob",
  "status": {
    "state": "disconnected"
  }
}
----

.. Copy the id value from the response.
.. Retrieve the add-on parameters with the following command (replacing the <ID> with the id value that you copied in Step 6):
+
----
curl --insecure --oauth2-bearer "$(ocm token)" -S -s "${CONNECTORS_CLUSTERS}"/<ID>/addon_parameters | jq
----
+
For example:
+
----
curl --insecure --oauth2-bearer "$(ocm token)" -S -s "${CONNECTORS_CLUSTERS}"/c97iarsotd37bufhsta0/addon_parameters | jq
----
+
This command returns a list of parameters similar to the following:
+
----
ID    VALUE
__    __    
control-plane-base-url        https://<cos-fleet-manager-URL>
cluster-id            c99999c9999c9999ccc
auth-token-url            https://<connect-fleetshard-agent-URL>
mas-sso-base-url        https://<identity-URL>
mas-sso-realm            rhoas
client-id            <connect-fleetshard-agent-ID>
client-secret            <client-secret>
----

.. Save these parameters and their values (for example, copy and paste them to a temporary text file). You need them in the next step. 

. Configure the Connectors add-on in your OSD trial cluster:
.. In a web browser, login to the Hybrid Cloud console with cluster administrator permissions.
.. Click Clusters and then click the name of your trial cluster.
.. On the trial cluster’s page, click the Add-ons tab.
.. Click the Red Hat OpenShift Connectors card and then click Install. The Configure Red Hat OpenShift Connectors page opens.
.. Fill in the required configuration information by copying and pasting the values of the add-on parameters (that you obtained in Step 7 and saved in Step 8).
+
*Connectors Cluster ID* - The value of the cluster-id add-on parameter.
+
*Control Plane URL* - The value of the control-plane-base-url add-on parameter.
+
*SSO Authentication Server URL* - The value of the mas-sso-base-url add-on parameter.
+
*SSO Authentication Realm* -The value of the rhoas add-on parameter. 
+
*SSO Client ID* - The value of the client-id add-on parameter.
+
*SSO Client Secret* - The value of the client-secret add-on parameter.

.. Click *Install*.

.. On the Add-ons page, the Red Hat OpenShift Connectors card indicates the status of the installation. Wait until the status is Installed.

.. At the top of the web console, click All Apps and Services > Connectors.
+
You can now create Connectors instances.

_If you heed help, send an email to rhosak-eval-support@redhat.com_


.Next Steps

* Take the OpenShift Connectors Pendo Tour
* Try the Getting Started with Connectors quick start


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]