[id='con-binding-openshift-application-using-cli_{context}']
= Binding an OpenShift application to {product-long} using the RHOAS CLI
:imagesdir: ../_images

When the Red Hat OpenShift Application Services (RHOAS) Operator and Service Binding Operator are installed on your OpenShift cluster, you can use the RHOAS CLI to interact directly with the cluster. One CLI command instructs the RHOAS Operator to connect a specified Kafka instance to your OpenShift cluster. Another CLI command instructs the Service Binding Operator to automatically inject a specified application running on the cluster with the parameters required to connect to the Kafka instance. Using the Service Binding Operator to automatically inject an application with connection parameters for a Kafka instance is called __service binding__.

The following tutorial shows how to use the RHOAS CLI to perform service binding. In the tutorial, you create an example Quarkus application and connect this to a Kafka instance. link:https://quarkus.io/[Quarkus^] is a Kubernetes-native Java framework that is optimized for serverless, cloud, and Kubernetes environments.

When you perform service binding, the Service Binding Operator injects connection parameters as files into the pod for the application. Because the example Quarkus application uses the `quarkus-kubernetes-service-binding` link:https://quarkus.io/guides/deploying-to-kubernetes#service-binding[extension^], the application automatically detects and uses the injected connection parameters.

In general, this automatic injection and detection of connection parameters eliminates the need to manually configure an application to connect to a Kafka instance in {product}. This is a particular advantage if you have many applications in your project that you want to connect to a Kafka instance.
