[id='con-registry-access-management_{context}']
= Access management in {product-long-registry}
:imagesdir: ../_images

[role="_abstract"]
{product-long-registry} uses Role-Based Access Control (RBAC) to manage how other user accounts and service accounts access the {registry} instances that you create and the artifacts that they contain. You can manage access for only the {registry} instances that you create or for instances that the owner has allowed you to access and change.

An account in {product-long-registry} is either a user account or a service account. A user account enables users in your organization to access your {registry} instances. A service account enables client applications or tools to connect securely to your {registry} instances.


== User roles in {product-long-registry}

The {registry} web console provides an *Access* tab on the {registry} instance page. {registry} instance owners, instance administrators, and organization administrators can use this tab to manage the following user roles:

Administrator:: Users with the Administrator role can perform the following tasks in this {registry} instance:
* View or write schema and API artifacts
* Configure user roles for access
* Configure {registry} settings
* Configure global rules for artifact compatibility and validity
* Import or export {registry} data
Manager:: Users with the Manager role can view or write schema and API artifacts in this {registry} instance.
Viewer:: Users with the Viewer role can view schema and API artifacts in this {registry} instance.

IMPORTANT: The owner of a {registry} instance has the Administrator role for that instance by default, and can assign roles in the same organization. Other user accounts or service accounts in the organization have no access to that instance by default.

In addition to the web console, the `rhoas` CLI provides commands to manage user roles. The core {registry} REST API also provides Admin API endpoints for managing user roles.
