[id='con-kafka-registry-binding-quarkus-application-using-cli_{context}']
= Binding a Quarkus application to {product-long} and {registry-product-long} using the RHOAS CLI
:imagesdir: ../_images

When the RHOAS Operator and Service Binding Operator are installed on your OpenShift cluster and you've connected a Kafka and {registry} instance to the cluster, you're ready to deploy an application and perform service binding. __Service binding__ means instructing the Service Binding Operator to automatically inject the application with the parameters required to connect to the Kafka and {registry} instances.

The following tutorial shows how to use the RHOAS CLI to perform service binding. In the tutorial, you create an example Quarkus application and connect this to a Kafka and {registry} instance. link:https://quarkus.io/[Quarkus^] is a Kubernetes-native Java framework that is optimized for serverless, cloud, and Kubernetes environments.

When you perform service binding, the Service Binding Operator automatically injects connection parameters as files into the pod for the application. The example Quarkus application in this tutorial uses link:https://quarkus.io/guides/deploying-to-kubernetes#service-binding[service binding extensions^] for Kafka, {registry}, and the Service Binding Operator. These extensions enable the application to automatically detect and use the injected connection parameters, eliminating the need for manual configuration of the application.

In general, this automatic injection and detection of connection parameters eliminates the need to manually configure an application to connect to a Kafka or {registry} instance. This is a particular advantage if you have many applications in your project that you want to connect to these cloud services.

== Prerequisites
* The Service Binding Operator is installed on your OpenShift cluster. See link:{base-url}{service-binding-url}#proc-installing-service-binding-operator_{context}[Installing the Service Binding Operator on OpenShift].
* The RHOAS Operator is installed on your OpenShift cluster and you've verified connection to the cluster. See link:{base-url}{service-binding-url}#proc-verifying-connection-to-openshift-cluster_{context}[Verifying connection to your OpenShift cluster].
* You've connected a Kafka and {registry} instance to a project in your OpenShift cluster. See link:{base-url}{service-binding-url}#proc-connecting-kafka-registry-instance-to-openshift-cluster_{context}[Connecting a Kafka or {registry} instance to your OpenShift cluster].
