[id='con-reducing-consumer-lag_{context}']
= Consumer lag indicators
:imagesdir: ../_images

[role="_abstract"]
Consumer lag for a given consumer group indicates the delay between the last message added in a partition and the message currently being picked up by that consumer.
The lag reflects the position of the consumer offset in relation to the end of the partition log.

When you're reviewing consumer group properties in the {product} web console, look for the differences between *Current offset* and *Log end offset*.
The difference shows as the *Offset lag* value.

For applications that rely on the processing of (near) real-time data, it’s critical that consumer lag doesn't become too big.
Suppose a topic streams 100 messages per second.
A lag of 1000 messages between the producer offset (the topic partition head) and the last (current) offset that the consumer has read means a 10-second delay.
The offset lag shows that a gap is opening up between the write and read positions.

To reduce lag, you typically add new consumers to a group.
However, you can also increase the retention time for a message to remain in a topic.
Extending the retention of data in the log gives the consumer a chance to catch up before data is flushed from the message log.

For more information about increasing topic retention time, see {base-url}{topic-config-url}[_Configuring topics in {product}_^].

[role="_additional-resources"]
.Additional resources
* {base-url}{consumer-config-url}#ref-supported-consumer-group-properties_configuring-consumer-groups[_Consumer group properties presented in {product}_]
* {base-url}{rhoas-cli-url}[_Getting started with the `rhoas` CLI_^]
* {base-url}{topic-config-url}[_Configuring topics in {product}_^]

////
[id="proc-resetting-consumer-group-offset_{context}"]
= Resetting consumer group offset positions

[role="_abstract"]
Use the {product} web console to select consumer groups and reset partition offsets for a particular topic.
A reset changes the offset position from which consumers read from the message log of a topic partition.
To reset an offset position, the consumer group must have _NO MEMBERS_ connected to a topic.

Choose one of the following options for the reset:

* *Earliest* resets to the earliest offset at the start of the message log.
* *Latest* resets to the latest offset at the end of the message log.
* *Custom offset* resets to a specific offset in the message log.

[WARNING]
====
By resetting the offset position you risk clients skipping or duplicating messages.
====

As an alternative to using the {product} web console, you can use the `rhoas` command-line interface (CLI) to reset consumer group offsets, as shown in the following example command:

.Example CLI command to reset offsets for consumer groups
[source]
----
rhoas kafka consumer-group reset my-consumer-group --to-earliest
----

For a list of topic properties that you can update using the CLI, see the `rhoas kafka topic update` entry in the {base-url-cli}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^].

If you're using Kafka bin scripts, you can use the `kafka-consumer-groups.sh` tool to reset offsets:
[source,subs="+quotes,+attributes"]
----
bin/kafka-consumer-groups.sh --bootstrap-server __<bootstrap_server>__ --reset-offsets --group my-consumer-group --topic topic1 --to-latest
----

You can specify the reset for `--all-topics` or a single specified `--topic`.

The `<bootstrap_server>` is the bootstrap server endpoint for your service account.
You copy this information for the Kafka instance in the {product} web console by selecting the options menu (three vertical dots) and clicking *View connection information*.

.Prerequisites
* You're logged in to the {product} web console.
* The consumer group you select must have no active members connected to the topic.
* Consumers in the consumer group must be shut down (not consuming partitions).

.Procedure
. In the {product} web console, go to *Streams for Apache Kafka* > *Kafka Instances* and click the name of the Kafka instance that contains the consumer group you're updating.
+
Alternatively, select a consumer group for a specific topic.
+
--
.. In the {product} web console, go to *Streams for Apache Kafka* > *Kafka Instances* and click the name of the Kafka instance that contains the topic.
.. In the *Topics* page, click the name of the topic.
--
. In the *Consumer groups* page, select the options icon (three vertical dots) for the relevant consumer group and click *Reset Offset*.
. Select a topic.
. Choose a new offset position from *Latest*, *Earliest*, or *Custom offset*.
. Select one or more partitions to apply the offset reset.
. If you chose a custom reset, enter the new offset number for the reset.
. Click *Reset offset* to finish.

[role="_additional-resources"]
.Additional resources
* {base-url}{rhoas-cli-url}[_Getting started with the `rhoas` CLI_^]
* {base-url-cli}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
////

////
[id="proc-deleting-consumer-groups_{context}"]
= Deleting a consumer group

[role="_abstract"]
Use the {product} web console to delete consumer groups.
The consumer group must have no active members connected to a topic.
By deleting the consumer group, you remove the current state associated with the group.

As an alternative to using the {product} web console, you can use the `rhoas` command-line interface (CLI) to delete consumer groups, as shown in the following example command:

.Example CLI command to delete a consumer group
[source]
----
rrhoas kafka consumer-group delete my-consumer-group
----

For a list of topic properties that you can update using the CLI, see the `rhoas kafka topic update` entry in the {base-url-cli}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^].

If you're using Kafka bin scripts, you can use the `kafka-consumer-groups.sh` tool to delete consumer groups:
[source,subs="+quotes,+attributes"]
----
bin/kafka-consumer-groups.sh --bootstrap-server __<bootstrap_server>__ --delete --group my-consumer-group
----

The `<bootstrap_server>` is the bootstrap server endpoint for your service account.
You copy this information for the Kafka instance in the {product} web console by selecting the options menu (three vertical dots) and clicking *View connection information*.

.Prerequisites
* You're logged in to the {product} web console.
* The consumer group you select must have no active members.
* Consumers in the consumer group must be shut down (not consuming partitions).

.Procedure
. In the {product} web console, go to *Streams for Apache Kafka* > *Kafka Instances* and click the name of the Kafka instance that contains the consumer group you're updating.
+
Alternatively, select a consumer group for a specific topic.
+
--
.. In the {product} web console, go to *Streams for Apache Kafka* > *Kafka Instances* and click the name of the Kafka instance that contains the topic.
.. In the *Topics* page, click the name of the topic.
--
. In the *Consumer groups* page, select the options icon (three vertical dots) for the relevant consumer group and click *Delete*.
. Confirm the deletion by clicking *Delete*.

[role="_additional-resources"]
.Additional resources
* {base-url}{rhoas-cli-url}[_Getting started with the `rhoas` CLI_^]
* {base-url-cli}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
////

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
