[id='con-binding-quarkus-application-using-cli_{context}']
= Binding a Quarkus application to {product-long-kafka} using the RHOAS CLI
:imagesdir: ../_images

[role="_abstract"]
When the RHOAS Operator is installed on your OpenShift cluster and you have connected a Kafka instance to the cluster, you can use the RHOAS CLI to instruct the Service Binding Operator to automatically inject an application running on the cluster with the parameters required to connect to the Kafka instance. This process is called __service binding__.

The following tutorial shows how to use the RHOAS CLI to perform service binding. In the tutorial, you create an example Quarkus application and connect this to a Kafka instance. link:https://quarkus.io/[Quarkus^] is a Kubernetes-native Java framework that is optimized for serverless, cloud, and Kubernetes environments.

When you perform service binding, the Service Binding Operator automatically injects connection parameters as files into the pod for the application. The example Quarkus application in this tutorial uses the `quarkus-kubernetes-service-binding` link:https://quarkus.io/guides/deploying-to-kubernetes#service-binding[extension^]. This means that the application automatically detects and uses the injected connection parameters.

In general, this automatic injection and detection of connection parameters eliminates the need to manually configure an application to connect to a Kafka instance in {product-long-kafka}. This is a particular advantage if you have many applications in your project that you want to connect to a Kafka instance.

== Prerequisites
* The Service Binding Operator is installed on your OpenShift cluster.
* The RHOAS Operator is installed on your OpenShift cluster and you have verified connection to the cluster.
* You have connected a Kafka instance to a project in your OpenShift cluster.
