[id='con-binding-nodejs-application-using-web-console_{context}']
= Binding a Node.js application to {product-long-kafka} using the OpenShift web console
:imagesdir: ../_images

[role="_abstract"]
When the RHOAS Operator is installed on your OpenShift cluster and you have connected a Kafka instance to the cluster, you can use the OpenShift web console to instruct the Service Binding Operator to automatically inject an application running on the cluster with the parameters required to connect to the Kafka instance. This process is called __service binding__.

The following tutorial shows how to use the OpenShift web console to perform service binding. In the tutorial, you create an example Node.js application and connect this to a Kafka instance. link:https://nodejs.org/en/about/[Node.js^] is a server-side JavaScript runtime that's designed to build scalable network applications. Node.js provides an I/O model based on events and non-blocking operations, which enables efficient applications.

When you perform service binding, the Service Binding Operator automatically injects connection parameters as files into the pod for the application. The example Node.js application in this tutorial uses the `kube-service-bindings` link:https://www.npmjs.com/package/kube-service-bindings[package^]. This means that the application automatically detects the injected connection parameters and converts the information into the format used by two popular Node.js clients; link:https://kafka.js.org/[KafkaJS^] and link:https://github.com/blizzard/node-rdkafka[node-rdkafka^].

In general, this automatic injection and detection of connection parameters eliminates the need to manually configure an application to connect to a Kafka instance in {product-long-kafka}. This is a particular advantage if you have many applications in your project that you want to connect to a Kafka instance.

== Prerequisites
* Your OpenShift cluster is running on OpenShift 4.8 or later.
* The Service Binding Operator is installed on your OpenShift cluster.
* The RHOAS Operator is installed on your OpenShift cluster and you have verified connection to the cluster.
* You have connected a Kafka instance to a project in your OpenShift cluster.
