[id='proc-producing-messages-kafkacat_{context}']
= Producing messages in Kafkacat
:imagesdir: ../_images

You can use Kafkacat to produce messages to Kafka topics in several ways, such as reading them from standard input (`stdin`) directly on the command line or from a file. This example produces messages from input on the command line. For more examples of Kafkacat producer messaging, see the https://github.com/edenhill/kafkacat#examples[Examples^] in the Kafkacat documentation.

.Prerequisites
* Kafkacat is installed.
* You have a running Kafka instance in {product}.
* You've set the Kafka bootstrap server endpoint and your service account credentials as environment variables.

.Procedure
. On the command line, enter the following commands to start Kafkacat in _producer_ mode. This mode enables you to produce messages to your Kafka topic.
+
--
This example uses the SASL/PLAIN authentication mechanism with the server and credential environment variables that you set previously. This example produces messages to a topic in {product} named `my-first-kafka-topic`. Replace the topic name with the relevant topic as needed. The topic that you use in this command must already exist in {product}.

.Starting Kafkacat in producer mode
[source]
----
$ kafkacat -t my-first-kafka-topic -b "$BOOTSTRAP_SERVER" \
 -X security.protocol=SASL_SSL -X sasl.mechanisms=PLAIN \
 -X sasl.username="$USER" \
 -X sasl.password="$PASSWORD" -P
----

NOTE: {product} also supports the SASL/OAUTHBEARER mechanism for authentication, which is the recommended authentication mechanism to use. However, Kafkacat does not yet fully support OAUTHBEARER, so this example uses SASL/PLAIN.

--
. With Kafkacat running in producer mode, enter messages into Kafkacat that you want to produce to the Kafka topic.
+
.Example messages to produce to the Kafka topic
[source]
----
First message
Second message
Third message
----
. Keep this producer running to use later when you create a consumer.

.Verification
ifdef::qs[]
* Is your producer still running without any errors in the terminal?
endif::[]
ifndef::qs[]
* Verify that your producer is still running without any errors in the terminal.
endif::[]
