[id='proc-installing-kafkacat_{context}']
= Installing and verifying Kafkacat
:imagesdir: ../_images

https://github.com/edenhill/kafkacat[Kafkacat^] is a command-line utility for messaging in Apache Kafka 0.8 and later. You can install and use Kafkacat to test and debug your Kafka instances in {product}. With Kafkacat, you can produce and consume messages for your Kafka instances directly from the command line, and list topic and partition information for your Kafka instances.

ifndef::community[]
NOTE: Kafkacat is an open source community tool. Kafkacat is not a part of {product} and is therefore not supported by Red Hat.
endif::[]

.Procedure
. In a web browser, go to the https://github.com/edenhill/kafkacat[Kafkacat^] repository in GitHub and follow the installation instructions for your operating system.
. Verify that the expected version was installed:
+
.Verifying Kafkacat installation
[source]
----
$ kafkacat -V

kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2019, Magnus Edenhill
Version 1.6.0 (JSON, Avro, Transactions, librdkafka 1.6.1 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer)
----

ifdef::qs[]
.Verification
* Was Kafkacat installed successfully?
endif::[]
