[id='proc-user-account-access_{context}']
= Allowing users to view other user accounts
:imagesdir: ../_images

[role="_abstract"]
As an organization administrator, you can use Role-Based Access Control (RBAC) in the {org-name} web console to allow users to view other users in an organization.

You set up access by assigning a predefined role called `User Access principal viewer` to a user group.
By assigning the role, users within the group are able to do the following:

* View and select other users when changing owners and managing access to {registry} instances in the web console
* Specify user names when managing {registry} instances using the `rhoas` CLI for {product-long-registry}

.Prerequisites
* You're logged into the {org-name} web console as an organization administrator.
* A user group contains the users to assign the role to.

NOTE: If you want to add the `User Access principal viewer` role to a single user, create a new group for that user only.

ifndef::community[]
For more information on setting up user access in the web console, see the link:https://access.redhat.com/documentation/en-us/red_hat_hybrid_cloud_console/[_User Access Configuration Guide for Role-based Access Control (RBAC)_^].
endif::[]

.Procedure

. In the upper-right corner of the {registry} web console, select the gear icon, and click *Settings* > *User Access* > *Groups*
. Click the name of the user group.
. From the *Roles* tab, click *Add role* and select `User Access principal viewer` to add the role to the group.
. Click *Add to group* to add the role to the group.
+
The role is added to the list of selected roles on the *Roles* tab.

[role="_additional-resources"]
.Additional resources
* {base-url}{getting-started-url-registry}[_Getting started with {product-long-registry}_^]
* {base-url}{rhoas-cli-getting-started-url-registry}[_Getting started with the rhoas CLI for {product-long-registry}_^]
* {rhoas-cli-base-url}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
* https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/assets-attachments/registry-rest-api.htm[_Apicurio Registry REST API documentation_^]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
