[id='proc-producing-messages-kafka-bin-scripts_{context}']
= Producing messages using Kafka scripts
:imagesdir: ../_images

[role="_abstract"]
In this task, you use the `kafka-console-producer` script to produce messages to a Kafka topic.

.Prerequisites

* You have a running Kafka instance in {product-long-kafka}.
* You have the bootstrap server endpoint for your Kafka instance. To get the server endpoint, select your Kafka instance in the {product-long-kafka} web console, select the options icon (three vertical dots), and click *Connection*.
* You've created the `{property-file-name}` file to store your service account credentials.

.Procedure
. On the command line, navigate to the `bin/` directory of your Kafka distribution.
. Use the `kafka-topics` script to create a Kafka topic, as shown in the following example. The example creates a topic called `my-other-topic` with the default settings. Replace _<bootstrap_server>_ with the bootstrap server endpoint for your own Kafka instance.
+
--
.Using the `kafka-topics` script to create a Kafka topic
[source,subs="+quotes,+attributes"]
----
$ ./kafka-topics.sh --create --topic my-other-topic --partitions 1 --replication-factor 3 --bootstrap-server __<bootstrap_server>__ --command-config ../config/{property-file-name}
----
--
+
ifndef::community[]
NOTE: If you try to create a topic with a number of partitions that would cause the partition limit of the Kafka instance to be exceeded, you see an error message indicating this. For more information about partition limits for Kafka instances, see https://access.redhat.com/articles/5979061[{product-long-kafka} service limits].
endif::[]

. Start the `kafka-console-producer` script, as shown in the following example. The example uses the SASL/PLAIN authentication mechanism with the credentials that you saved in the `{property-file-name}` file. The command prepares a producer to send messages to the `my-other-topic` topic that you previously created.
+
.Starting the `kafka-console-producer` script
+
[source,subs="+quotes,+attributes"]
----
$ ./kafka-console-producer.sh --topic my-other-topic --bootstrap-server "__<bootstrap_server>__" --producer.config ../config/{property-file-name}
----

. With the `kafka-console-producer` script running, enter messages that you want to produce to the Kafka topic.
+
.Example messages to produce to the Kafka topic
+
[source]
----
>First message
>Second message
>Third message
----

. Keep the producer running so that you can use it again later, when you create a consumer.

.Verification
ifdef::qs[]
* Is the `kafka-console-producer` script still running without any errors in the terminal?
endif::[]
ifndef::qs[]
* Verify that the `kafka-console-producer` script is still running without any errors in the terminal.
endif::[]
