[id='proc-creating-service-registry-instance-cli_{context}']
= Creating a {registry} instance
:imagesdir: ../_images

[role="_abstract"]
A {registry} instance serves as a central location for storing artifacts.

.Prerequisites

* You're logged in to `rhoas`.

.Procedure

. Create a {registry} instance with default values.
+
--
This example creates a {registry} instance called `my-registry`.

.Creating a {registry} instance
[source,shell,subs="attributes"]
----
$ rhoas service-registry create --name my-registry
----

The CLI uses service contexts to group service instances against which commands are executed.
The current context is automatically updated so that the created {registry} instance is set as the current instance.

[NOTE]
====
If you do not want to use the default values, enter the following command: `rhoas service-registry create`.
You are prompted to enter the `Name` and optional `Description` for the {registry} instance.
====
--

. Verify that the {registry} instance is ready to use.
+
--
.Reviewing the {registry} instance details
[source,shell]
----
$ rhoas context status service-registry
----

This command shows that the {registry} instance is ready to use,
because the `Status` field is `ready`.

[NOTE]
====
By default, many of the `rhoas` commands provide output in JSON format. You can use the `-o` option to specify a different output format. For more information, see {base-url}{getting-started-rhoas-cli-url-registry}#proc-commands-managing-registry_getting-started-rhoas-service-registry[Commands for managing {registry}].
====
--

