[id='proc-create-connecto_{context}']
= Creating a {product-long-connectors} from Rhoas CLI
:imagesdir: ../_images
[role="_abstract"]
Once you have build a configuration you can create the Connectors instance from the Rhoas CLI.

.Prerequisites
* You have buillt a Connectors configuration and it is saved locally as `connectors.json`.
* You have a {product-long-kafka} instance running and have a topic called `my-topic`.
* You have a service account created that has read and write access to the kafka topic and you have the credentials saved for use.

.Procedure
. Create a evaluation namespace that the connectors instance will use.
+
[source,subs="+quotes"]
----
$ rhoas namespace create
----

. Run the create command and pass in the current configuration.
+
[source,subs="+quotes"]
----
$ rhoas connector create --file=connector.json
----

. You're prompted to enter details to create the {product-connectors} instance.

+
Enter `my-connector` as the connector's name.
+
Select the namespace you created when prompted.
+
If prompted select the kafka instance you created with the topic you want to send messages too.
+
Enter the Service Account Client Id when prompted.
+
Enter the Service Account Client Secret when prompted.

. Once the {product-long-connectors} is running run the following command to see if the connector is producing messages as configured.

[source,subs="+quotes"]
----
$ rhoas kafka topic consume --name=my-topic --partition=0 --wait
----

.Verification
* Is there a connectors instance running called `my-connector`.
* Is there messages being received as expected?

ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed the quick start for creating a connectors instance with the `rhoas` CLI.
====
endif::[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
