[id='proc-create-prices-topic-registry_{context}']
= Creating the quotes Kafka topic in {product-kafka}
:imagesdir: ../_images

[role="_abstract"]
The Quarkus application in this quick start uses a Kafka topic called `quotes` to produce and consume messages. In this task, you'll create the `quotes` topic in your Kafka instance.

.Prerequisites
* You have a running Kafka instance in {product-long-kafka}.

.Procedure
. In the {product-kafka} {service-url-kafka}[web console^], select *Kafka Instances* and then click the name of the Kafka instance that you want to add a topic to.
. Select the *Topics* tab.
. Click *Create topic* and follow the guided steps to define the topic details.
+
--
You must specify the following topic properties:

* *Topic name*: For this quick start, enter `quotes` as the topic name.
* *Partitions*: Set the number of partitions for the topic. For this quick start, set the value to `1`.
* *Message retention*: Set the message retention time and size. For this quick start, set the retention time to `A week` and the retention size to `Unlimited`.
* *Replicas*: For this release of {product-kafka}, the replica values are preconfigured. The number of partition replicas for the topic is set to `3` and the minimum number of follower replicas that must be in sync with a partition leader is set to `2`. For a trial Kafka instance, the number of replicas and the minimum in-sync replica factor are both set to `1`.

After you complete the setup, the new topic appears on the *Topics* page. You can now run the Quarkus application to start producing and consuming messages to and from this topic.
--

.Verification
ifdef::qs[]
* Is the `quotes` topic listed on the *Topics* page?
endif::[]
ifndef::qs[]
* Verify that the `quotes` topic is listed on the *Topics* page.
endif::[]

