[id='proc-viewing-registry-roles_{context}']
= Viewing user roles in a {registry} instance
:imagesdir: ../_images

[role="_abstract"]
You can view the user roles assigned to your {registry} instances that manage how other user accounts or service accounts interact with the instance and the artifacts that it contains. You can view user roles and accounts only for instances that you create or for instances that the owner has assigned you access to.

.Prerequisites
* The {registry} instance has been created and is in *Ready* state.
* The user accounts or service accounts that you want to view have been created in the organization and have already been assigned user roles.

.Procedure
. In the web console, go to *{registry}* > *{registry} Instances* and click the name of the {registry} instance that you want to view roles and accounts for.
. Click the *Access* tab to view the roles and accounts assigned for this instance:
.. To view specific accounts, click *Account*, enter the account name, and click the search button.
.. To view accounts with a specific role, click *Role*, select *Filter by role* and then the role you want (for example, *Administrator*), and click the search button.
. Click *Clear all filters* when done.
