[id='proc-creating-service-account-ansible_{context}']
= Creating a service account
:imagesdir: ../_images

[role="_abstract"]
To connect your applications or services to a Kafka instance in {product-kafka}, you must first create a service account with credentials.

.Prerequisites

* You have an offline token that authenticates the Ansible modules with the {product-long-rhoas} API.
* You have created a Kafka instance.

.Procedure

. To add a module that creates a service account, copy the `create_service_account` module shown in the following example and paste it into the `rhoas_kafka.yml` file.
+
.Example `create_service_account` module
[source,yaml]
----
- name: Create Service Account
    create_service_account:
      name: "service-account-name"
      description: "This is a description of the service account"
      openshift_offline_token: "OPENSHIFT_OFFLINE_TOKEN"
    register:
      srvce_acc_resp_obj
----
. Enter values for the `name`, `short description`, and `openshift_offline_token` fields.
+
When you run the `create_service_account` module as part of the playbook at the end of these steps, Ansible populates the generated service account credentials in the `client_id` and `client_secret` fields in the terminal after it creates the service account.
