[id='proc-deleting-consumer-groups_{context}']
= Deleting a consumer group
:imagesdir: ../_images

[role="_abstract"]
Use the {product-kafka} {service-url-kafka}[web console^] to delete consumer groups.
The consumer group must have no active members connected to a topic.
By deleting the consumer group, you remove the current state associated with the group.

As an alternative to using the {product-kafka} web console, you can use the `rhoas` command-line interface (CLI) to delete consumer groups, as shown in the following example command:

.Example CLI command to delete a consumer group
[source]
----
rhoas kafka consumer-group delete my-consumer-group
----

For a list of topic properties that you can update using the CLI, see the `rhoas kafka topic update` entry in the {base-url-cli}{command-ref-url-cli}[CLI command reference (rhoas)^].

If you're using Kafka scripts, you can use the `kafka-consumer-groups.sh` tool to delete consumer groups:
[source,subs="+quotes,+attributes"]
----
./kafka-consumer-groups.sh --bootstrap-server __<bootstrap_server>__ --command-config __<authentication_properties>__ --delete --group my-consumer-group
----

.Prerequisites
* The consumer group you select must have no active members.
* Consumers in the consumer group must be shut down (not consuming partitions).

.Procedure
. On the {service-url-kafka}[Kafka Instances^] page of the {product-kafka} web console, click the name of the Kafka instance that contains the consumer group you're updating.
+
Alternatively, select a consumer group for a specific topic.
+
--
.. On the {service-url-kafka}[Kafka Instances^] page of the {product-kafka} web console, click the name of the Kafka instance that contains the topic.
.. On the *Topics* page, click the name of the topic.
--
. On the *Consumer groups* page, select the options icon (three vertical dots) for the relevant consumer group and click *Delete*.
. Confirm the deletion by clicking *Delete*.

[role="_additional-resources"]
.Additional resources
* {base-url}{getting-started-rhoas-cli-url-kafka}[Getting started with the rhoas CLI for OpenShift Streams for Apache Kafka^]
* {base-url-cli}{command-ref-url-cli}[CLI command reference (rhoas)^]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
