[id='proc-editing-consumer-group-properties_{context}']
= Reviewing consumer group properties in {product-kafka}
:imagesdir: ../_images

[role="_abstract"]
Use the {product-kafka} {service-url-kafka}[web console^] to select a consumer group and review the consumer properties.
You can examine the consumer groups associated with a Kafka instance or a specific topic of the instance.

As an alternative to using the {product-kafka} web console, you can use the `rhoas` command-line interface (CLI) to return information about a consumer group, as shown in the following example command:

----
rhoas kafka consumer-group describe [flags]
----

For a list of consumer group commands that you can use with the CLI, see the {base-url-cli}{command-ref-url-cli}[CLI command reference (rhoas)^].

If you're using Kafka scripts, you can use the `kafka-consumer-groups.sh` tool to provide the same information:
[source,subs="+quotes,+attributes"]
----
./kafka-consumer-groups.sh --bootstrap-server __<bootstrap_server>__ --command-config __<authentication_properties>__ --describe --group my-consumer-group
----



.Prerequisites
* You have a running Kafka instance with at least one Kafka topic in {product-kafka} (see {base-url}{getting-started-url-kafka}[Getting started with {product-long-kafka}^]).
* Consumer client applications connected to the Kafka instance have a consumer group ID.

.Procedure
. On the {service-url-kafka}[Kafka Instances^] page of the {product-kafka} web console, click the name of the Kafka instance that contains the consumer groups that you want to review.
. Select the *Consumer groups* page.
. Select the options icon (three vertical dots) for the relevant consumer group and click *View partition offsets*.

NOTE: You can also view consumer groups for a specific topic. In your Kafka instance, select the *Topics* page and then click the name of a topic. Select the *Consumer groups* page. For a given consumer group, select the options icon (three vertical dots) and click *View partition offsets*.


[role="_additional-resources"]
.Additional resources
* {base-url}{getting-started-rhoas-cli-url-kafka}[Getting started with the rhoas CLI for OpenShift Streams for Apache Kafka^]
* {base-url-cli}{command-ref-url-cli}[CLI command reference (rhoas)^]
