[id='proc-verifying-connection-to-openshift-cluster_{context}']
= Verifying connection to your OpenShift cluster
:imagesdir: ../_images

[role="_abstract"]
After you install the RHOAS Operator, you can verify that the Operator is working by using the RHOAS CLI to connect to your OpenShift cluster and retrieve the cluster status. The following example shows how to verify connection to your OpenShift cluster.

.Prerequisites
* The RHOAS Operator is installed on your OpenShift cluster.
* You can access your OpenShift cluster with privileges to create a new project.
* You have installed the OpenShift CLI.
* You have installed the latest version of the RHOAS CLI.

.Procedure
. On your computer, open a command-line window.
. Log in to the OpenShift CLI using a token.
.. Log in to the OpenShift web console as a user who has privileges to create a new project in the cluster.
.. In the upper-right corner of the console, click your user name. Select *Copy login command*.
+
A new page opens.
.. Click the *Display Token* link.
.. In the section entitled *Log in with this token*, copy the full `oc login` command shown.
.. On the command line, paste the login command you copied. Right-click on the command line and select *Paste*.
+
You see output confirming that you are logged in to your OpenShift cluster and the current project that you are using.

. On the command line, use the OpenShift CLI to create a new project, as shown in the following example:
+
.Example OpenShift CLI command to create new project
[source, subs="+quotes"]
----
$ oc new-project my-project
----

. Log in to the RHOAS CLI.
+
.RHOAS CLI login command
[source]
----
$ rhoas login
----
+
The login command opens a sign-in process in your web browser.

. On the command line, use the RHOAS CLI to connect to your OpenShift cluster and retrieve the cluster status.
+
.RHOAS CLI command to retrieve status of OpenShift cluster
[source]
----
$ rhoas cluster status
Namespace: my-project
RHOAS Operator: Installed
----
+
As shown in the output, the RHOAS CLI indicates that the RHOAS Operator was successfully installed. The CLI also retrieves the name of the current OpenShift project (namespace).
