[id='task-3_{context}']
= Produce messages
:imagesdir: _images
The Kafka Bin Scripts contain a script to easily produce message to Apache Kafka from the console/command line/terminal.
To prdouce messages from the console/terminal, you simply need to run the `kafka-console-producer` script.

In the previous task, you've created a configuration file with the credentials to connect to your Kafka instance. We will use this configuration file to connect the `kafka-console-producer` to Kafka.

.Prerequisites
* Kafka Bin Scripts available on your system.
* A running {Product_short} Kafka instance.
* The bootstrap server location of your Kafka instance.
* A configuration file containing the authentication information to connect to your Kafka instance.

.Procedure
. Get the Bootstrap Server host and port of your {Product_short} Kafka instance. In the _Getting Started Guide_ we've explained where you can find this information. To quickly recap:
.. Navigate to the {Product} environment.
.. In the Kakfa instance table, click on the kebab/three-dot menu icon of your Kafka and select `Connect to instance`.
.. Copy the _Bootstrap Server_ hostname and port to your clipboard.
. Start the `kafka-console-producer` using the following command, replacing the _BOOTSTRAP_SERVER_ with the value for your Kafka instance.
+
[source,bash]
----
./kafka-console-producer.sh --topic my-other-topic --bootstrap-server "$BOOTSTRAP_SERVER" --producer.config ../config/{Propertyfile_name}
----
+
. If the producer starts correctly, you will see the following prompt.
+
[source,bash]
----
>
----
+
. With `kafka-console-producer` running, you can produce messages by simply typing the message values in your terminal. The following will produce 3 messages to your topic.
+
[source,bash]
----
>First message
>Second message
>Third message
----
+
. Keep the producer running. We will use this producer again in one of the following tasks.

.Verification
. You've a `kafka-console-producer` running without any errors printed to your console.
. No errors were printed to the console when you sent the 3 messages.
