[id='proc-installing-cli_{context}']
= Installing required cli tools
:imagesdir: ../_images

RHOAS operator allow you to represent {product} services as first class citizens in your OpenShift environment.
This enables you to work and integrate with these services using standard OpenShift/Kubernetes features and APIs.

To connect your OpenShift project to your Red Hat OpenShift Application Services, you can use the RHOAS CLI.
In this step we going to install RHOAS and OpenShift cli. You can skip this step entirely if you have those CLI
already installed.

.Prerequisites
* You have bash/shell environment that can be used to download and install required tools

.Procedure
. Install oc command line by following https://docs.openshift.com/container-platform/4.7/cli_reference/openshift_cli/getting-started-cli.html#installing-openshift-cli[official guide]
. Install RHOAS CLI by downloading binaries from the latest release https://github.com/redhat-developer/app-services-cli/releases/latest

ifdef::qs[]
.Verification
* Do you see version printed when running `oc version` command in your terminal
* Do you see version printed when running `rhoas version` command in your terminal
endif::[]
