[id='proc-resetting-consumer-group-offset_{context}']
= Resetting consumer group offset positions
:imagesdir: ../_images

[role="_abstract"]
Use the {product} web console to select consumer groups and reset partition offsets for a particular topic.
A reset changes the offset position from which consumers read from the message log of a topic partition.
To reset an offset position, the consumer group must have _NO MEMBERS_ connected to a topic.

Choose one of the following options for the reset:

* *Earliest* resets to the earliest offset at the start of the message log.
* *Latest* resets to the latest offset at the end of the message log.
* *Custom offset* resets to a specific offset in the message log.

[WARNING]
====
By resetting the offset position you risk clients skipping or duplicating messages.
====

As an alternative to using the {product} web console, you can use the `rhoas` command-line interface (CLI) to reset consumer group offsets, as shown in the following example command:

.Example CLI command to reset offsets for consumer groups
[source]
----
rhoas kafka consumer-group reset-offset --id my-consumer-group --offset earliest --topic topic1
----

The `reset-offset` CLI command has an additional reset option. You can use a timestamp value.

[source]
----
rhoas kafka consumer-group reset-offset --id my-consumer-group --offset timestamp --value "2021-06-23T09:07:21-07:00"
----

For a list of topic properties that you can update using the CLI, see the `rhoas kafka topic update` entry in the {base-url-cli}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^].

If you're using Kafka scripts, you can use the `kafka-consumer-groups.sh` tool to reset offsets:
[source,subs="+quotes,+attributes"]
----
./kafka-consumer-groups.sh --bootstrap-server __<bootstrap_server>__ --command-config __<authentication_properties>__ --reset-offsets --group my-consumer-group --topic topic1 --to-latest
----

You can specify the reset for `--all-topics` or a single specified `--topic`.

.Prerequisites
* You're logged in to the {product} web console.
* The consumer group you select must have no active members connected to the topic.
* Consumers in the consumer group must be shut down (not consuming partitions).

.Procedure
. In the {product} web console, go to *Streams for Apache Kafka* > *Kafka Instances* and click the name of the Kafka instance that contains the consumer group you're updating.
+
Alternatively, select a consumer group for a specific topic.
+
--
.. In the {product} web console, go to *Streams for Apache Kafka* > *Kafka Instances* and click the name of the Kafka instance that contains the topic.
.. In the *Topics* page, click the name of the topic.
--
. In the *Consumer groups* page, select the options icon (three vertical dots) for the relevant consumer group and click *Reset Offset*.
. Select a topic.
. Choose a new offset position from *Absolute*, *Latest*, or *Earliest*.
. Select one or more partitions to apply the offset reset.
. If you chose an absolute reset, enter the new custom offset number for the reset.
. Click *Reset offset* to finish.

[role="_additional-resources"]
.Additional resources
* {base-url}{rhoas-cli-kafka-url}[_Getting started with the rhoas CLI for OpenShift Streams for Apache Kafka_^]
* {base-url-cli}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
