[id='proc-configuring-kafka-bin-scripts_{context}']
= Configuring the Kafka scripts to connect to a Kafka instance
:imagesdir: ../_images

[role="_abstract"]
To enable the Kafka scripts to access a Kafka instance, you must configure a connection using the generated credentials for your {product-long-rhoas} service account. In this task, you create a configuration file that specifies these credential values.

.Prerequisites
* You have the generated credentials for your service account. To reset the credentials, use the {service-accounts-url}[Service Accounts^] page.
* You've set permissions for your service account to access resources in the Kafka instance. To verify the current permissions, select your Kafka instance in the {product-long-kafka} web console and click the *Access* tab. To learn more about setting permissions, see {base-url}{access-mgmt-url-kafka}[Managing account access in {product-long-kafka}^].

.Procedure

. In your Kafka distribution, navigate to the `config/` directory.

. Create a file called `{property-file-name}`.

. In the `{property-file-name}` file, set the SASL connection mechanism and the Kafka instance client credentials as shown in the following configuration. Replace the values with your own credential information. {product-kafka}  supports the SASL/OAUTHBEARER mechanism for authentication, which is the recommended authentication mechanism to use.
+
--
.Setting server and credential values
[source,subs="+quotes,attributes"]
----
sasl.mechanism=OAUTHBEARER
security.protocol=SASL_SSL

sasl.oauthbearer.token.endpoint.url= {sso-token-url}

sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
clientId="<client-id>" \
clientSecret="<client-secret>" ;

sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler
----


--
. Save the file. You'll use this file in the next task to connect to your Kafka instance and produce messages.
