[id='proc-consuming-messages-kafkacat_{context}']
= Consuming messages in Kafkacat
:imagesdir: ../_images

You can use Kafkacat to consume messages from Kafka topics. This example consumes the messages that you sent previously with the producer that you created with Kafkacat.

.Prerequisites
* Kafkacat is installed.
* You have a running Kafka instance in {product}.
* You've set the Kafka bootstrap server endpoint and your service account credentials as environment variables.
* You used a producer to produce example messages to a topic.

.Procedure
. On the command line in a separate terminal from your producer, enter the following commands to start Kafkacat in _consumer_ mode. This mode enables you to consume messages from your Kafka topic.
+
--
This example uses the SASL/PLAIN authentication mechanism with the server and credential environment variables that you set previously. This example consumes and displays the messages from the `my-first-kafka-topic` example topic, and states that it reached the end of partition `0` in the topic.

.Starting Kafkacat in consumer mode
[source]
----
$ kafkacat -t my-first-kafka-topic -b "$BOOTSTRAP_SERVER" \
 -X security.protocol=SASL_SSL -X sasl.mechanisms=PLAIN \
 -X sasl.username="$USER" \
 -X sasl.password="$PASSWORD" -C

First message
Second message
Third message
% Reached end of topic my-first-kafka-topic [0] at offset 3
----
--
. If your producer is still running in a separate terminal, continue entering messages in the producer terminal and observe the messages being consumed in the consumer terminal.

.Verification
ifdef::qs[]
* Is your consumer running without any errors in the terminal?
* Did the consumer display the messages from the `my-first-kafka-topic` example topic?
endif::[]
ifndef::qs[]
. Verify that your consumer is running without any errors in the terminal.
. Verify that the consumer displays the messages from the `my-first-kafka-topic` example topic.
endif::[]

ifdef::qs[]
[#conclusion]
Congratulations! You successfully completed the {product} Kafkacat quick start, and are now ready to produce and consume messages in the service.
endif::[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
