[id='proc-uploading-service-registry-artifacts_{context}']
= Uploading {registry} artifacts
:imagesdir: ../_images

[role="_abstract"]
After creating a {registry} instance, you can start uploading {registry} artifacts.
Artifacts might include, for example, schemas that define the structure of Kafka data or OpenAPI documents to define an API.

.Prerequisites

* You've created a {registry} instance, and it has a `ready` status.

[NOTE]
====
You can use `rhoas context set-service-registry` to switch to a specific {registry} instance.

.Selecting a {registry} instance to use
[source,shell]
----
$ rhoas context set-service-registry --name=my-registry
----
====

.Procedure

. Upload a {registry} artifact.
+
--
This example uploads a {registry} artifact called `my-artifact` to the {registry} instance.
The artifact is an Apache Kafka Avro schema in JSON format.

.Uploading an artifact
[source,shell]
----
$ wget https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/docs/resources/avro-userInfo.json
----
--

. Create the {registry} artifact from the Avro schema that you uploaded.
+
.Creating an artifact
[source,shell]
----
$ rhoas service-registry artifact create --type=AVRO --artifact-id=my-artifact avro-userInfo.json
----

. Verify that the artifact was registered.
+
--
This example lists all artifacts belonging to the {registry} instance.

.Listing artifact details for a {registry} instance
[source,shell]
----
$ rhoas service-registry artifact list
----
--

. Check the version information for the artifact.
+
.Checking the version information of an artifact
[source,shell]
----
$ rhoas service-registry artifact versions --artifact-id=my-artifact
----

. Check the metadata information for the artifact.
+
--
.Checking the metadata information of an artifact
[source,shell]
----
$ rhoas service-registry artifact metadata-get --artifact-id=my-artifact
----

[NOTE]
====
You can use additional options, such as `--group`, `--version`, and  `--description`, to modify the metadata of the artifact you're creating.
For more information about any of the options, view the command help `rhoas service-registry artifact metadata-set -h`.
====
--
