[id='proc-configuring-kafka-for-connectors_{context}']
= Verifying that you have the prerequisites for using {product-long-connectors}
:imagesdir: ../_images

[role="_abstract"]
ifdef::qs[]
Before you can use {product-connectors}, you must complete the link:https://console.redhat.com/application-services/learning-resources?quickstart=getting-started[Getting started with {product-long-kafka}] quick start to set up the following components:

* A *Kafka instance* that you can use for {product-connectors}.
* A *Kafka topic* to store messages sent by data sources and make the messages available to data sinks.
* A *service account* that allows you to connect and authenticate your {connectors} instances with your Kafka instance.
* *Access rules* for the service account that defines how your {connectors} instances can access and use the topics in your Kafka instance.
endif::[]
ifndef::qs[]
Before you can use {product-connectors}, you must complete the steps in _{base-url}{getting-started-url-kafka}[Getting started with {product-long-kafka}^]_ to set up the following components:

* A *Kafka instance* that you can use for {product-connectors}.
* A *Kafka topic* to store messages sent by data sources and make the messages available to data sinks.
* A *service account* that allows you to connect and authenticate your {connectors} instances with your Kafka instance.
* *Access rules* for the service account that defines how your {connectors} instances can access and use the topics in your Kafka instance.
endif::[]

ifdef::qs[]
.Procedure
Make sure that you have set up the prerequisite components.

.Verification
* Is the Kafka instance listed in the Kafka instances table and is it in the *Ready* state?
* Did you verify that your service account was successfully created in the *Service Accounts* page?
* Did you save your service account credentials to a secure location?
* Are the permissions for your service account listed in the *Access* page of the Kafka instance?
* Is the Kafka topic that you created for {product-connectors} listed in the topics table of the Kafka instance?

endif::[]

ifndef::qs[]
.Verification
* Verify that the Kafka instance is listed in the Kafka instances table and that the state of the Kafka instance is shown as *Ready*.
* Verify that your service account was successfully created in the *Service Accounts* page.
* Verify that you saved your service account credentials to a secure location.
* Verify that the permissions for your service account are listed in the *Access* page of the Kafka instance.
* Verify that the Kafka topic that you created for {product-connectors} is listed in the Kafka instance's topics table.

endif::[]

