[id='proc-creating-kafka-instance-cli_{context}']
= Creating a Kafka instance
:imagesdir: ../_images

[role="_abstract"]
A Kafka instance includes a Kafka cluster, bootstrap server, and other required configurations for connecting to Kafka producer and consumer services.

.Prerequisites

* You are logged in to `rhoas`.

.Procedure

. Enter the following command to create a Kafka instance with default values.
+
--
This example creates a Kafka instance called `my-kafka`.

.Creating a Kafka instance
[source,shell]
----
$ rhoas kafka create --name my-kafka
----

CLI uses service contexts to group service instances against which commands are executed.
The created Kafka instance is set automatically in the current context.

[NOTE]
====
If you do not want to use the default values,
enter the following command: `rhoas kafka create`.
You will be prompted to enter the `Name`, `Cloud Provider`, and `Cloud Region` for the Kafka instance.
====
--

. Verify that the Kafka instance is ready to use.
+
--
.Reviewing details of a Kafka instance
[source,shell]
----
$ rhoas context status kafka
----


[NOTE]
====
If you have multiple Kafka instances,
you can make the current context switch to a different instance by using the `rhoas context set-kafka` command.
====
--
