[id='proc-viewing-metrics_{context}']
= Viewing metrics for a Kafka instance in {product}
:imagesdir: ../_images

After you create Kafka topics in your Kafka instance, you can start producing and consuming messages using methods such as link:https://kafka.apache.org/downloads[Kafka] scripts, link:https://github.com/edenhill/kcat[Kafkacat], or a link:https://quarkus.io/[Quarkus] application.

After you produce and consume messages in your services, you can return to the Kafka instance in the web console and use the *Dashboard* page to view metrics for the instance and topics. The metrics help you understand the performance and data usage for your Kafka instance and topics.

.Prerequisites
* You've created a Kafka instance and the instance is in *Ready* state.
* You've created topics in your Kafka instance.

.Procedure
* In the *Kafka Instances* page of the web console, click the name of the Kafka instance and select the *Dashboard* tab.
+
--
When you create your Kafka instance and topics, the *Dashboard* page is initially empty. After you start producing and consuming messages in your services, you can return to this page to view related metrics.

NOTE: In some cases, after you start producing and consuming messages, you might need to wait several minutes for the latest metrics to appear. You might also need to wait until your instance and topics contain enough data for metrics to appear.

After your topics contain data, the following metrics are available:

* *Kafka instance metrics*
** *Used disk space*: Used disk space is the amount of disk space used by the Kafka brokers in the instance. This metric enables you to assess available disk space relative to the limit. To reduce used disk space, you can adjust topic retention time or other topic properties as needed.
* *Topic metrics*
** *Total bytes*: Total bytes is the total incoming and outgoing bytes for all topics or for a selected topic in the Kafka instance. This metric enables you to assess data transfer in and out of your Kafka instance. To modify incoming and outgoing bytes, you can adjust topic message size or other topic properties as needed.
--

.Verification
ifdef::qs[]
* Did you note how to navigate to the instance *Dashboard* page to view metrics later?
endif::[]
ifndef::qs[]
* Verify that you know how to navigate to the instance *Dashboard* page to view metrics later.
endif::[]
