[id='proc-creating-service-account-terraform_{context}']
= Creating a service account
:imagesdir: ../_images

[role="_abstract"]
To connect your applications or services to a Kafka instance in {product-kafka}, you must first create a service account with credentials.

.Prerequisites

* You have an offline token that authenticates the Terraform resources with the {product-long-rhoas} API.
* You have created a Kafka instance.

.Procedure

. To create a service account, copy and paste the  `rhoas_service_account` resource shown in the following example into the `main.tf` file. This example uses the `"my-service-account"` identifier and creates a service account called `my-service-account`.
+

.Example `rhoas_service_account` resource
[source]
----
resource "rhoas_service_account" "my-service-account" {
  name        = "my-service-account"
  description = "<description of service account>"
}

output "client_id" {
  value = rhoas_service_account.my-service-account.client_id
}

output "client_secret" {
  value     = rhoas_service_account.my-service-account.client_secret
  sensitive = true
}
----
+
. Save your changes.
. Apply the changes you made to your Terraform provider configuration.
+
[source, shell]
----
$ terraform apply
----
In the terminal, Terraform displays a message that `rhoas_service_account.my-service-account` will be created.
. When you're ready to create your service account, type *yes*. The generated client ID appears in the terminal as an output. The client secret does not appear because it is marked as a sensitive value.
. To verify Terraform successfully created your service account, in your web browser, open the *Service Accounts* page of the {product-kafka} {service-url-kafka}[web console^].
