[id='proc-setting-registry-roles_{context}']
= Assigning user roles in a {registry} instance
:imagesdir: ../_images

[role="_abstract"]
In {product-long-registry}, you can assign user roles for your {registry} instances to manage how other user accounts or service accounts interact with the instance and the artifacts that it contains. You can assign user roles only for instances that you create or for instances that the owner has assigned you access to.

.Prerequisites
* You're logged in to the {registry} web console at {service-url-registry}[^].
* The {registry} instance is created and is in *Ready* state.
* The user accounts or service accounts that you're assigning roles to are created in the organization.

.Procedure
. In the {service-url-registry}[{registry} web console], click the name of the {registry} instance that you want to assign roles for.
. Click the *Access* tab to view the accounts and roles assigned for this instance.
. Click *Grant access* to assign roles to accounts.
. In the *Account* field, select or enter the service account or user account name that you want to assign the role to:
** A service account enables your application or tool to connect securely to your instance.
** A user account enables users in your organization to access instances.
+
NOTE: If you don't see users in the list, ask your organization administrator to grant access to view other user accounts. For more information, see {base-url}{access-mgmt-url-registry}#proc-user-account-access_managing-access-service-registry[Allowing users to view other user accounts].
. Select the *Role* that you want to assign to your account, for example, *Manager* for write access to this instance.
. Click *Save*.
