[id='proc-creating-service-registry-instance-cli_{context}']
= Creating a Service Registry instance
:imagesdir: ../_images

[role="_abstract"]
A Service Registry instance serves as a central location for storing artifacts.

.Prerequisites

* You are logged in to `rhoas`.

.Procedure

. Enter the following command to create a Service Registry instance with default values.
+
--
This example creates a Service Registry instance called `my-registry`.

.Creating a Service Registry instance
[source,shell]
----
$ rhoas service-registry create --name my-registry
Creating Service Registry instance with name: my-registry
✔️ Successfully created Service Registry instance
{
  "browserUrl": "https://console.redhat.com/beta/application-services/service-registry/t/63620903-4a29-4ba4-8229-7ab793bf73f3",
  "created_at": "2021-09-27T15:35:01Z",
  "href": "/api/serviceregistry_mgmt/v1/registries/63620903-4a29-4ba4-8229-7ab793bf73f3",
  "id": "63620903-4a29-4ba4-8229-7ab793bf73f3",
  "instance_type": "eval",
  "kind": "ServiceRegistry",
  "name": "my-registry",
  "owner": "User",
  "status": "accepted",
  "updated_at": "2021-09-27T15:35:01Z"
}
----

[NOTE]
====
If you do not want to use the default values,
enter the following command: `rhoas service-registry create`.
You will be prompted to enter the `Name` for the Service Registry instance.
====
--

. Enter the following command to verify that the Service Registry instance is ready to use.
+
--
This command shows that the Service Registry instance is ready to use,
because the `Status` field is `ready`.

.Reviewing details of a Registry instance
[source,shell]
----
$ rhoas status service-registry

  Service Registry
  -----------------------------------------------------------
  ID:                    63620903-4a29-4ba4-8229-7ab793bf73f3
  Name:                  my-registry
  Status:                ready
  Registry URL:          https://service-registry-service-registry-production.apps.app-sre-prod-04.i5h0.p1.openshiftapps.com/t/63620903-4a29-4ba4-8229-7ab793bf73f3
----

[NOTE]
====
When you created the Service Registry instance, it was set as the current instance automatically.
If you have multiple Service Registry instances,
you can switch to a different instance by using the `rhoas service-registry use` command.
====
--
