[id='proc-creating-kafka-topic-cli_{context}']
= Creating a Kafka topic
:imagesdir: ../_images

[role="_abstract"]
After creating a Kafka instance, you can create Kafka topics to start producing and consuming messages in your services.

.Prerequisites

* You have created a Kafka instance, and it has a `ready` status.

[NOTE]
====
You can use `rhoas kafka use` to switch to a specific Kafka instance.

.Selecting a Kafka instance to use
[source,shell]
----
$ rhoas kafka use --name my-kafka
Kafka instance "my-kafka" has been set as the current instance.
----
====

.Procedure

. Create a Kafka topic with default values.
+
--
This example creates the `my-topic` Kafka topic.

.Creating a Kafka topic with default values
[source,shell]
----
$ rhoas kafka topic create --name my-topic
{
  "config": [
    {
      "key": "retention.ms",
      "value": "-1"
    }
  ],
  "name": "my-topic",
  "partitions": [
    {
      "id": 1,
      "leader": {
        "id": 1
      },
      "replicas": [
        {
          "id": 1
        }
      ]
    }
  ]
}
----

[NOTE]
====
If you do not want to use the default values,
you can specify the number of partitions (`--partitions`) and message retention time (`--retention-ms`).
For more information, use the command help `rhoas kafka topic create -h`.
====
--

. If necessary, you can edit or delete the topic by using the `rhoas kafka topic update` and `rhoas kafka topic delete` commands.
