[id='proc-user-account-access_{context}']
= Allowing users to view other user accounts
:imagesdir: ../_images

[role="_abstract"]
As an organization administrator, you can use Role-Based Access Control (RBAC) to allow users to view other users in an organization.

You set up access by assigning a predefined role called `User Access principal viewer` to a user group.
By assigning the role, users within the group are able to perform the following actions:

* View and select other users when changing owners and managing access to Kafka instances in the {service-url-kafka}[Openshift Streams for Apache Kafka web console].
* Specify user names when using the `rhoas` CLI for {product-long-kafka}.

.Prerequisites
* You're logged into the {cloud-console-url}[Red Hat Hybrid Cloud Console] as an organization administrator.
* A user group contains the users to assign the role to.

NOTE: If you want to add the `User Access principal viewer` role to a single user, create a new group for that user only.

ifndef::community[]
For more information on setting up user access in the Red Hat Hybrid Cloud Console, see the link:https://access.redhat.com/documentation/en-us/red_hat_hybrid_cloud_console/[User Access Configuration Guide for Role-based Access Control (RBAC)^].
endif::[]

.Procedure

. In the toolbar of the {service-url-kafka}[{product-kafka} web console], select the gear icon.
. Click *Identity & Access Management* > *User Access* > *Groups*.
. Click the name of the user group.
. From the *Roles* tab, click *Add role* and select `User Access principal viewer`.
. Click *Add to group*.
+
The role is added to the list of selected roles on the *Roles* tab.

[role="_additional-resources"]
.Additional resources
* {base-url}{getting-started-url-kafka}[Getting started with {product-long-kafka}^]
* {base-url}{getting-started-rhoas-cli-url-kafka}[Getting started with the `rhoas` CLI for {product-long-kafka}^]
* {base-url-cli}{command-ref-url-cli}[CLI command reference (rhoas)^]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
