[id='proc-configuring-quarkus_{context}']
= Configuring your {quarkus} application to connect to a Kafka instance
:imagesdir: ../_images

To enable your Quarkus application to access a Kafka instance, you must configure the connection using the bootstrap server endpoint and the generated credentials for your {product} service account. For Quarkus, you can configure connection information by using the `application.properties` configuration file. This example sets environment variables and then references them in `application.properties`.

For more information about Quarkus configuration options for using Kafka with MicroProfile Reactive Messaging, see https://quarkus.io/guides/kafka[the guide] in the {quarkus} documentation.

.Prerequisites
* You have the bootstrap server endpoint (external server endpoint) and the generated credentials for your service account. You retrieved this information previously for the Kafka instance in {product} by selecting the options menu (three vertical dots), clicking *Connect to instance*, and generating the service account.

.Procedure
. On the command line, enter the following commands to set the Kafka instance bootstrap server and client credentials as environment variables to be used by Quarkus or other applications. Replace the values with your own server and credential information.
+
.Setting environment variables for server and credentials
[source,subs="+quotes"]
----
export BOOTSTRAP_SERVER=__<bootstrap_server>__
export CLIENT_ID=__<client_id>__
export CLIENT_SECRET=__<client_secret>__
export OAUTH_TOKEN_ENDPOINT_URI=__<oauth_token_endpoint_uri>__
----
+
. Review the `src/main/resources/application.properties` file to understand how the environment variables you set in the previous step are used in your application.
