[id='proc-creating-kafka-topic-cli_{context}']
= Creating a Kafka topic
:imagesdir: ../_images

[role="_abstract"]
After creating a Kafka instance, you can create Kafka topics to start producing and consuming messages in your services.

.Prerequisites

* You've created a Kafka instance, and it has a `ready` status.

[NOTE]
====
You can use `rhoas kafka list` and `rhoas context use-kafka` to switch to a specific Kafka instance.

.List Kafka instances
[source,shell]
----
$ rhoas kafka list
----
.Selecting a Kafka instance to use
[source,shell]
----
$ rhoas context use-kafka --name my-kafka
----
====

.Procedure

. Create a Kafka topic with default values.
+
--
This example creates the `my-topic` Kafka topic.

.Creating a Kafka topic with default values
[source,shell]
----
$ rhoas kafka topic create --name my-topic
----

[NOTE]
====
If you do not want to use the default values,
you can specify the number of partitions (`--partitions`) and message retention time (`--retention-ms`).
For more information, use the command help `rhoas kafka topic create -h`.
====
--

. If necessary, you can edit or delete the topic by using the `rhoas kafka topic update` and `rhoas kafka topic delete` commands.
