[id='proc-binding-kafka_{context}']
= Connecting your service with running application
:imagesdir: ../_images

Once application is running we can now connect our service using `rhoas cluster bind` command. This command will let us inject credentials to our application as files. Credentials will be by default injected as volume into our kuberentes deployment. Quarkus Kuberentes Client will detect them and automatically configure our application for us.

Bind command will create following structure in your pod that many frameworks like quarkus can automatically read and autoconfigure your application to connect with the Kafka and other services.

[source]
----
/bindings/yourkafka
├── bootstrapServers
├── password
├── provider
├── saslMechanism
├── securityProtocol
├── type
└── user
----

.Procedure
. Execute
+
[source]
----
rhoas cluster bind
----
+
Command will automatically detect our application and single Kafka service in our namespace and inject connection details to the running application.
. Select application we want to connect with.
. Press enter to select it on the list
. Verify that command finished with **Binding succeeded** message
. Please go back to your app `prices.html` page
. You should see prices changing on the webpage


ifdef::qs[]
.Verification
* Command should end up with **Binding succeeded**
* Can you view `prices.html` page and chaging prices
endif::[]

ifdef::qs[]
[#conclusion]
Congratulations! You successfully completed the {product} Service Discovery quick start, and are now ready to deploy and connect services to your own applications with {product}.
endif::[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
