[id='proc-consume-message_{context}']
= Consuming messages from a {product-kafka} instance
:imagesdir: ../_images
[role="_abstract"]
You can consume your own message from the Cli instead of using an application. This is very useful for testing and debuging your {product-kafka} instance.

.Prerequisites
. You're logged in to the  OpenShift Application Services web console at {service-url-connectors}[^].
. You configured a {product-kafka} instance for connectors as described _Configuring the {product-kafka} instance for use with {product-long-connectors}_.
. You are logged into the Rhoas Cli with your OpenShift Application Services account using `rhoas login`.

.Procedure
. To consume a message to your kafka topic use the following command `rhoas kafka topic consume --name=test-topic`. You will now see all messages you produced to the topic.
. Just like produce set the `--partition` flag to consume from a specific partition. Run `rhoas kafka topic consume --name=test-topic --partition=1`. You will now see all messages you produced to the topic on the *1* partition.

.Verification
* Does running the commands output messages on the correct partitions?

ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed producing and conuming messages in Rhoas Cli for {product-long-kafka} quick start.
====
endif::[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
