[id='proc-creating-service-account-cli_{context}']
= Creating a service account
:imagesdir: ../_images

[role="_abstract"]
To connect your applications or services to a Kafka instance, you must first create a service account with credentials.
The credentials are exported to a file on your computer,
which you can use to authenticate your application with your Kafka instance.

.Prerequisites

* You have created a Kafka instance, and it has a `ready` status.

.Procedure

. Enter the following command to create a service account.
+
--
This example creates a service account and saves the credentials in a JSON file.

.Creating a service account
[source,shell]
----
$ rhoas service-account create --file-format json --short-description="rhoas-service-account"

✔️ Service account created successfully with ID "04ba07d6-b08c-45fb-af53-3522c1b4c32f".
✔️ Credentials saved to /home/developer/my-project/credentials.json
----

Your service account credentials are created and saved to a JSON file.

[NOTE]
====
When creating a service account, you can choose the file format and location to save the credentials.
For more information, see the `rhoas service-account create` command help.
====
--

. To verify your service account credentials,
view the `credentials.json` file that you created.
+
--
.Verifying service account credentials
[source,shell]
----
$ cat credentials.json
{
	"clientID":"srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1",
	"clientSecret":"facf3df1-ab97-2253-aa87-ab97",
        "oauthTokenUrl": "https://identity.api.openshift.com/auth/realms/rhoas/protocol/openid-connect/token"
}
----
You'll use these credentials and the bootstrap server URL to connect your applications and services to your Kafka instance.

--

. Set the permissions for your service account to access the Kafka instance resources.
+
This example allows applications to produce and consume messages from topics starting with a specified prefix that belong to any consumer group.
+
--
.Assigning access permissions to a service account
[source,shell]
----
$ rhoas kafka acl grant-access --consumer --producer \
    --service-account srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1 --topic-prefix myapp  --group all

The following ACL rules are to be created:

  PRINCIPAL (7)                                   PERMISSION         DESCRIPTION
 ----------------------------------------------- ------------------ ---------------------------
  srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1   ALLOW | DESCRIBE   TOPIC starts with "myapp"
  srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1   ALLOW | READ       TOPIC starts with "myapp"
  srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1   ALLOW | READ       GROUP is "*"
  srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1   ALLOW | WRITE      TOPIC starts with "myapp"
  srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1   ALLOW | CREATE     TOPIC starts with "myapp"
  srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1   ALLOW | WRITE      TRANSACTIONAL_ID is "*"
  srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1   ALLOW | DESCRIBE   TRANSACTIONAL_ID is "*"

? Are you sure you want to create the listed ACL rules (y/N)
----

The permissions you assign depend on whether your application produces or consumes messages.
--
