[id='proc-remove-registry-roles_{context}']
= Editing or removing user roles in a {registry} instance
:imagesdir: ../_images

[role="_abstract"]
You can edit or remove the user roles assigned in your {registry} instances that manage how other user accounts or service accounts interact with the instance and the artifacts that it contains. You can edit or remove user roles only for the instances that you create or for instances that the owner has assigned you access to.

.Prerequisites
* The {registry} instance has been created and is in *Ready* state.
* The user accounts or service accounts have been created in the organization and the user roles have already been assigned.

.Procedure
. In the web console, go to *{registry}* > *{registry} Instances* and click the name of the {registry} instance that you want to remove a user role for.
. Click the *Access* tab to view the accounts and roles assigned for this instance.
. Select the options menu (three vertical dots) next to the assigned *Role* name:
.. To change to a different role, click *Edit* and select the new user role, for example, *Viewer* for read-only access to this instance.
.. To remove the currently assigned role, click *Remove* and confirm in the dialog.



[role="_additional-resources"]
.Additional resources
* {base-url}{getting-started-service-registry-url}[_Getting started with {registry-product-long}_^]
* {base-url}{rhoas-cli-service-registry-url}[_Getting started with the rhoas CLI for {registry-product-long}_^]
* {base-url-cli}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
* https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/assets-attachments/registry-rest-api.htm[_Apicurio Registry REST API documentation_^]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
