[id='proc-generating-credentials-for-application-services_{context}']
= Generate credentials for Application Service Instances
:imagesdir: ../_images

Applications make use of service-accounts to authenticate with the Kafka and Service Registry instances. RHOAS CLI can create a service-account and save the credentials as a Kubernetes secret object.

.Procedure

. Create a service account and save the credentials in a Kubernetes secret object.
+
[source,shell]
----
$ rhoas service-account create --file-format secret --output-file ./rhoas-secrets.yaml
----

. Storing the secret object
+
Unlike ConfigMap objects that contain URLs to connect to the instances, Secrets need to be securely stored so that the credentials are not exposed and security is not breached.
+
The generated secret can be stored securely using:

* The `helm-secrets` plug-in
* Encrypting and pushing the secret in Helm chart
* A secret-management solution such as Hashicorp Vault
+
For this example, we will be encrypting the secret values. Run the following commands to obtain the hashed values of credentials.
+
[source,shell]
----
$ echo -n <client-id> | base64
----
+
[source,shell]
----
$ echo -n <client-secret> | base64
----
+
. Copy the obtained base64 values and paste it in the rhoas-secrets.yaml file.
+
+
. Apply the modified secret file.
+
[source,shell]
----
$ oc apply -f “./rhoas-secrets.yaml”
----
+
. Consuming secrets in a Kubernetes Deployment.
+
Secrets should be injected as environment variables in the Deployments.
+
[source,shell]
----
env:
  - name: RHOAS_SERVICE_ACCOUNT_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: service-account-credentials
        key: RHOAS_SERVICE_ACCOUNT_CLIENT_ID
  - name: RHOAS_SERVICE_ACCOUNT_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: service-account-credentials
        key: RHOAS_SERVICE_ACCOUNT_CLIENT_SECRET

----
. Consuming secret in a Helm Chart.
+
Similar to ConfiGmaps, Secrets can be passed to Helm templates. Here too, the Helm chart needs to follow the naming standards set by RHOAS CLI.
+
[source,shell]
----
env:
  - name: RHOAS_SERVICE_ACCOUNT_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name:  {{ .Values.rhoas.secret }}
        key: RHOAS_SERVICE_ACCOUNT_CLIENT_ID
  - name: RHOAS_SERVICE_ACCOUNT_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name:  {{ .Values.rhoas.secret }}
        key: RHOAS_SERVICE_ACCOUNT_CLIENT_SECRET
----
+
Similar to ConfigMaps, the value can be supplied using “--set-string” flag:
+
[source,shell]
----
$ helm install . --generate-name --set-string rhoas.secret=service-account-credentials
----

