[id='proc-creating-service-account_{context}']
= Creating a service account to connect to a Kafka instance in {product-long-kafka}
:imagesdir: ../_images

[role="_abstract"]
To connect your applications or services to a Kafka instance in {product-long-kafka}, you need to create a service account that's associated with the instance. You then need to save the generated service account credentials, the authentication token endpoint, and the bootstrap server endpoint for the instance to a secure location. You'll use these details when you configure an application to connect to the Kafka instance.

.Prerequisites
* You have a running Kafka instance in {product-kafka}.

.Procedure
. On the *Kafka Instances* page of the {product-kafka} {service-url-kafka}[web console^], select the options icon (three vertical dots) for your Kafka instance and click *Connection*.
. On the *Connection* page, copy the *Bootstrap server* endpoint to a secure location. You'll specify this endpoint when configuring a connection to the Kafka instance.
+
ifdef::qs[]
The remainder of this task describes how to create a service account and copy the generated credentials.
If you want to use the credentials of an _existing_ service account, you can skip to the next task.
endif::[]
ifndef::qs[]
The remainder of this section describes how to create a service account and copy the generated credentials.
If you want to use the credentials of an _existing_ service account, you can skip to the next section.
endif::[]

. Open the {service-accounts-url}[Service Accounts^] page in the *Application Services* section of the Red Hat Hybrid Cloud Console.
. Click *Create service account* to set up the account that you'll use to access this Kafka instance.
. Enter a short description such as `my-service-account` and click *Create*.
. Copy the generated *Client ID* and *Client secret* values to a secure location. You'll specify these credentials when configuring a connection to the Kafka instance.
+
IMPORTANT: The generated credentials are displayed only once, so ensure that you've successfully and securely saved the copied credentials before closing the credentials window.

. After you save the generated credentials to a secure location, select the confirmation check box in the credentials window and close the window.
. Under *Authentication method*, copy the SASL/OAUTHBEARER *Token endpoint URL* value to a secure location. This is the endpoint that you'll use with your service account credentials to authenticate the connection to the Kafka instance.
+
NOTE: SASL/PLAIN authentication is also available for tools and libraries that don't support SASL/OAUTHBEARER, but SASL/OAUTHBEARER is recommended whenever possible. With SASL/PLAIN authentication, you use only service account credentials to authenticate the connection to the Kafka instance.

. (Optional) To review, reset, or delete the service account, use the {service-accounts-url}[Service Accounts^] page.

.Verification
ifdef::qs[]
* Did you save the bootstrap server, client credentials, and authentication token endpoint to a secure location?
* Did you verify that your service account was successfully created in the *Service Accounts* page?
endif::[]
ifndef::qs[]
. Verify that the bootstrap server, client credentials, and authentication token endpoint are saved to a secure location.
. Verify that your service account was successfully created on the *Service Accounts* page.
endif::[]
