[id='proc-configuring-nodejs_{context}']
= Configuring the Node.js example application to connect to a Kafka instance
:imagesdir: ../_images

[role="_abstract"]
To enable your Node.js application to access a Kafka instance, you must configure a connection by specifying the following details:

* The bootstrap server endpoint for your Kafka instance
* The generated credentials for your {product-long-kafka} service account
* The Simple Authentication and Security Layer (SASL) mechanism that the client will use to authenticate with the Kafka instance

In this task, you'll create a new configuration file called `rhoas.env`. In the file, you'll set the required bootstrap server and client credentials as environment variables.

.Prerequisites
ifndef::qs[]
* You have the bootstrap server endpoint for your Kafka instance. To get the server endpoint, select your Kafka instance in the {product-kafka} {service-url-kafka}[web console^], select the options icon (three vertical dots), and click *Connection*.
* You have the generated credentials for your service account. To reset the credentials, use the {service-accounts-url}[Service Accounts^] page in the *Application Services* section of the Red Hat Hybrid Cloud Console.
endif::[]

.Procedure

. In your IDE, create a new file. Save the file with the name `rhoas.env`, at the root level of the `reactive-example` directory for the cloned repository.

. In the `rhoas.env` file, set the SASL authentication mechanism and the Kafka instance client credentials as shown in the following configuration. Replace the client ID and client secret values with your own credential information. The configuration uses SASL/OAUTHBEARER authentication, which is the recommended authentication mechanism to use in {product-kafka}.
+
.Setting environment variables in the rhoas.env file
[source,subs="+attributes,+quotes"]
----
KAFKA_HOST=__<bootstrap_server>__
RHOAS_SERVICE_ACCOUNT_CLIENT_ID=__<client_id>__
RHOAS_SERVICE_ACCOUNT_CLIENT_SECRET=__<client_secret>__
KAFKA_SASL_MECHANISM=oauthbearer
RHOAS_TOKEN_ENDPOINT_URL={sso-token-url}
----
ifdef::qs[]
+
The values are described as follows:
+
--
* *bootstrap_server*: The bootstrap server endpoint for your Kafka instance. To access this information for a Kafka instance in {product-kafka}, select the options menu (three vertical dots). Click *Connection*.
* *client_id*: A client credential generated when you create a service account in {product-kafka}. You're prompted to copy and store this credential when you create the service account.
* *client_secret*: A client credential generated when you create a service account in {product-kafka}. You're prompted to copy and store this credential when you create the service account.
--
endif::[]

. Save the `rhoas.env` file.

ifdef::qs[]
.Verification
* Did you set environment variables for the Kafka instance?
endif::[]
