[id='proc-creating-service-registry-account_{context}']
= Creating a service account
:imagesdir: ../_images

[role="_abstract"]
To connect your applications or services to a {registry} instance, you must first create a service account with credentials.
The credentials are exported to a file on your computer,
which you can use to authenticate your application with your {registry} instance.

.Prerequisites

* You've created a {registry} instance, and it has a `ready` status.

.Procedure

. Create a service account.
+
--
This example creates a service account and saves the credentials in a JSON file.

.Creating a service account
[source,shell]
----
$ rhoas service-account create --short-description="rhoas-service-account" --file-format json
----

[NOTE]
====
When creating a service account, you can choose the file format and location to save the credentials.
For more information, see the `rhoas service-account create` command help.
====
--

. To verify your service account credentials,
view the `credentials.json` file that you created.
+
--
.Example `credentials.json` file
[source,json]
----
{
	"clientID":"srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1",
	"clientSecret":"facf3df1-ab97-2253-aa87-ab97",
    "oauthTokenUrl": "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
}
----
You use these credentials and the {registry} URL to connect your applications and services to your {registry} instance.

[NOTE]
====
By connecting your applications to your {registry} instance, you can retrieve artifacts and use them directly in your service.
====
--

. Create a role for the new service account that can read and write artifacts.
+
--
This example creates a role called `manager` for the service account.

.Creating a role for the service account
[source,shell]
----
$ rhoas service-registry role add --role=manager --service-account=srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1
----
--
