[id='proc-downloading-kafka-bin-scripts_{context}']
= Downloading the Kafka bin scripts
:imagesdir: ../_images

The Kafka bin scripts are the binary scripts that are provided in the https://kafka.apache.org/downloads[Apache Kafka distribution^]. When you extract the Apache Kafka distribution, the `bin/` directory (or the `bin\windows\` directory if you're using Windows) of the distribution contains a set of shell scripts that enable you to interact with your Kafka instance. With the bin scripts, you can produce and consume messages, and perform various operations against the Kafka APIs to administer topics, consumer groups, and other resources.

ifndef::community[]
NOTE: The Kafka bin scripts are part of the open source community version of Apache Kafka. The bin scripts are not a part of {product} and are therefore not supported by Red Hat.
endif::[]

.Procedure
. In a web browser, go to the Kafka https://kafka.apache.org/downloads[Download^] page and download the latest binary version of Apache Kafka.
. Extract the downloaded archive and navigate to the `bin/` directory.
+
--
This example extracts the archive and then changes to the `bin/` directory.

.Extracting the Kafka archive and navigating to the `bin/` directory
[source]
----
$ tar -xzf kafka_2.13-2.7.0.tgz
$ cd kafka_2.13-2.7.0/bin
----

The `bin/` directory contains the Kafka bin scripts.
--

. Review the scripts in the `bin/` directory and verify that you have the `kafka-console-producer` and `kafka-console-consumer` scripts.

. Check the version number of the `kafka-console-producer` script to verify that the scripts were downloaded correctly.
+
.Verifying Kafka bin scripts
[source]
----
$ ./kafka-console-producer.sh --version
2.7.0 (Commit:448719dc99a19793)
----

ifdef::qs[]
.Verification
. Were the Kafka bin scripts installed successfully?
endif::qs[]
