[id='proc-generating-credentials_{context}']
= Generating credentials to connect to a Kafka instance in bf2

To connect your applications or services to a Kafka instance in the {product} web console, you must copy and save the bootstrap server location and the generated credentials for the instance. {product-long} uses the SASL/PLAIN authentication mechanism over TLS to provide secure connections between your applications and Kafka instances. When you generate credentials for a Kafka instance, {product} creates a service account that contains the generated user name and password associated with the instance.

.Prerequisites
* You have created a Kafka instance in the {product} web console and the instance is in *Ready* state.

.Procedure
. In the *Streams for Apache Kafka* page of the web console, on the right side of the relevant Kafka instance, select the options icon (three vertical dots) and click *Connect to instance*.
. In the *Connection* page, copy the *External server* address to a secure location. Your application requires this bootstrap server address to connect to the Kafka instance.
. Click *Generate credential* and copy the *Client ID* and *Client secret* to a secure location. Your application requires these credentials to authenticate the connection to the Kafka instance.
+
IMPORTANT: The generated credentials are displayed only one time, so ensure that you have successfully and securely saved the copied credentials before closing the credentials window.

. After you save the generated credentials to a secure location, select the confirmation check box in the credentials window and close the window.
+
You'll use the server and client information that you saved to configure your application to connect to your Kafka instances when you're ready. For example, if you plan to use https://github.com/edenhill/kafkacat[Kafkacat] to interact with your Kafka instance, you'll use this information to set your bootstrap server and client environment variables.

.Verification
ifdef::qs[]
* Did you save the bootstrap server address to a secure location?
* Did you save the client credentials to a secure location?
endif::[]
ifndef::qs[]
. Verify that the bootstrap server address is saved to a secure location.
. Verify that the client credentials are saved to a secure location.
endif::[]
