[id='proc-create-connector-namespace_{context}']
= Creating a namespace to host your {connectors} instances
:imagesdir: ../_images
[role="_abstract"]

A {connectors} namespace hosts your {connectors} instances.

The namespace that you use depends on your OpenShift Dedicated environment.

If you're using the hosted preview environment:: You must create a preview namespace before you can create {connectors} instances. A preview namespace is active for 48 hours.

If you're using a trial cluster in your own OpenShift Dedicated environment:: The namespace is created when you add the {product-connectors} service to your trial cluster, as described in {addon-url-connectors}[Adding the Red Hat OpenShift {connectors} add-on to your OpenShift cluster^]. Your OpenShift Dedicated trial cluster namespace is active for 60 days.

If you're using your own {rosa-name} cluster:: The namespace is created when you add the {product-connectors} service to your cluster, as described in {addon-url-connectors}[Adding the Red Hat OpenShift {connectors} add-on to your OpenShift cluster^]. You can create {connectors} instances depending on your subscription, as described in https://access.redhat.com/articles/6990631[Red Hat OpenShift Connectors Tiers^].

.Prerequisites

* You're logged in to `rhoas`.
+
[source]
----
$ rhoas login
----

.Procedure

. If you're using a trial cluster in your own OpenShift Dedicated environment, skip to Step 2.
+
If you're using the {product-connectors} evaluation site, create an evaluation namespace.
+
[source,subs="+quotes"]
----
$ rhoas connector namespace create --name=eval-namespace
----

. Verify that your namespace is listed.
+
[source,subs="+quotes"]
----
$ rhoas connector namespace list
----
