[id='proc-viewing-registry-roles_{context}']
= Viewing user roles in a {registry} instance
:imagesdir: ../_images

[role="_abstract"]
You can view the user roles assigned to your {registry} instances to manage how other user accounts or service accounts interact with the instance and the artifacts that it contains. You can view user roles and accounts only for instances that you create or for instances that the owner has assigned you access to.

.Prerequisites
* You're logged in to the {registry} web console at {service-url-registry}[^].
* The {registry} instance is created and is in *Ready* state.
* The user accounts or service accounts that you want to view are created in the organization and are assigned user roles.


.Procedure
. In the {service-url-registry}[{registry} web console], click the name of the {registry} instance that you want to view roles and accounts for.
. Click the *Access* tab to view the roles and accounts assigned for this instance:
.. To view specific accounts, click *Account*, enter the user account or service account name, and click the search button.
.. To view accounts with a specific role, click *Role*, click *Filter by role*, and select the role you want (for example, *Administrator*), and then click the search button.
. When you are finished, click *Clear all filters*.
