[id='proc-generating-config-cli_{context}']
= Generating configurations for Quarkus applications
:imagesdir: ../_images

`rhoas generate-config` command generates application configurations that can be used to connect to the services set in context.
The configurations can be saved in yaml, json, env file or as kubernetes secret. Connection configuration consists of credentials and endpoints that will be used by applications to connect to the services.

[role="_abstract"]
For this quick start, you'll use the Quarkus sample code from the {product-kafka} {samples-git-repo}[Guides and Samples^] repository in GitHub.
The quick start will walk you through how you can generate connection configurations for Quarkus applications using a single command.

.Procedure
. On the command line, clone the {product-kafka} {samples-git-repo}[Guides and Samples^] repository from GitHub.
+
.Cloning the guides and samples repository
[source,subs="+attributes"]
----
git clone {samples-git-repo} app-services-guides
----
. In your IDE, open the `code-examples/quarkus-kafka-quickstart` directory from the repository that you cloned.
. Generate the application configurations for the Quarkus application.
+
--
[source,shell]
----
$ rhoas generate-config --type env --output-file .env
----
--
. Create the "prices" Kafka topic.
+
--
[source,shell]
----
$ rhoas kafka topic create --name prices
----
--
. Create ACLs for the service account created using the `rhoas generate-config` command.
+
--
[source,shell]
----
$ rhoas kafka acl grant-access --producer --consumer --service-account <client_id> --topic prices --group all
----
--
. Run the Quarkus application in dev mode.
+
--
[source,shell]
----
./mvnw quarkus:dev
----
--

[role="_abstract"]
The Quarkus application starts producing and consuming messages to and from the "prices" Kafka topic.
After the application is running, in a web browser, go to http://localhost:8080/prices.html[^] and verify that the `Last price` is updated.

If the Quarkus application fails to run, review the error log in the terminal and address any problems. Also, review the steps to ensure that the Quarkus application and Kafka topic are configured correctly.

[role="_additional-resources"]
.Additional resources
* {rhoas-cli-base-url}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
