[id='proc-creating-schema-design_{context}']
= Creating a schema design
:imagesdir: ../_images

[role="_abstract"]
Use the {product-long-api-designer} web console to create an Apache Avro, JSON Schema, or Google Protocol Buffers (Protobuf) event schema.

ifndef::qs[]
.Prerequisites
* You're logged in to the {product-long-api-designer} web console at {service-url-api-designer}[^].
endif::[]

.Procedure
. In the {service-url-api-designer}[{product-long-api-designer} web console^], click *Create design*.
. Complete the form to provide the following details for the new design:
* *Name*: Enter a unique design name, such as `My Schema Design`.
* *Description* _(Optional)_: Enter a short description of the design.
* *Type*: From the list, select *Apache Avro*, or select another schema type.
. Click *Create*. The new schema design opens in the design editor.
. Edit the design source to provide your content.
. _(Optional)_ To see the changes that you made since the last save, click *Actions > Show design changes*.
. _(Optional)_ For Apache Avro or JSON Schema designs, you can click *Actions > Format design content* to insert spaces and tabs that align your design content correctly.
. Click *Save*.
+
The new design is listed on the *API and Schema Designs* page.
You can use the options icon (three vertical dots) to view or edit the design details, edit the design content, export the design to {product-long-registry}, download the design to a file, or delete the design.

.Verification
ifdef::qs[]
* Is the new design listed on the designs page?
* Are the design details correct?
endif::[]
ifndef::qs[]
. Verify that the new design is listed on the designs page.
. Verify that the design details are correct.
endif::[]
