[id='proc-setting-service-account-permissions_{context}']
= Setting permissions for a service account in a Kafka instance in {product}
:imagesdir: ../_images

After you create a service account to connect to a Kafka instance, you must also set the appropriate level of access for that new account in the Access Control List (ACL) of the Kafka instance. {product} uses ACLs provided by Kafka that enable you to manage how other user accounts and service accounts are permitted to interact with the Kafka resources that you create.

.Prerequisites
* You've created a Kafka instance and the instance is in *Ready* state.
* You've created a service account that you want to allow to access the running Kafka instance.

.Procedure
. In the *Kafka Instances* page of the web console, click the name of the Kafka instance that you want the service account to access.
. Click the *Access* tab to view the current ACL for this instance.
. Click *Manage access*, use the *Account* drop-down menu to select the service account that you previously created, and click *Next*.
. Under *Assign Permissions*, use the drop-down menus to set the permissions shown in the following table for this service account. Click *Add* to add each new resource permission.
+
--
These permissions enable applications associated with the service account to create and delete topics in the instance, to produce and consume messages in any topic in the instance, and to use any consumer group and any producer.

.Example ACL permissions for a new service account
[cols="25%,25%,25%,25%"]
|===
h|Resource type
h|Resource identifier and value
h|Access type
h|Operation

|`Topic`
|`Is` = `*`
|`Allow`
|`All`

|`Consumer group`
|`Is` = `*`
|`Allow`
|`Read`

|`Transactional ID`
|`Is` = `*`
|`Allow`
|`All`
|===
--
. After you add these permissions for the service account, click *Save* to finish.

.Verification
ifdef::qs[]
* Are the new permissions for the service account listed in the *Access* page of the Kafka instance?
endif::[]
ifndef::qs[]
* Verify that the new permissions for the service account are listed in the *Access* page of the Kafka instance.

[role="_additional-resources"]
.Additional resources
* link:https://kafka.apache.org/documentation/#security_authz[Authorization and ACLs^] in Kafka documentation
endif::[]
