[id='proc-remove-registry-roles_{context}']
= Editing or removing user roles in a {registry} instance
:imagesdir: ../_images

[role="_abstract"]
You can edit or remove the user roles assigned in your {registry} instances to manage how other user accounts or service accounts interact with the instance and the artifacts that it contains. You can edit or remove user roles only for the instances that you create or for instances that the owner has assigned you access to.

.Prerequisites
* You're logged in to the {registry} web console at {service-url-registry}[^].
* The {registry} instance is created and is in *Ready* state.
* The user accounts or service accounts are created in the organization and the user roles are assigned.

.Procedure
. In the {service-url-registry}[{registry} web console], click the name of the {registry} instance that you want to remove a user role for.
. Click the *Access* tab to view the accounts and roles assigned for this instance.
. Click the options menu (three vertical dots) next to the assigned *Role* name:
.. To change to a different role, click *Edit*, select the new user role, for example, *Viewer* for read-only access, and then click *Save*.
.. To remove the currently assigned role, click *Remove*, and then click *Remove* again to confirm.
