[id='proc-deploying-example-application-in-openshift_{context}']
= Deploying an example application in OpenShift
:imagesdir: ../_images

[role="_abstract"]
In this step of the tutorial, you deploy an example Quarkus application in the OpenShift project that you created earlier in the tutorial.

The Quarkus application generates random numbers between 0 and 100 and produces those numbers to a Kafka topic. Another part of the application consumes the numbers from the Kafka topic. Finally, the application uses __server-sent events__ to expose the numbers as a REST UI. A web page in the application displays the exposed numbers.

The example Quarkus application uses the `quarkus-kubernetes-service-binding` link:https://quarkus.io/guides/deploying-to-kubernetes#service-binding[extension], which means that the application automatically detects and uses the injected connection parameters. This eliminates the need for manual configuration of the application.

.Prerequisites
* You've completed the previous steps in this tutorial:
** xref:proc-verifying-connection-to-openshift-cluster_{context}[]
** xref:proc-connecting-kafka-instance-to-openshift-cluster_{context}[]
* You've privileges to deploy applications in the OpenShift project created earlier in this tutorial.

.Procedure

. If you're not already logged in to the OpenShift CLI, log in using a token, as described earlier in this tutorial. Log in as the same user who created a new project earlier in the tutorial.

. Use the OpenShift CLI to ensure that the current OpenShift project is the one created earlier in this tutorial, as shown in the following example.
+
.Using the OpenShift CLI to specify the current OpenShift project
[source]
----
$ oc project rhoas-quarkus
----

. To deploy the Quarkus application, apply an example application template provided by {product}.
+
.Deploying an example Quarkus application
[source,options="nowrap"]
----
$ oc apply -f https://raw.githubusercontent.com/redhat-developer/app-services-guides/main/code-examples/quarkus-kafka-quickstart/.kubernetes/kubernetes.yml

service/rhoas-quarkus-kafka created
deployment.apps/rhoas-quarkus-kafka created
route.route.openshift.io/rhoas-quarkus-kafka created
----
+
As shown in the output, when you deploy the application, OpenShift creates a service and route for access to the application.

. Get the URL of the route created for the application.
+
.Getting the route details for the Quarkus application
[source,options="nowrap"]
----
$ oc get route

NAME                   HOST/PORT
rhoas-quarkus-kafka    rhoas-quarkus-kafka-jbyrne-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
----

. On the command line, highlight the URL shown under *HOST/PORT*. Right-click and select *Copy*.

. In your web browser, paste the URL for the route. Ensure that the URL includes `http://`.
+
A web page for the Quarkus application opens.

. In your web browser, append `/prices.html` to the URL.
+
A new web page entitled *Last price* opens.  Because you haven't yet connected the Quarkus application to your Kafka instance, the price value appears as `N/A`.
