[id='proc-creating-service-account-cli_{context}']
= Creating a service account
:imagesdir: ../_images

[role="_abstract"]
To connect your applications or services to a Kafka instance, you must first create a service account with credentials.
The credentials are exported to a file on your computer,
which you can use to authenticate your application with your Kafka instance.

.Prerequisites

* You've created a Kafka instance, and it has a `ready` status.

.Procedure

. Create a service account.
+
--
This example creates a service account and saves the credentials in a JSON file.

.Creating a service account
[source,shell]
----
$ rhoas service-account create --file-format json --short-description="rhoas-service-account"
----

[NOTE]
====
When creating a service account, you can choose the file format and location to save the credentials.
For more information, see the `rhoas service-account create` command help.
====
--

. To verify your service account credentials,
view the `credentials.json` file that you created.
+
--
.Example `credentials.json` file
[source,json,subs="+attributes,+quotes"]
----
{
	"clientID":"_<client-id>_",
	"clientSecret":"_<client-secret>_",
    "oauthTokenUrl": "{sso-token-url}"
}
----
You use these credentials and the bootstrap server URL to connect your applications and services to your Kafka instance.
--

. Set the permissions for your service account to access the Kafka instance resources.
+
--
This example allows applications to produce and consume messages from topics starting with a specified prefix that belong to any consumer group. The service account information you input here is the `clientID` value from the previous step.

.Assigning access permissions to a service account
[source,shell,subs="+quotes"]
----
$ rhoas kafka acl grant-access --consumer --producer \
    --service-account _<client-id>_ --topic-prefix myapp  --group all
----

The permissions you assign depend on whether your application produces or consumes messages.
--
