[id='proc-running-quarkus-example-application-for-operator_{context}']
= Starting the Quarkus example application
:imagesdir: ../_images

In this section of the guide we going to deploy Quarkus Example application container image
The Quarkus example application in this quick start will connect with Kafka prices topic and generate random numbers between 0 and 100 and produces it to a Kafka topic. Another part of the application consumes the number from the Kafka topic. Applicalition exposes the number as a REST UI (using Server Sent events).

.Prerequisites
* You've created the `prices` example Kafka topic.

.Procedure
. Execute quarkus application template that will be deployed to your namespace
+
[source]
----
oc apply -f https://raw.githubusercontent.com/redhat-developer/app-services-guides/main/code-examples/quarkus-kafka-quickstart/.kubernetes/kubernetes.yml
----
+
. Fetch route to the application by executing
+
[source]
----
oc get route
----
+
. Open url from **HOST/PORT** section in your default browser
. Verify that you see Quarkus landing page
. If the Quarkus application fails to run, review the error log in the terminal and address any problems. Also review the steps in this quick start to ensure that the Quarkus application and Kafka topic are configured correctly.
. Append `/prices.html` to url to see prices section.
. You should see `N/A` as price as we still did not connected our application to our Kafka instance

ifdef::qs[]
.Verification
* Did the Quarkus example application run without any errors?
* Can you view `prices.html` page
endif::[]
