[id='proc-creating-service-account_{context}']
= Creating a service account to connect to a Kafka instance in {product}
:imagesdir: ../_images

To connect your applications or services to a Kafka instance in the {product} web console, you must create a service account, copy and save the generated credentials, and copy and save the bootstrap server location. {product-long} uses the SASL/OAUTHBEARER authentication mechanism over TLS to provide secure connections between your applications and Kafka instances. SASL/PLAIN authentication is also available for tools and libraries that do not support SASL/OAUTHBEARER, but SASL/OAUTHBEARER is recommended whenever possible. When you generate credentials for a Kafka instance, {product} creates a service account that contains the generated user name and password associated with the instance.

.Prerequisites
* You have created a Kafka instance in the {product} web console and the instance is in *Ready* state.

.Procedure
. In the *Streams for Apache Kafka* page of the web console, on the right side of the relevant Kafka instance, select the options icon (three vertical dots) and click *Connect to instance*.
. In the *Connection* page, copy the *External server* endpoint to a secure location. This is the bootstrap server endpoint that your application requires to connect to the Kafka instance.
. Click *Generate service account* and copy the *Client ID* and *Client secret* to a secure location. Your application requires these credentials to authenticate the connection to the Kafka instance.
+
IMPORTANT: The generated credentials are displayed only one time, so ensure that you have successfully and securely saved the copied credentials before closing the credentials window.

. After you save the generated credentials to a secure location, select the confirmation check box in the credentials window and close the window.
+
You'll use the server and client information that you saved to configure your application to connect to your Kafka instances when you're ready. For example, if you plan to use https://github.com/edenhill/kafkacat[Kafkacat] to interact with your Kafka instance, you'll use this information to set your bootstrap server and client environment variables.

.Verification
ifdef::qs[]
* Did you save the bootstrap server endpoint to a secure location?
* Did you save the client credentials to a secure location?
endif::[]
ifndef::qs[]
. Verify that the bootstrap server endpoint is saved to a secure location.
. Verify that the client credentials are saved to a secure location.
endif::[]
