[id='proc-binding-kafka-instance-to-openshift-application_{context}']
= Binding your Kafka instance to your OpenShift application
:imagesdir: ../_images

In this step of the tutorial, you use the RHOAS CLI to bind your Kafka instance to your OpenShift application. When you perform this binding, the Service Binding Operator injects connection parameters as files into the pod for the application. The Quarkus application automatically detects and uses the connection parameters to bind to the Kafka instance.

.Prerequisites
* The Service Binding Operator is installed on your OpenShift cluster. See xref:proc-installing-service-binding-operator_{context}[].
* You've completed the previous steps in this tutorial:
** xref:proc-verifying-connection-to-openshift-cluster_{context}[]
** xref:proc-connecting-kafka-instance-to-openshift-cluster_{context}[]
** xref:proc-deploying-example-application-in-openshift_{context}[]
** xref:proc-creating-topic-in-kafka-instance_{context}[]
* You understand how the Service Binding Operator injects connection parameters as files into a client application pod. To learn more, see xref:con-about-service-binding_{context}[].

.Procedure
. If you're not already logged in to the OpenShift CLI, log in using a token, as described earlier in this tutorial. Log in as the same user who created a new project earlier in the tutorial.

. If you're not already logged in to the RHOAS CLI, log in as described earlier in the tutorial.

. Use the OpenShift CLI to ensure that the current OpenShift project is the one created earlier in this tutorial, as shown in the following example.
+
.Using the OpenShift CLI to specify the current OpenShift project
[source]
----
$ oc project rhoas-quarkus
----

. Use the RHOAS CLI to instruct the Service Binding Operator to bind your Kafka instance to an application in your OpenShift project.
+
.Using the RHOAS CLI to bind a Kafka instance to an application in OpenShift
[source]
----
$ rhoas cluster bind
----
+
You're prompted to specify the Kafka instance that you want to bind to an application in your OpenShift project.

.  If you have more than one Kafka instance, use the up and down arrows on your keyboard to highlight the instance that you want to bind to an application in OpenShift. Press *Enter*.
+
You're prompted to specify the application that you want to bind your Kafka instance to.

. If you have more than one application in your OpenShift project, use the up and down arrows on your keyboard to highlight the `rhoas-quarkus-kafka` example application. Press *Enter*.

. Type `y` to confirm that you want to continue. Press *Enter*.
+
When binding is complete, you should see output like the following:
+
.Example output from binding a Kafka instance to an application in OpenShift
[source]
----
Using Service Binding Operator to perform binding
Binding my-kafka-instance with rhoas-quarkus-kafka app succeeded
----
+
The output shows that the RHOAS CLI successfully instructed the Service Binding Operator to bind a Kafka instance called `my-kafka-instance` to the example Quarkus application called `rhoas-quarkus-kafka`. The Quarkus application automatically detected the connection parameters injected by the Service Binding Operator and used them to bind with the Kafka instance.
+
When service binding is complete, OpenShift redeploys the Quarkus application. When the application is running again, it starts to use the `prices` Kafka topic that you created in your Kafka instance. One part of the Quarkus application publishes price updates to this topic, while another part of the application consumes the updates.

. To verify that the Quarkus application is using the Kafka topic, reopen the *Last price* web page that you opened earlier in this tutorial.
+
On the *Last price* web page, observe that the price value is continuously updated. The updates show that the Quarkus application is now using the `prices` topic in your Kafka instance to produce and consume messages that correspond to price updates.
