[id='proc-producing-messages-kafkacat_{context}']
= Producing messages in Kcat
:imagesdir: ../_images

[role="_abstract"]
You can use Kcat to produce messages to Kafka topics in several ways, such as reading them from standard input (`stdin`) on the command line, or from a file. In this task, you produce messages from input on the command line. For more examples of Kcat producer messaging, see https://github.com/edenhill/kcat#examples[Examples^] in the Kcat documentation.

.Prerequisites
* Kcat is installed.
* You have a running Kafka instance in {product-long-kafka} (see {base-url}{getting-started-url-kafka}[Getting started with {product-long-kafka}^]).
* You have a topic in your Kafka instance that you can use to produce and consume messages.
* You've set the Kafka bootstrap server endpoint and your service account credentials as environment variables.

.Procedure
. On the command line, enter the following command to start Kcat in producer mode. This mode enables you to produce messages to your Kafka topic. Replace `_<kafka-topic>_` with your own topic name.
+
--
.Starting Kcat in producer mode
[source,subs="+quotes"]
----
$ kcat -t _<kafka-topic>_ -b "$KAFKA_HOST" \
 -X security.protocol=SASL_SSL -X sasl.mechanisms=PLAIN \
 -X sasl.username="$RHOAS_SERVICE_ACCOUNT_CLIENT_ID" \
 -X sasl.password="$RHOAS_SERVICE_ACCOUNT_CLIENT_SECRET" -P
----

NOTE: Kcat does not yet fully support SASL/OAUTHBEARER authentication, which requires you to specify an access token in addition to service account credentials. Therefore, you use SASL/PLAIN authentication to connect to your Kafka instance with just service account credentials.

NOTE: A Kcat producer might behave differently based on the operating system. For example, on Mac operating systems, messages are sent by redirecting them to the Kcat binary in the format `echo "message" | kcat ...`.

--
. With Kcat running in producer mode, enter messages that you want to produce to the Kafka topic, as shown in the following example:
+
[source]
----
First message
Second message
Third message
----
. To finish producing the messages you entered, press `CTRL+D`.
. Keep the producer running so that you can use it again later, when you create a consumer.
+
NOTE: On Mac operating systems, pressing `CTRL+D` produces the messages you entered and then stops the producer. To use the producer again, you must restart it, as shown earlier in this task.

.Verification
ifdef::qs[]
* Is your producer still running without any errors in the terminal?
endif::[]
ifndef::qs[]
* Verify that your producer is still running without any errors in the terminal.
endif::[]
