[id='proc-creating-kafka-instance-cli_{context}']
= Creating a Kafka instance
:imagesdir: ../_images

[role="_abstract"]
A Kafka instance includes a Kafka cluster, bootstrap server, and other required configurations for connecting to Kafka producer and consumer services.

.Prerequisites

* You're logged in to `rhoas`.

.Procedure

. On the command line, create a Kafka instance.
+
--
.Creating a Kafka instance
[source,shell]
----
$ rhoas kafka create
----
--

. Type `my-kafka` for your instance name.
. When prompted to select a cluster, use the arrows on your keyboard to select your OpenShift cluster and press Enter to provision your Kafka instance.
. When prompted to select an instance size, use the arrows on your keyboard to select 1 or 2 streaming units, and press Enter.
+
--
A streaming unit determines the default maximum capacity of a Kafka instance. An instance with a larger size can handle higher loads and process more events, has more storage, and can handle more clients and connections.

The CLI displays information about the created instance including billing model, cloud provider, cluster ID of the cluster the instance is provisioned on, and instance type.

CLI uses service contexts to group service instances against which commands are executed.
The created Kafka instance is set automatically in the current context.

[NOTE]
====
Alternatively, to provision a Kafka instance by specifying the Kafka name and cluster ID, enter the following command: `rhoas kafka create --name my-kafka --cluster-id _<CLUSTER_ID>_`. Replace _<CLUSTER_ID>_ with your cluster ID. Using this command creates an instance with the default value size of 1 streaming unit.
====
--
. Verify the details and `ready` status of a Kafka instance.
+
--
.Verifying the Kafka instance
[source,shell]
----
$ rhoas context status kafka
----
[NOTE]
====
If you have multiple Kafka instances,
you can make the current context switch to a different instance by using the `rhoas context set-kafka` command.
====
--
