[id='proc-creating-kafka-instance-cli_{context}']
= Creating a Kafka instance
:imagesdir: ../_images

[role="_abstract"]
A Kafka instance includes a Kafka cluster, bootstrap server, and other required configurations for connecting to Kafka producer and consumer services.

.Prerequisites

* You are logged in to `rhoas`.

.Procedure

. Enter the following command to create a Kafka instance with default values.
+
--
This example creates a Kafka instance called `my-kafka`.

.Creating a Kafka instance
[source,shell]
----
$ rhoas kafka create --name my-kafka
----

[NOTE]
====
If you do not want to use the default values,
enter the following command: `rhoas kafka create`.
You will be prompted to enter the `Name`, `Cloud Provider`, and `Cloud Region` for the Kafka instance.
====
--

. Verify that the Kafka instance is ready to use.
+
--
.Reviewing details of a Kafka instance
[source,shell]
----
$ rhoas status kafka
----

This command shows that the Kafka instance is ready to use,
because the `Status` field is `ready`.

[NOTE]
====
When you created the Kafka instance, it was set as the current instance automatically.
If you have multiple Kafka instances,
you can switch to a different instance by using the `rhoas kafka use` command.
====
--
