[id='proc-downloading-service-registry-artifacts_{context}']
= Downloading {registry} artifacts
:imagesdir: ../_images

[role="_abstract"]
After you register a {registry} artifact, you can download the artifact to update it.

.Prerequisites

* You've created a {registry} instance with at least one artifact.
* Your {registry} instance is the default instance, as described in {base-url}{getting-started-rhoas-cli-url-registry}#proc-specifying-default-service-registry-instance-cli_getting-started-rhoas-service-registry[Specifying the default {registry} instance].

.Procedure

. Download the artifact in one of the following ways:

** Use the `rhoas service-registry artifact get` command and specify the artifact ID.
+
--
To find the artifact ID, use the `rhoas service-registry artifact list` command.

.Downloading an artifact by using the artifact ID
[source,shell]
----
$ rhoas service-registry artifact get --artifact-id=my-artifact
----
--

** Use the `rhoas service-registry artifact download` command and specify the global ID.
+
--
To find the global ID, see the output of the `rhoas service-registry artifact metadata-get --artifact-id=my-artifact` command.

.Downloading an artifact by using the global ID
[source,shell]
----
$ rhoas service-registry artifact download --global-id=28
----
--

. Verify that the artifact was downloaded.

[NOTE]
====
You can use additional options, such as `--group` and `--instance-id`, to specify the artifact to download.
For more information about any of the options, run the `rhoas service-registry artifact download -h` command and the `rhoas service-registry artifact get -h` command to view the command help.
====
