[id='proc-creating-service-account_{context}']
= Creating a service account to connect to a Kafka instance in {product}
:imagesdir: ../_images

To connect your applications or services to a Kafka instance in the {product} web console, you need to create a service account that's associated with the instance. You also need to save the bootstrap server endpoint for the instance, the generated service account credentials, and the authentication token endpoint to a secure location. You'll use the service account and Kafka instance information later when you configure your application.

.Prerequisites
* You've created a Kafka instance and the instance is in *Ready* state.

.Procedure
. In the *Kafka Instances* page of the web console, for the relevant Kafka instance that you want to connect to, select the options icon (three vertical dots) and click *View connection information*.
. In the *Connection* page, copy the *Bootstrap server* endpoint to a secure location. This is the bootstrap server endpoint that you'll need for connecting to this Kafka instance.
. Click *Create service account* to set up the account that you'll use to access this Kafka instance.
. Enter a unique service account name, such as `my-service-account`, add an optional description, and click *Create*.
. Copy the generated *Client ID* and *Client Secret* to a secure location. These are the credentials that you'll use to connect to this Kafka instance.
+
IMPORTANT: The generated credentials are displayed only one time, so ensure that you've successfully and securely saved the copied credentials before closing the credentials window.

. After you save the generated credentials to a secure location, select the confirmation check box in the credentials window and close the window.
. For the *Authentication method*, copy the SASL/OAUTHBEARER *Token endpoint URL* to a secure location. This is the endpoint that you'll use with your service account credentials to authenticate the connection to this Kafka instance.
+
NOTE: SASL/PLAIN authentication is also available for tools and libraries that don't support SASL/OAUTHBEARER, but SASL/OAUTHBEARER is recommended whenever possible. With SASL/PLAIN authentication, you use only the service account credentials to authenticate the connection to the Kafka instance.

+
You'll use the service account information that you saved to configure your application to connect to your Kafka instances when you're ready. For example, if you plan to use https://github.com/edenhill/kafkacat[Kafkacat^] to interact with your Kafka instance, you'll use this information to set your bootstrap server and client environment variables.
. To review your service account information, reset your credentials, or delete the service account, go to the *Streams for Apache Kafka* > *Service Accounts* page in the web console.

.Verification
ifdef::qs[]
* Did you save the bootstrap server, client credentials, and authentication token endpoint to a secure location?
* Did you verify that your service account was successfully created in the *Streams for Apache Kafka* > *Service Accounts* page?
endif::[]
ifndef::qs[]
. Verify that the bootstrap server, client credentials, and authentication token endpoint are saved to a secure location.
. Verify that your service account was successfully created in the *Streams for Apache Kafka* > *Service Accounts* page.
endif::[]
