[id='proc-creating-service-registry-instance-cli_{context}']
= Creating a {registry} instance
:imagesdir: ../_images

[role="_abstract"]
A {registry} instance serves as a central location for storing artifacts.

.Prerequisites

* You're logged in to `rhoas`.

.Procedure

. Create a {registry} instance with default values.
+
--
This example creates a {registry} instance called `my-registry`.

.Creating a {registry} instance
[source,shell,subs="attributes"]
----
$ rhoas service-registry create --name my-registry
----

[NOTE]
====
If you do not want to use the default values,
enter the following command: `rhoas service-registry create`.
You are prompted to enter the `Name` for the {registry} instance.
====
--

. Verify that the {registry} instance is ready to use.
+
--
.Reviewing details of a {registry} instance
[source,shell]
----
$ rhoas status service-registry
----

This command shows that the {registry} instance is ready to use,
because the `Status` field is `ready`.

[NOTE]
====
When you created the {registry} instance, it was set as the current instance automatically.
If you have multiple {registry} instances,
you can switch to a different instance by using the `rhoas service-registry use` command.
====
--
