[id='proc-creating-service-account_{context}']
= Creating a service account to connect to a Kafka instance in {product}
:imagesdir: ../_images

To connect your applications or services to a Kafka instance in the {product} web console, you need to create a service account, copy and save the generated credentials, and copy and save the bootstrap server endpoint. You'll use the service account information later when you configure your application.

NOTE: {product} uses the SASL/OAUTHBEARER authentication mechanism over TLS to provide secure connections between your applications and Kafka instances. SASL/PLAIN authentication is also available for tools and libraries that do not support SASL/OAUTHBEARER, but SASL/OAUTHBEARER is recommended whenever possible.

.Prerequisites
* You've created a Kafka instance and the instance is in *Ready* state.

.Procedure
. In the *Streams for Apache Kafka* page of the web console, for the relevant Kafka instance that you want to connect to, select the options icon (three vertical dots) and click *View connection information*.
. In the *Connection* page, copy the *Bootstrap server* endpoint to a secure location. This is the bootstrap server endpoint that you'll need for connecting to this Kafka instance.
. Click *Create service account* to generate the credentials that you'll use to connect to this Kafka instance.
. Copy the generated *Client ID* and *Client Secret* to a secure location.
+
IMPORTANT: The generated credentials are displayed only one time, so ensure that you have successfully and securely saved the copied credentials before closing the credentials window.

. After you save the generated credentials to a secure location, select the confirmation check box in the credentials window and close the window.
+
////
//Will need a step about authentication once the UI is finalized. Pasting Jenn C.'s comment from PR for now. (Stetson, 5 Apr 2021)
To use the SASL/OAUTHBEARER authentication method, copy the token endpoint URL to (where? a file? the same secure location as the credentials?). You'll need this to create a secure connection between your applications and your Kafka instance.

Note: The SASL/PLAIN authentication method is available in case your clients or libraries don't support SASL/OAUTHBEARER. In this case, you'll use the credentials you just generated when it's time to connect your applications to your Kafka instance."
////
+
You'll use the server and client information that you saved to configure your application to connect to your Kafka instances when you're ready. For example, if you plan to use https://github.com/edenhill/kafkacat[Kafkacat] to interact with your Kafka instance, you'll use this information to set your bootstrap server and client environment variables.

.Verification
ifdef::qs[]
* Did you save the bootstrap server endpoint to a secure location?
* Did you save the client credentials to a secure location?
endif::[]
ifndef::qs[]
. Verify that the bootstrap server endpoint is saved to a secure location.
. Verify that the client credentials are saved to a secure location.
endif::[]
