[id='proc-using-rhoas-ansible-collection_{context}']
= Using the OpenShift Application Services Ansible collection
:imagesdir: ../_images

[role="_abstract"]
You can create, view, configure, and delete the following {product-long-kafka} resources with the {product-long-rhoas} (RHOAS) collection:

* Kafka instances
* Service accounts
* Kafka topics
* Access Control Lists (ACLs)

.Prerequisites
* You have a Red Hat account.
* You have an offline token used to authenticate the Ansible modules with the {product-long-rhoas} API.

[NOTE]
The offline token is a refresh token with no expiry and can be used by non-interactive processes to provide an access token for OpenShift Application Services to authenticate the user. The token is an OpenShift offline token and you can find it at https://cloud.redhat.com/openshift/token.


.Procedure
. In your IDE, create a new environment variables (`.env`) file.
. In the `.env` file, add the following variables required by the Ansible collection:
+
`API_BASE_HOST`:: This is the base URL for the API. For example, `\https://api.openshift.com`.
`SSO_BASE_HOST`:: This is the base URL for the Red Hat single sign-on (SSO) service. For example, `\https://sso.redhat.com/auth/realms/redhat-external`.
. Save the file in the root directory of the Ansible collection.
+
NOTE: If you do not explicitly define the environment variables, the collection uses the URLs shown in the preceding step.

. You can run a module in a terminal window to perform a single task. For example, the following command shows how to run a module that creates a Kafka instance. Replace _<OFFLINE_TOKEN>_ with your OpenShift offline token.
+
.Example create_kafka module
[source,shell]
----
$ ansible localhost -m rhoas.rhoas.create_kafka -a 'name=unique-kafka-name billing_model=standard cloud_provider=aws plan="developer.x1" region="us-east-1" openshift_offline_token=<OFFLINE_TOKEN>'
----
Ansible runs the `rhoas.rhoas.create_kafka` task in the terminal and creates the instance.
+
You can also create a playbook of sequential tasks and use Ansible to automatically execute those tasks. The steps in the next section show you how to create and run an example playbook.
