[id='proc-creating-acl-permissions-terraform_{context}']
= Creating Access Control List permissions
:imagesdir: ../_images

[role="_abstract"]
After you create a service account to connect to a Kafka instance, you must also set the appropriate level of access for that new account in an Access Control List (ACL) for the Kafka instance.

.Prerequisites

* You have an offline token that authenticates the Terraform resources with the {product-long-rhoas} API.
* You have created a Kafka instance.
* You understand how Access Control Lists (ACLs) enable you to manage how user accounts and service accounts can access the Kafka resources that you create. See {base-url}{access-mgmt-url-kafka}[Managing account access in {product-long-kafka}^].

.Procedure

. To create Access Control List (ACL) permissions with some default values, copy and paste the `rhoas_acl` resource shown in the following example into the `main.tf` file. This example uses the `"acl"` identifier.
+
.Example `ACL binding` resource
[source]
----
resource "rhoas_acl" "acl" {
  kafka_id = rhoas_kafka.my-instance.id
  resource_type = "TOPIC"
  resource_name = "my-topic"
  pattern_type = "LITERAL"
  principal = rhoas_service_account.my-service-account.client_id
  operation_type = "ALL"
  permission_type = "ALLOW"
}

----
. Consider whether you need to specify your own value for any of the fields in the following list. These fields must all have values in an ACL binding resource.

`resource_type`:: The type of resource you grant access to. This example uses `“TOPIC”`.
`resource_name`:: The name of the Kafka resource  you grant access to. This example uses the name that is passed when creating the topic.
`pattern_type`:: The type of pattern of the ACL. This example uses the `LITERAL` pattern type meaning that Kafka will try to match the match the full resource name (the topic) with the resource specified in the ACL.
`principal`:: The user or service account that this binding applies to. This example uses the service account client ID.
`operation_type`:: The type of operation (an action performed on a resource) that is allowed for the given user on this resource.
`permission_type`:: Whether permission is given or taken away.
. Save your changes.
. Apply the changes you made to your Terraform provider configuration.
+
[source, shell]
----
$ terraform apply
----
In the terminal, Terraform displays a message that `rhoas_acl.acl.` will be created.
. When you're ready to set your permissions, type *yes*.
