[id='proc-consuming-messages-kafkacat_{context}']
= Consuming messages in Kcat
:imagesdir: ../_images

[role="_abstract"]
You can also use Kcat to consume messages from Kafka topics. In this task, you use Kcat to consume the messages that you previously produced to your topic.

.Prerequisites
* Kcat is installed.
* You have a running Kafka instance in {product-long-kafka}.
* You used Kcat to produce example messages to a topic in your Kafka instance.

.Procedure
. Open a second terminal window or tab, separate from your producer.
. On the command line, enter the following command to start Kcat in _consumer_ mode. This mode enables you to consume messages from your Kafka topic. Replace `_<kafka-topic>_` with the name of the topic that you previously produced messages to.
+
--
.Starting Kcat in consumer mode
[source,subs="+quotes"]
----
$ kcat -t _<kafka-topic>_ -b "$KAFKA_HOST" \
 -X security.protocol=SASL_SSL -X sasl.mechanisms=PLAIN \
 -X sasl.username="$RHOAS_SERVICE_ACCOUNT_CLIENT_ID" \
 -X sasl.password="$RHOAS_SERVICE_ACCOUNT_CLIENT_SECRET" -C
----

You see output that looks like the following example. The message values are the ones you previously sent using the producer.

[source,subs="+quotes"]
----
First message
Second message
Third message
% Reached end of topic _<kafka-topic>_ [0] at offset 3
----
--
. If your producer is still running in a separate terminal, continue entering messages in the producer terminal and observe the messages being consumed in the consumer terminal.

NOTE: You can also use the {product-kafka} web console to browse messages in the Kafka topic. For more information, see {base-url}{message-browsing-url-kafka}[Browsing messages in the {product-long-kafka} web console^].

.Verification
ifdef::qs[]
* Is your consumer running without any errors in the terminal?
* Did the consumer display the messages from your Kafka topic?
endif::[]
ifndef::qs[]
. Verify that your consumer is running without any errors in the terminal.
. Verify that the consumer displays the messages from your Kafka topic.
endif::[]

ifdef::qs[]
[#conclusion]
====
Congratulations! You successfully completed the {product-kafka} Kcat quick start, and are now ready to produce and consume messages in the service.
====
endif::[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
