[id='proc-connecting-kafka_{context}']
= Connecting Apache Kafka Service to your cluster
:imagesdir: ../_images

Now we can connect one of our services to our cluster.
`rhoas cluster connect` command will let us to connect our Kafka instance to our cluster. If you do not have any Kafka instance you can create new one using `rhoas kafka create` command.

.Procedure
. Execute
+
[source]
----
rhoas cluster connect --ignore-context
----
+
. You will be asked to select the Kafka instance you want to connect.
Select instance and Press **Enter** to continue.
. The CLI will print the **Connection Details** and asks you to confirm.
. Verify if namespace that will be used to create service instance is `rhoas-quarkus`
. Type `y` and press **Enter** to continue.
. You will be asked to provide a token, which again can be retrieved from https://cloud.redhat.com/openshift/token . Navigate to this URL, copy the token to your clipboard, and copy it into your terminal. Press **Enter** to continue.
. You should see the message: **KafkaConnection successfully installed on your cluster.**
. To verify that the connection has been successfully created, execute the following **oc** command: `oc get KafkaConnection`. This should return a **KafkaConnection** with the name of your Kafka instance.

.Verification
ifdef::qs[]
* `oc get KafkaConnection` returned created kafka instance

In case of issues you can remove your KafkaConnection by executing
`oc delete akc name-of-your-kafka` and retry operation
endif::[]
