[id='proc-user-account-access_{context}']
= Allowing users to view other user accounts
:imagesdir: ../_images

[role="_abstract"]
As an organization administrator, you can use Role-Based Access Control (RBAC) in the {org-name} Hybrid Cloud Console  to allow users to view other users in an organization.

You set up access by assigning a predefined role called `User Access principal viewer` to a user group.
By assigning the role, users in the group can do the following tasks:

* View and select other users when changing owners and managing access to {registry} instances in the {registry} web console.
* Specify user names when managing {registry} instances using the `rhoas` CLI for {product-long-registry}.

.Prerequisites
* You're logged in to the {registry} web console at {service-url-registry}[^] as an organization administrator.
* A user group is created that contains the users to assign the role to.

NOTE: If you want to add the `User Access principal viewer` role to a single user, create a new group for that user only.

ifndef::community[]
For more information on setting up user access in the {org-name} Hybrid Cloud Console, see the link:https://access.redhat.com/documentation/en-us/red_hat_hybrid_cloud_console/[_User Access Configuration Guide for Role-based Access Control (RBAC)_^].
endif::[]

.Procedure

. At the top of the {service-url-registry}[{registry} web console], select the gear icon.
. Click *Settings*, then *User Access*, and then *Groups*.
. Click the name of the user group.
. From the *Roles* tab, click *Add role*, and select `User Access principal viewer`.
. Click *Add to group*.
+
The role is also added to the list of selected roles on the *Roles* tab.

[role="_additional-resources"]
.Additional resources
* {base-url}{getting-started-url-registry}[_Getting started with {product-long-registry}_^]
* {base-url}{getting-started-rhoas-cli-url-registry}[_Getting started with the rhoas CLI for {product-long-registry}_^]
* {base-url-cli}{command-ref-url-cli}[_CLI command reference (rhoas)_^]
* https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/assets-attachments/registry-rest-api.htm[_Apicurio Registry REST API documentation_^]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
