[id='proc-configuring-kafka-bin-scripts_{context}']
= Configuring the Kafka scripts to connect to a Kafka instance
:imagesdir: ../_images

[role="_abstract"]
To enable the Kafka scripts to access a Kafka instance, you must configure the connection using the generated credentials for your {product-kafka} service account. For the Kafka scripts, you will create a configuration file that defines these values.

.Prerequisites
ifndef::qs[]
* You have the generated credentials for your service account. To reset the credentials, use the {service-accounts-url}[Service Accounts^] page in the *Application Services* section of the Red Hat Hybrid Cloud Console.
* You've set the permissions for your service account to access the Kafka instance resources. To verify the current permissions, select your Kafka instance in the {product-kafka} web console and use the *Access* page to find your service account permission settings.
endif::[]

.Procedure

. In your Kafka distribution, navigate to the `config/` directory.

. Create a file called `{property-file-name}`.

. In the `{property-file-name}` file, set the SASL connection mechanism and the Kafka instance client credentials. Replace the values with your own credential information.
+
--
ifdef::qs[]
The `<client_id>` and `<client_secret>` are the generated credentials for your service account. You copied this information previously for the Kafka instance in {product-kafka} by selecting the options menu (three vertical dots), clicking *Connection*, and creating the service account.
endif::[]

.Setting server and credential values
[source,subs="+quotes"]
----
sasl.mechanism=PLAIN
security.protocol=SASL_SSL

sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="__<client_id>__" \
  password="__<client_secret>__" ;
----

NOTE: {product-kafka} also supports the SASL/OAUTHBEARER mechanism for authentication, which is the recommended authentication mechanism to use. However, the Kafka scripts do not yet fully support OAUTHBEARER, so this example uses SASL/PLAIN.

--
. Save the file. You'll use this file in the next task to connect to your Kafka instance and produce messages.
