[id='proc-configure-kafka-instance_{context}']
= Configuring the {product-kafka} instance
:imagesdir: ../_images

[role="_abstract"]
After you create a {product-kafka} instance, configure by performing the following tasks:

* Create *Kafka topics* to store messages sent by you and make them available to consumers.

For this example, you create one Kafka topic, named *test-topic* which will be used for all commands in the following examples.

ifdef::qs[]
.Prerequisites
* You've created a {product-kafka} instance and the instance is in the *Ready* state.
endif::[]

.Procedure
. Create a Kafka topic for your kafka instance:
.. In the OpenShift Application Services web console, select *Streams for Apache Kafka* > *Kafka Instances*.
.. Click the name of the {product-kafka} instance that you created.
.. Select the *Topics* tab, and then click *Create topic*.
.. Type a unique name for your topic. For example, type *test-topic* for *Topic Name*.
.. Accept the default settings for message retention, and replicas. But set the partition count to *2*.

ifdef::qs[]
.Verification
* Did you create a topic for the kafka instance?
endif::[]

