[id='proc-setting-permissions_{context}']
= Setting account permissions in a Kafka instance in {product-kafka}
:imagesdir: ../_images

[role="_abstract"]
In {product-long-kafka}, you can create Access Control Lists (ACLs) in your Kafka instances and set permissions for how other user accounts or service accounts can interact with an instance and its resources. You can manage access for only the Kafka instances that you create or for the instances that the owner has enabled you to access and alter.

.Prerequisites
* You've created a Kafka instance and the instance is in the *Ready* state.
* The user account or service account that you're setting permissions for has been created in the organization.

.Procedure
. On the {service-url-kafka}[Kafka Instances^] page of the {product-kafka} web console, click the name of the Kafka instance that you want to set permissions for.
. Click the *Access* tab to view the current ACL permissions for this instance.
. Use this *Access* page to set permissions for a new account, add permissions to an existing account, or delete account permissions in this instance.
+
* To set permissions for a new account in this instance, follow these steps:

.. Click *Manage access*.
.. In the *Account* list, select the new user account or service account that you want to set permissions for. You can also select *All accounts* to set permissions for all user accounts and service accounts in the organization.
+
If you don't see users in the *Account* list, ask your organization administrator to grant access to view other user accounts. For more information, see {base-url}{access-mgmt-url-kafka}#proc-user-account-access_managing-access[Allowing users to view other user accounts].
.. Click *Next*.
+
--
The *Review existing permissions* section lists any permission settings in this instance that are already defined for all accounts in the organization and for the same account that you previously selected, if applicable. You can delete existing permissions now if needed, or you can wait to delete existing permissions later from the main *Access* page.

If you previously selected a specific account, you can delete only permission entries that apply to individual accounts. If you previously selected *All accounts*, you can delete only permission entries that apply to all accounts.
--
.. Under *Assign Permissions*, use the list to select and define the permissions for the specified account or all accounts for a resource type, such as a topic.
+
--
The following permission options are available:

** *Add permission*: Empty permission entry that you must define manually
** *Consume from a topic*: Predefined permission entry for consuming from one or more specified topics
** *Produce to a topic*: Predefined permission entry for producing to one or more specified topics
** *Manage access*: Predefined permission entry for allowing other user accounts or service accounts to access and alter the permissions in the Kafka instance

For example, when you create a new service account, select the *Consume from a topic* and *Produce to a topic* predefined options and set all resource identifiers and values to `Is *`. These permissions enable applications associated with the service account to create and delete topics in the Kafka instance, to produce and consume messages in any topic in the instance, and to use any consumer group and any producer.

These permission settings result in the following ACL permissions for the new service account:

.Example ACL permissions for a new service account
[cols="25%,25%,25%,25%"]
|===
h|Resource type
h|Resource identifier and value
h|Access type
h|Operation

|`Topic`

(For consuming)
|`Is` = `*`
|`Allow`
|`Read`, `Describe`

|`Consumer group`

(For consuming)
|`Is` = `*`
|`Allow`
|`Read`

|`Topic`

(For producing)
|`Is` = `*`
|`Allow`
|`Write`, `Create`, `Describe`
|===

NOTE: Alternatively, you can click *Add permission* to individually create one `Topic` entry and one `Consumer group` entry, both with `Allow` access to `All` operations. This enables both consuming and producing for the topic in a single entry, and enables all permissions for the consumer group in a single entry. But you must configure these entries individually without using the predefined permission options.

--
.. Click *Save* to finish.

* To add permissions to an existing account in this instance, follow these steps:

.. For the account that you want to add permissions to, select the options icon (three vertical dots) for that entry and click *Manage*.
+
--
The *Review existing permissions* section lists any permission settings in this instance that are already defined for all accounts in the organization and for the same account that you previously selected, if applicable. You can delete existing permissions now if needed, or you can wait to delete existing permissions later from the main *Access* page.

If you selected a permission entry that applies to a specific account, you can delete only permission entries that apply to individual accounts. If you selected a permission entry that applies to all accounts, you can delete only permission entries that apply to all accounts.
--
.. Under *Assign Permissions*, use the list to select and define the permissions for the specified account or all accounts for a resource type, such as a topic. You can click *Add permission* to add permissions individually, or you can select from the predefined permission options as described previously.
.. Click *Save* to finish.

* To delete existing account permissions in this instance, use the following options:

 ** Select one or more permission entries, select the options icon (three vertical dots) at the top of the table, and click *Delete selected permissions*.
 ** For the account that you want to delete, select the options icon (three vertical dots) for that entry and click *Delete*.

+
IMPORTANT: If you delete a user account or service account, you must also delete any ACL permissions associated with that account. If you don't delete unused ACL permissions, then a future account with the same ID of a previously deleted account could inherit the ACL permissions and have automatic access to a Kafka instance.


[role="_additional-resources"]
.Additional resources
* link:https://kafka.apache.org/documentation/#security_authz[Authorization and ACLs^] in Kafka documentation
