[id='proc-updating-service-registry-artifacts_{context}']
= Updating {registry} artifacts
:imagesdir: ../_images

[role="_abstract"]
You can update an artifact with content from a file or from standard input.

.Prerequisites

* You've created a {registry} instance with at least one artifact.
* The type of the updated content is compatible with the current artifact type.

.Procedure

. Update a {registry} artifact.
+
--
This example updates a {registry} artifact called `my-artifact` with content from a file in JSON format.

.Updating an artifact from a file
[source,shell]
----
$ rhoas service-registry artifact update --artifact-id=my-artifact my-artifact.json
----

[NOTE]
====
To update the artifact from standard input, use the `rhoas service-registry artifact update --artifact-id=my_artifact` command.

Paste the updated artifact content on the command line, and then press Ctrl+D to save.
====
--

. Verify that the artifact was updated. The updated artifact is saved as a new version.
+
--
.Checking the version number and modified date of an artifact
[source,shell]
----
$ rhoas service-registry artifact metadata-get --artifact-id=my-artifact
----

[NOTE]
====
You can use additional options, such as `--group` and `--version`, to specify the artifact to update.
For more information about any of the options, view the command help `rhoas service-registry artifact update -h`.
====
--
