[id='proc-running-nodejs-example-application_{context}']
= Running the Node.js example application
:imagesdir: ../_images

After you configure your Node.js application to connect to a Kafka instance, and you create the required Kafka topic, you're ready to run the application.

In this task, you'll run the following components of the Node.js application:

* A `producer-backend` component that generates random country names and sends these names to the Kafka topic.
* A `consumer-backend` component that consumes the country names from the Kafka topic.

.Prerequisites
* You've configured the Node.js example application to connect to a Kafka instance.
* You've created the `countries` Kafka topic.

.Procedure
. On the command line, navigate to the `reactive-example` directory of the repository that you cloned.
+
.Navigating to the reactive-example directory
[source]
----
$ cd reactive-example
----

. Navigate to the directory for the consumer component. Use Node Package Manager (npm) to install the dependencies for this component.
+
.Installing dependencies for the consumer component
[source]
----
$ cd consumer-backend
$ npm install
----

. Run the consumer component.
+
.Running the consumer component
[source]
----
$ node consumer.js
----
+
You should see the Node.js application start to run and connect to the Kafka instance. However, because you haven't yet run the producer component, the consumer has no country names to display.
+
If the application fails to run, review the error log in the command-line window and address any problems. Also, review the steps in this quick start to ensure that the application and Kafka topic are configured correctly.

. Open a second command-line window or tab.

. On the second command line, navigate to the `reactive-example` directory of the repository that you cloned.
+
.Navigating to the reactive-example directory
[source]
----
$ cd reactive-example
----

. Navigate to the directory for the producer component. Use Node Package Manager to install the dependencies for this component.
+
.Installing dependencies for the producer component
[source]
----
$ cd producer-backend
$ npm install
----

. Run the producer component.
+
.Running the producer component
[source]
----
$ node producer.js
----
+
You should see output like that shown in the example.
+
.Example output from the producer component
[source]
----
$ node producer.js
Ghana
Réunion
Guatemala
Luxembourg
Mayotte
Syria
United Kingdom
Bolivia
Haiti
----
+
As shown in the example, the producer component starts to run and generate messages that represent country names.

. Switch back to the first command-line window that you opened.
+
You should now see that the consumer component displays the same country names generated by the producer, and in the same order, as shown in the example.
+
.Example output from the consumer component
[source]
----
$ node consumer.js
Ghana
Réunion
Guatemala
Luxembourg
Mayotte
Syria
United Kingdom
Bolivia
Haiti
----
+
The output from both components confirms that they successfully connected to the Kafka instance. The components are using the Kafka topic that you created to produce and consume messages.

. In your IDE, in the `producer-backend` directory of the repository that you cloned, open the `producer.js` file.
+
Observe that the producer component is configured to process environment variables from the `.env` file that you created. The values of these environment variables are the bootstrap server endpoint and client credentials that the component used to connect to the Kafka instance.

. In the `consumer-backend` directory, open the `consumer.js` file.
+
Observe that the consumer component is also configured to process environment variables from the `.env` file that you created.

ifdef::qs[]
.Verification
* Did the producer component run and start generating random country names?
* Did the consumer component run and display the same country names generated by the producer, and in the same order?
endif::[]

ifdef::qs[]
[#conclusion]
Congratulations! You successfully completed the {product} Node.js quick start. You're now ready to use your own Node.js applications with {product}.
endif::[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
