[id='proc-generating-connection-information-quarkus_{context}']
= Generating connection configuration information for a Quarkus application
:imagesdir: ../_images
The following example shows how to connect an example Quarkus application to the service instances defined in a context in {product-long-rhoas}. https://quarkus.io/[Quarkus^] is a Kubernetes-native Java framework that is optimized for serverless, cloud, and Kubernetes environments.

The Quarkus application uses a topic in a Kafka instance to produce and consume a stream of quote values and display these on a web page. The application consists of two components:

* A producer component that periodically produces a new quote value and publishes this to a Kafka topic called `quotes`.
* A consumer component that streams quote values from the Kafka topic. This component also has a minimal front end that uses Server-Sent Events to show the quote values on a web page.

In addition, the producer and consumer components serialize and deserialize Kafka messages using an Avro schema stored in {registry}. Use of the schema ensures that message values conform to a defined format.

.Prerequisites

ifndef::community[]
* You have a Red Hat account.
endif::[]
* You have a service context with a Kafka and {registry} instance. For an example of creating this, see xref:con-about-service-contexts_{context}[Creating new service contexts].
* https://github.com/git-guides/[Git^] is installed.
* You have an IDE such as https://www.jetbrains.com/idea/download/[IntelliJ IDEA^], https://www.eclipse.org/downloads/[Eclipse^], or https://code.visualstudio.com/Download[VSCode^].
* https://adoptopenjdk.net/[OpenJDK^] 11 or later is installed on Linux or MacOS. (The latest LTS version of OpenJDK is recommended.)
* https://maven.apache.org/[Apache Maven^] 3.8.x or later is installed (for Quarkus 2.2.x).


.Procedure

. On the command line, clone the {product-long-rhoas} https://github.com/redhat-developer/app-services-guides[Guides and Samples^] repository from GitHub.
+
[source,shell]
----
$ git clone https://github.com/redhat-developer/app-services-guides app-services-guides
----

. In your IDE, open the `code-examples/quarkus-service-registry-quickstart` directory from the repository that you cloned.
+
You see that the sample Quarkus application has two components - a producer component and a consumer component. The producer component publishes a stream of quote values to a Kafka topic. The consumer component consumes these values and displays them on a web page.

. On the command line, create the `quotes` topic required by the Quarkus application.
+
[source,shell]
----
$ rhoas kafka topic create --name quotes
----

. Ensure that you are using the service context that includes your Kafka and {registry} instances, as shown in the following example:
+
[source,shell]
----
$ rhoas context use --name development-context
----

. In the guides and samples repository that you cloned, navigate to the directory for the Quarkus application.
+
[source,shell]
----
$ cd ~/app-services-guides/code-examples/quarkus-service-registry-quickstart/
----

. Generate an environment variables file that contains the connection configuration information required by the producer component.
+
[source,shell]
----
$ rhoas generate-config --type env --output-file ./producer/.env
----

. Copy the `.env` file to the directory for the consumer component, as shown in the following Linux example:
+
[source,shell]
----
$ cp ./producer/.env ./consumer/.env
----
+
For a service context with single Kafka and {registry} instances, the `.env` file looks like the following example:
+
.Example environment variables file for connection configuration information
[source,shell]
----
## Generated by rhoas cli
## Kafka Configuration
KAFKA_HOST=kafka-inst-cafkr-jma--lhulbl-ca.bf2.kafka.rhcloud.com:443
## Service Registry Configuration
SERVICE_REGISTRY_URL=https://bu98.serviceregistry.rhcloud.com/t/0aa1dd8b-63d5-466c-9de8-7c03320a81c2
SERVICE_REGISTRY_CORE_PATH=/apis/registry/v2
SERVICE_REGISTRY_COMPAT_PATH=/apis/ccompat/v6

## Authentication Configuration
RHOAS_CLIENT_ID=srvc-acct-14295e3c-f72d-4bae-876c-3172a96eb7eb
RHOAS_CLIENT_SECRET=5c3a20e0-d946-4edf-94d2-35db41f3b2ad
RHOAS_OAUTH_TOKEN_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
----
+
As shown in the example, the file that you generate contains the endpoints for your service instances, and the credentials required to connect to those instances. The CLI automatically created a service account (under the environment variable name `RHOAS_CLIENT_ID`) that client applications can use to authenticate with the Kafka and {registry} instances.

. Set Access Control List (ACL) permissions to enable the new service account to access resources in the Kafka instance.
+
.Example command for granting access to Kafka instance
[source,shell]
----
$ rhoas kafka acl grant-access --producer --consumer --service-account srvc-acct-14295e3c-f72d-4bae-876c-3172a96eb7eb --topic quotes --group all
----
+
The command you entered allows applications to use the service account to produce and consume messages in the `quotes` topic. Applications can use any consumer group and producer.

. Use Role-Based Access Control (RBAC) to enable the new service account to access the {registry} instance and the artifacts (such as schemas) that it contains.
+
.Example command for granting access to {registry} instance
[source,shell]
----
$ rhoas service-registry role add --role manager --service-account srvc-acct-14295e3c-f72d-4bae-876c-3172a96eb7eb
----

. In the guides and samples repository, navigate to the directory for the producer component. Use Apache Maven to run the producer component in developer mode.
+
[source,shell,options="nowrap"]
----
$ cd ~/app-services-guides/code-examples/quarkus-service-registry-quickstart/producer
$ mvn quarkus:dev
----
+
The producer component starts to generate quote values to the `quotes` topic in the Kafka instance.
+
The Quarkus application also created an Avro schema called `quotes-value` in the {registry} instance. The producer and consumer components use the schema to ensure that message values conform to a defined format.
+
To view the contents of the `quotes-value` schema, run the following command:
+
[source,shell]
----
$ rhoas service-registry artifact get --artifact-id quotes-value
----
+
You see output that looks like the following example:
+
.Example Avro schema in {registry}
[source,shell]
----
{
  "type": "record",
  "name": "Quote",
  "namespace": "org.acme.kafka.quarkus",
  "fields": [
    {
      "name": "id",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "price",
      "type": "int"
    }
  ]
}
----

. With the producer component still running, open a second command-line window or tab. In the guides and samples repository, navigate to the directory for the consumer component and run the component in developer mode.
+
[source,shell,options="nowrap"]
----
$ cd ~/app-services-guides/code-examples/quarkus-service-registry-quickstart/consumer
$ mvn quarkus:dev
----
+
The consumer component starts to consume the stream of quote values from the `quotes` topic.

. In a web browser, go to  http://localhost:8080/quotes.html[^].
+
You see that the consumer component displays the stream of quote values on the web page. This output shows that the Quarkus application used the connection configuration information that you generated to connect to the Kafka and {registry} instances in your service context.

[role="_additional-resources"]
.Additional resources
* https://access.redhat.com/documentation/en-us/red_hat_openshift_application_services/1/guide/8bd088a6-b7b7-4e5d-832a-b0f0494f9070#_b7f033ec-6f0c-4b3c-89b0-cb1801de19f9[CLI command reference (rhoas)^]
* https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/1/guide/2f4bf7cf-5de2-4254-8274-6bf71673f407[ Managing account access in {product-long-kafka}^]
* https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1/guide/7717db0b-9fad-4fff-91b7-b311b63290a4[Managing account access in {product-long-registry}^]
