[id='proc-binding-quarkus-applcation-to-kafka-instance-using-cli_{context}']
= Binding the Quarkus application to your Kafka instance using the RHOAS CLI
:imagesdir: ../_images

[role="_abstract"]
In this step of the tutorial, you use the RHOAS CLI to bind the example Quarkus application that you deployed on OpenShift to your Kafka instance. When you perform this binding, the Service Binding Operator injects connection parameters as files into the pod for the application. The Quarkus application automatically detects and uses the connection parameters to bind to the Kafka instance.

.Prerequisites
* You understand how the Service Binding Operator injects connection parameters as files into the pod for a client application. See {base-url}{service-binding-url-kafka}#con-about-service-binding_{context}[About service binding].
* The Service Binding Operator is installed on your OpenShift cluster.
* The RHOAS Operator is installed on your OpenShift cluster and you have verified connection to the cluster.
* You have connected a Kafka instance to a project in your OpenShift cluster.
* You have deployed the example Quarkus application.
* You have created the Kafka topic required by the Quarkus application.

.Procedure
. If you are not already logged in to the OpenShift CLI, log in using a token, as described in {base-url}{service-binding-url-kafka}#proc-verifying-connection-to-openshift-cluster_{context}[Verifying connection to your OpenShift cluster]. Log in as the same user who verified connection to the cluster.

. Log in to the RHOAS CLI.
+
.RHOAS CLI login command
[source]
----
$ rhoas login
----

. Use the OpenShift CLI to ensure that the current OpenShift project is the one that you previously connected your Kafka instance to, as shown in the following example:
+
.Example OpenShift CLI command to specify current OpenShift project
[source]
----
$ oc project my-project
----

. Use the RHOAS CLI to instruct the Service Binding Operator to bind your Kafka instance to an application in your OpenShift project.
+
.RHOAS CLI command to bind Kafka instance to application in OpenShift
[source]
----
$ rhoas cluster bind
----
+
You are prompted to specify the Kafka instance that you want to bind to an application in your OpenShift project.

.  If you have more than one Kafka instance, use the up and down arrows on your keyboard to highlight the instance that you want to bind to an application in OpenShift. Press *Enter*.
+
You are prompted to specify the application that you want to bind your Kafka instance to.

. If you have more than one application in your OpenShift project, use the up and down arrows on your keyboard to highlight the `rhoas-quarkus-kafka` example application. Press *Enter*.

. Type `y` to confirm that you want to continue. Press *Enter*.
+
When binding is complete, you should see output like the following:
+
.Example output from binding Kafka instance to application in OpenShift
[source]
----
Using Service Binding Operator to perform binding
Binding my-kafka-instance with rhoas-quarkus-kafka app succeeded
----
+
The output shows that the RHOAS CLI successfully instructed the Service Binding Operator to bind a Kafka instance called `my-kafka-instance` to the example Quarkus application called `rhoas-quarkus-kafka`. The Quarkus application automatically detected the connection parameters injected by the Service Binding Operator and used them to bind with the Kafka instance.
+
When service binding is complete, OpenShift redeploys the Quarkus application. When the application is running again, it starts to use the `prices` Kafka topic that you created in your Kafka instance. One part of the Quarkus application publishes price updates to this topic, while another part of the application consumes the updates.

. To verify that the Quarkus application is using the Kafka topic, reopen the *Last price* web page that you opened earlier in this tutorial.
+
On the *Last price* web page, observe that the price value is continuously updated. The updates show that the Quarkus application is now using the `prices` topic in your Kafka instance to produce and consume messages that correspond to price updates.
+
NOTE: You can also use the {product-long-kafka} web console to browse messages in the Kafka topic. For more information, see {base-url}{message-browsing-url-kafka}[Browsing messages in the {product-long-kafka} web console^].
