[id='proc-running-quarkus-registry-example-app_{context}']
= Running the Quarkus example application
:imagesdir: ../_images

[role="_abstract"]
After you configure your Quarkus application to connect to Kafka and {registry} instances, and you create the Kafka topic, you can run the Quarkus application to start producing and consuming messages to and from this topic.

The Quarkus application in this quick start consists of two processes:

* The consumer process is implemented by the `QuotesResource` class. This class exposes the `/quotes` REST endpoint that streams quotes from the `quotes` topic. This process also has a minimal frontend that streams quotes using Server-Sent Events to the web page.
* The producer process is implemented by the `QuotesProducer` class. This class produces a new quote periodically (every 5 seconds) with a random quote value that is published to the `quotes` topic.

.Prerequisites
* You've configured the Quarkus example application to connect to the Kafka and {registry} instances.
* You've created the Kafka `quotes` topic.
ifndef::qs[]
* You're logged in to the {registry} web console at {registry-url}[^].
endif::[]


.Procedure
. On the command line, change to the `code-examples/quarkus-service-registry-quickstart/consumer` directory that you imported and run the consumer process.
+
.Running the example consumer process
[source]
----
$ cd ~/code-examples/quarkus-service-registry-quickstart/consumer
$ mvn quarkus:dev
----
. After the consumer process is running, in a web browser, go to http://localhost:8080/quotes.html[^] and verify that this process is available.

. Leave the consumer process running, and run the producer process on a different terminal.
+
.Running the example producer process
[source]
----
$ cd ~/code-examples/quarkus-service-registry-quickstart/producer
$ mvn quarkus:dev
----

. When both the consumer and producer processes are running, view the generated quotes in the web browser at http://localhost:8080/quotes.html[^].

. In the web console, go to *{registry}* > *{registry} Instances*,  select your {registry} instance, and view the automatically generated schema for your application.


.What just happened?

* The Quarkus application is configured to use the `io.apicurio.registry.serde.avro.AvroKafkaSerializer` Java class for serializing and the `io.apicurio.registry.serde.avro.AvroKafkaDeserializer` class for deserializing messages to Avro format. This SerDes is configured to use remote schemas in {registry-product-long} rather than the local schemas in the application.

* Because there are no schemas in the {registry} instance, the SerDes published the schema for the `quotes` topic. The name of the schema is managed by the `TopicRecordIdStrategy` class, which uses the `topic_name-value` convention. You can find this schema in the {registry} instance and configure compatability rules to govern how the schema can evolve for future versions.

* If the Quarkus application fails to run, review the error log in the terminal and address any problems. Also review the steps in this quick start to ensure that the Quarkus application and Kafka topic are configured correctly.

ifdef::qs[]
.Verification
* Did the Quarkus example application run without any errors?
* Did you see the generated quotes at http://localhost:8080/quotes.html[^]?
* Did you see generated schemas in the {registry} instance?
endif::[]

ifdef::qs[]
[#conclusion]
Congratulations! You successfully completed the {product} and {registry} Quarkus quick start, and are now ready to use your own Quarkus application with {product} and {registry}.
endif::[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
