[id='proc-using-terraform_{context}']
= Using the {product-long-rhoas} (RHOAS) Terraform provider
:imagesdir: ../_images

Resources are the most important element in the Terraform language. Each resource block in a Terraform provider describes one or more infrastructure objects. For {product-long-kafka}, such infrastructure objects might include Kafka instances, service accounts, Access Control Lists (ACLs), and topics. The procedure that follows shows what resources you can add to your Terraform configuration file to create a Kafka instance and its associated resources such as service accounts and topics.

.Prerequisites

* You have a Red Hat account.
* You have an offline token that authenticates the Terraform resources with the OpenShift Application Services API.

[NOTE]
====
The offline token is a refresh token with no expiry and can be used by non-interactive processes to provide an access token for {product-long-rhoas} to authenticate the user. The token is an OpenShift offline token and you can find it at https://cloud.redhat.com/openshift/token. Because the offline token is a sensitive value that varies between environments it is best specified as an `OFFLINE_TOKEN` environment variable when running `terraform apply` in a terminal. To set this environment variable, enter the following command in a terminal window, replacing _<offline_token>_ with the value of the offline token:
[source, subs="+quotes"]
----
export OFFLINE_TOKEN=<offline_token>
----
====

.Procedure

. Open the `main.tf` file in your IDE for editing.
. Copy the `rhoas_kafka` resource shown in the following example and paste it into the `main.tf` file after the provider configuration. This example uses the `"my-instance"` identifier and creates a Kafka instance called `my-instance`.
+
[NOTE]
In the following examples, the identifier and the name of the infrastructure object are the same for demonstration purposes only. You can choose different values for each field.
+

.Example `rhoas_kafka` resource
[source]
----
resource "rhoas_kafka" "my-instance" {
  name = "my-instance"
  plan = "developer.x1"
  billing_model = "standard"
}
  output "bootstrap_server_my-instance" {
    value = rhoas_kafka.my-instance.bootstrap_server_host
}

----
. Save your changes.
. Open a terminal and apply the changes you made to your Terraform provider configuration.
+
[source, shell]
----
$ terraform apply
----
+
In the terminal, Terraform displays a message that `rhoas_kafka.my-instance` will be created. Terraform automatically sets values for `cloud provider` and `region` in the terminal. All other information for the instance is provided by the Kafka APIs.
. When you're ready to create your instance,  type *yes*. The generated bootstrap server URL appears in the terminal as an output.
+
[NOTE]
Running `terraform apply` for the first time also creates the Terraform state file. Terraform logs information about the resources it has created in this state file. This allows Terraform to know which resources are under its control and when to update and delete them. The Terraform state file is named `terraform.tfstate` by default and is kept in the same directory where Terraform is run. Sensitive information such as the offline token, client ID, and client secret can be found in the `terraform.tfstate` file. Running `terraform apply` again updates this file.

. To verify Terraform successfully created your Kafka instance, in your web browser, open the *Kafka Instances* page of the {product-kafka} {service-url-kafka}[web console^].
. To connect your applications or services to a Kafka instance in {product-kafka}, you must first create a service account with credentials. To create a service account, copy and paste the  `rhoas_service_account` resource shown in the following example into the `main.tf` file. This example uses the `"my-service-account"` identifier and creates a service account called `my-service-account`.
+

.Example `rhoas_service_account` resource
[source]
----
resource "rhoas_service_account" "my-service-account" {
  name        = "my-service-account"
  description = "<description of service account>"
}

output "client_id" {
  value = rhoas_service_account.my-service-account.client_id
}

output "client_secret" {
  value     = rhoas_service_account.my-service-account.client_secret
  sensitive = true
}
----
+
. Save your changes.
. Apply the changes you made to your Terraform provider configuration.
+
[source, shell]
----
$ terraform apply
----
In the terminal, Terraform displays a message that `rhoas_service_account.my-service-account` will be created.
. When you're ready to create your service account, type *yes*. The generated client ID appears in the terminal as an output. The client secret does not appear because it is marked as a sensitive value.
. To verify Terraform successfully created your service account, in your web browser, open the *Service Accounts* page of the {product-kafka} {service-url-kafka}[web console^].
. To create a Kafka topic with default values, copy and paste the `rhoas_topic` resource shown in the following example into the `main.tf` file. This example uses the `topic` identifier and creates the `my-topic` Kafka topic. As you have already created the Kafka instance, Terraform can check dependencies for this new topic resource and knows the Kafka ID when you run this example resource.
+
.Example `rhoas_topic` resource with default values
[source]
----
resource "rhoas_topic" "topic" {
		name = "my-topic"
		partitions = 1
		kafka_id = rhoas_kafka.instance.id
	}

----
+
. Save your changes.
. Apply the changes you made to your Terraform provider configuration.
+
[source, shell]
----
$ terraform apply
----
In the terminal, Terraform displays a message that `rhoas_topic.my-topic` will be created.
. When you're ready to create your topic, type *yes*.
. To verify Terraform successfully created your topic, in your web browser, open the *Topics* page of the {product-kafka} {service-url-kafka}[web console^].
. To create Access Control List (ACL) permissions with some default values, copy and paste the `rhoas_acl` resource shown in the following example into the `main.tf` file. This example uses the `"acl"` identifier.
. Consider whether you need to specify your own value for any of the fields in the following list. These fields must all have values in an ACL binding resource.

`resource_type`:: The type of resource you grant access to. This example uses `“TOPIC”`.
`resource_name`:: The name of the Kafka resource  you grant access to. This example uses the name that is passed when creating the topic.
`pattern_type`:: The type of pattern of the ACL. This example uses the `LITERAL` pattern type meaning that Kafka will try to match the match the full resource name (the topic) with the resource specified in the ACL.
`principal`:: The user or service account that this binding applies to. This example uses the service account client ID.
`operation_type`:: The type of operation (an action performed on a resource) that is allowed for the given user on this resource.
`permission_type`:: Whether permission is given or taken away.

+
.Example `ACL binding` resource
[source]
----
resource "rhoas_acl" "acl" {
  kafka_id = rhoas_kafka.my-instance.id
  resource_type = "TOPIC"
  resource_name = "my-topic"
  pattern_type = "LITERAL"
  principal = rhoas_service_account.my-service-account.client_id
  operation_type = "ALL"
  permission_type = "ALLOW"
}

----
. Save your changes.
. Apply the changes you made to your Terraform provider configuration.
+
[source, shell]
----
$ terraform apply
----
In the terminal, Terraform displays a message that `rhoas_acl.acl.` will be created.
. When you're ready to set your permissions, type *yes*.
. (Optional) To delete the created resources, enter the following command:
+
[source,shell]
----
$ terraform destroy
----
