[id='proc-configuring-quarkus-registry-app_{context}']
= Configuring the Quarkus application to connect to Kafka and {registry} instances
:imagesdir: ../_images

[role="_abstract"]
To enable your Quarkus applications to access a Kafka instance, configure the connection properties using the Kafka bootstrap server endpoint. To access a {registry} instance, configure the registry endpoint connection property with the Core Registry API value.

Access to the {registry} and Kafka instances is managed using the same service account and SASL/OAUTHBEARER token endpoint. For Quarkus, you can configure all connection properties using the `application.properties` file. This example sets environment variables and references them in this file.

Quarkus applications use https://github.com/eclipse/microprofile-reactive-messaging[MicroProfile Reactive Messaging^] to produce messages to and consume messages from your Kafka instances in {product}. For details on configuration options, see https://quarkus.io/guides/kafka[Using Apache Kafka with Reactive Messaging^] in the Quarkus documentation.

This Quarkus example application includes producer and consumer processes that serialize/deserialize Kafka messages using a schema stored in {registry}.

.Prerequisites
ifndef::qs[]
* You have a service account with access to Kafka and {registry} instances and have stored your credentials securely (see the Getting started quick starts for Kafka and {registry}).
* You have the Kafka bootstrap server endpoint for the Kafka instance. You copied this information previously for the Kafka instance in {product} by selecting the options menu (three vertical dots) and clicking *Connection*.
* You have the Core Registry API endpoint for the {registry} instance. You copied this information for the {registry} instance by selecting the options menu (three vertical dots) and clicking *Connection*. From the list of endpoints, you copied the *Core Registry API* endpoint supported by the Apicurio serializer/deserializer (SerDes) used in this example.
* You copied the *Token endpoint URL* value from the same list of endpoints to be used for the OAuth-based athentication method used in this example.
endif::[]

.Procedure
. On the command line, set the following environment variables to use your Kafka and {registry} instances with Quarkus or other applications. Replace the values with your own server and credential information:
+
* The `<bootstrap_server>` is the bootstrap server endpoint for your Kafka instance.
* The `<core_registry_url>` is the core REST API endpoint for your {registry} instance.
* The `<client_id>` and `<client_secret>` are the generated credentials for your service account.
* The `<oauth_token_endpoint_uri>` is the SASL/OAUTHBEARER token endpoint.
+
.Setting environment variables for server and credentials
[source,subs="+quotes"]
----
$ export BOOTSTRAP_SERVER=__<bootstrap_server>__
$ export REGISTRY_URL=__<core_registry_url>__
$ export CLIENT_ID=__<client_id>__
$ export CLIENT_SECRET=__<client_secret>__
$ export OAUTH_TOKEN_ENDPOINT_URI=__<oauth_token_endpoint_uri>__
----

. In the Quarkus example application, review the `/src/main/resources/application.properties` files in the `consumer` and `producer` sub-folders to understand how the environment variables you set in the previous step are used. This example uses the `dev` configuration profile in the `application.properties` files.

ifdef::qs[]
.Verification
* Did you set the required environment variables for accessing your services?
endif::[]
