[id='ref-example-access-scenarios_{context}']
= Example account access scenarios in {product-kafka}
:imagesdir: ../_images

[role="_abstract"]
The following example Access Control Lists (ACLs) illustrate common scenarios for managing the level of access for user accounts or service accounts in {product-long-kafka}. Some examples differ from the predefined permissions in {product-kafka} to demonstrate various possible ACL scenarios. Use these examples as a guide for your own ACLs.

Access for a new service account in a Kafka instance::
+
--
You’ve created a new service account and you want to allow it to create and delete topics in the instance, to produce and consume messages in any topic in the instance, and to use any consumer group and any producer.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource type
h|Resource identifier and value
h|Access type
h|Operation

|`srvc-acct-1a2b3c4d-...`
|`Topic`
|`Is` = `*`
|`Allow`
|`All`

|`srvc-acct-1a2b3c4d-...`
|`Consumer group`
|`Is` = `*`
|`Allow`
|`Read`
|===
--

Access for all accounts in a Kafka instance::
+
--
You want this Kafka instance to be fully accessible to all accounts in the organization. You want any user to be able to read all topics, write to all topics, use any consumer group, and use any producer.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource
h|Resource identifier and value
h|Access type
h|Operations

|`All accounts`
|`Topic`
|`Is` = `*`
|`Allow`
|`All`

|`All accounts`
|`Consumer group`
|`Is` = `*`
|`Allow`
|`All`
|===
--

Access for a specific user in a Kafka instance::
+
--
You want this Kafka instance to be fully accessible to a specific user. You don't know which topics or consumer groups the user will use, so you want the user to be able to read any topic, write to any topic, and join any consumer group in the instance.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource
h|Resource identifier and value
h|Access type
h|Operations

|`usr-acct-1a2b3c4d-...`
|`Topic`
|`Is` = `*`
|`Allow`
|`All`

|`usr-acct-1a2b3c4d-...`
|`Consumer group`
|`Is` = `*`
|`Allow`
|`All`
|===
--

Access for a specific producer to write to a topic::
+
--
You want to allow a user account with a producer that is associated with a specific `transactional.id` value to produce messages to a specific topic in this Kafka instance.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource
h|Resource identifier and value
h|Access type
h|Operations

|`usr-acct-1a2b3c4d-...`
|`Topic`
|`Is` = `topic-1`
|`Allow`
|`Write`

|`usr-acct-1a2b3c4d-...`
|`Transactional ID`
|`Is` = `producer-1`
|`Allow`
|`All`
|===
--

Access for specific consumer groups to consume from a topic::
+
--
You want to allow a service account with consumers from consumer groups whose names start with `app` to consume messages from a specific topic in this Kafka instance.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource
h|Resource identifier and value
h|Access type
h|Operations

|`srvc-acct-1a2b3c4d-...`
|`Topic`
|`Is` = `topic-1`
|`Allow`
|`Read`

|`srvc-acct-1a2b3c4d-...`
|`Consumer group`
|`Starts with` = `app`
|`Allow`
|`Read`
|===
--

Access for a specific user to manage all permissions in the ACL of a Kafka instance::
+
--
You want to allow a user account to manage all permissions in the ACL for this Kafka instance. You've removed all other permissions from this instance so that the new authorized user can define the new ACL as needed.

.Example ACL permissions
[cols="25%,22%,23%,15%,15%"]
|===
h|Account
h|Resource
h|Resource identifier and value
h|Access type
h|Operations

|`usr-acct-1a2b3c4d-...`
|`Kafka instance`
|None
|`Allow`
|`Alter`

|`usr-acct-1a2b3c4d-...`
|`Kafka instance`
|None
|`Allow`
|`Describe`
|===
--
