[id='ref-supported-topic-properties_{context}']
= Supported topic properties in {product-kafka}
:imagesdir: ../_images

[role="_abstract"]
The following Kafka topic properties are supported in {product-long-kafka}. Each listed topic property indicates whether the property is editable or read only, and includes other relevant property attributes for your reference.

== Core configuration

The following topic properties determine the identity and core behavior of the topic. Before deploying your topic, enter all core configuration properties.

Name::
+
--
The topic name is the unique identifier for the topic within the cluster. You need this to set up your producers and consumers, so make it something memorable.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|Yes

h|Type
|String

h|Default value
|None

h|Supported values
|Letters (Aa-Zz), numbers (0-9), underscores ( _ ), or hyphens ( - ), maximum of 249 characters
|===
--

Partitions::
+
--
Partitions are distinct lists of messages within a topic. Partitions are the main concurrency mechanism in Kafka and enable parts of a topic to be distributed over multiple brokers in the cluster. A topic can contain one or more partitions, enabling producer and consumer loads to be scaled. After you create a topic, you can increase the number of partitions but you cannot decrease it.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|Yes

h|Type
|Integer

h|Default value
|`1`

h|Supported values
|1 or greater

h|Kafka property name
|`num.partitions`
|===

ifdef::community[]
NOTE: If you try to create a new topic with a number of partitions that would cause the partition limit of the Kafka instance to be exceeded, you see an error message indicating this. If you try to increase the number of partitions for an existing topic and this increase would cause the partition limit of the Kafka instance to be exceeded, you see an error message stating that topic authorization failed.
endif::[]

ifndef::community[]
NOTE: If you try to create a new topic with a number of partitions that would cause the partition limit of the Kafka instance to be exceeded, you see an error message indicating this. If you try to increase the number of partitions for an existing topic and this increase would cause the partition limit of the Kafka instance to be exceeded, you see an error message stating that topic authorization failed. For more information about partition limits for Kafka instances, see https://access.redhat.com/articles/5979061[{product-long-kafka} service limits].
endif::[]
--

Replicas::
+
--
Replicas are copies of partitions in a topic. Partition replicas are distributed over multiple brokers in the cluster to ensure topic availability if a broker fails. When a follower replica is in sync with a partition leader, the follower replica can become the new partition leader if needed. Topic replication is an essential property for fault toleration and high availability.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Integer

h|Default value
|`3`

(For trial Kafka instances, the default value is `1`.)

h|Kafka property name
|`replication.factor`
|===
--

Minimum in-sync replicas::
+
--
Minimum in-sync replicas is the minimum number of replicas that must acknowledge a write for the write to be considered successful. To enforce the minimum in-sync replicas value, (set `acks` to `all`) to ensure that producers request acknowledgements from all replicas. If this minimum is not met, the producer raises an exception (`NotEnoughReplicas` or `NotEnoughReplicasAfterAppend`).

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Integer

h|Default value
|`2`

(For trial Kafka instances, the default value is `1`.)

h|Kafka property name
|`min.insync.replicas`
|===
--

Retention time::
+
--
Retention time is the amount of time that messages are retained in a topic before they are deleted. This property applies only when the topic cleanup policy is set to `Delete` or `Compact, Delete`.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|Yes

h|Type
|Long

h|Default value
|`604800000` (milliseconds, 7 days)

h|Kafka property name
|`retention.ms`
|===
--

Retention size::
+
--
Retention size is the maximum total size of all log segments in a partition before old log segments are deleted to free up space. By default, no retention size limit is applied, only a retention time limit. This property applies only when the topic cleanup policy is set to `Delete` or `Compact, Delete`.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|Yes

h|Type
|Long

h|Default value
|`-1` (no retention size limit)

h|Kafka property name
|`retention.bytes`
|===
--

== Messages

The following topic properties control how the Kafka instance handles messages.

Maximum message bytes::
+
--
Maximum message bytes is the maximum record batch size.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Integer

h|Default value
|`1048588` (bytes)

h|Kafka property name
|`max.message.bytes`
|===
--

Message timestamp type::
+
--
Message timestamp type determines whether the timestamp is generated when the message is created (`CreateTime`) or when the message is appended to the log (`LogAppendTime`).

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|String

h|Default value
|`CreateTime`

h|Kafka property name
|`message.timestamp.type`
|===
--

Maximum message timestamp difference::
+
--
Maximum message timestamp difference is the maximum difference allowed between the timestamp specified in the message when it leaves the producer and the timestamp recorded when a broker receives the message.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Long

h|Default value
|`9223372036854775807` (milliseconds)

h|Kafka property name
|`message.timestamp.difference.max.ms`
|===
--

Message format version::
+
--
Message format version is the `ApiVersion` value that the broker uses to append messages to topics. This value must be a valid `ApiVersion` value, such as 0.10.0, 1.1, 2.8, or 3.0.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|String

h|Default value
|`3.0-IV1`

h|Kafka property name
|`message.format.version`
|===
--

Message down-conversion::
+
--
Message down-conversion determines whether the broker can convert the `message.format.version` property value to an older version for consumers that require an older message format version. By default, this property is enabled in order to avoid an `UNSUPPORTED_VERSION` error for consumption requests from older clients. If this property adds excessive load to your broker, you can disable it.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|Yes

h|Type
|Boolean

h|Default value
|`true`

h|Kafka property name
|`message.downconversion.enable`
|===
--

Compression type::
+
--
Compression type determines the final compression for the topic. The only supported value for this property is `Producer`, which retains the original compression type set by the producer.


.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|String

h|Default value
|`Producer`

h|Kafka property name
|`compression.type`
|===
--

== Log

The following topic properties define how the Kafka instance handles the message log.

NOTE: Messages are continually appended to the partition log and are assigned their offset.

Cleanup policy::
+
--
Cleanup policy determines whether log messages are deleted, compacted, or both. With the `Compact, Delete` option, log segments are first compacted and then deleted according to the retention time or size limit settings.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|Yes

h|Type
|List

h|Default value
|`Delete`

h|Supported values
|`Delete`, `Compact`, `Compact, Delete`

h|Kafka property name
|`cleanup.policy`
|===
--

Delete retention time::
+
--
Delete retention time is the amount of time that deletion tombstone markers are retained if the log is compacted. Producers send a tombstone message to act as a marker to tell a consumer that the value is deleted.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|Yes

h|Type
|Long

h|Default value
|`86400000` (milliseconds, 1 day)

h|Kafka property name
|`delete.retention.ms`
|===
--

Minimum cleanable dirty ratio::
+
--
Minimum cleanable dirty ratio is the ratio of entries in the log that can be compacted versus entries that cannot be compacted. When this ratio is reached, the eligible messages in the log are compacted. By default, the ratio is `0.5` or 50%, meaning that messages are compacted after at least half of the log messages are eligible. This property applies only when the topic cleanup policy is set to `Compact` or `Compact, Delete`.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Double

h|Default value
|`0.5` (50%)

h|Kafka property name
|`min.cleanable.dirty.ratio`
|===
--

Minimum compaction lag time::
+
--
Minimum compaction lag time is the minimum time a message remains uncompacted in a log. This property applies only when the topic cleanup policy is set to `Compact` or `Compact, Delete`.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|Yes

h|Type
|Long

h|Default value
|`0` (milliseconds)

h|Kafka property name
|`min.compaction.lag.ms`
|===
--

Maximum compaction lag time::
+
--
Maximum compaction lag time is the maximum time a message remains uncompacted in a log. This property applies only when the topic cleanup policy is set to `Compact` or `Compact, Delete`.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|Yes

h|Type
|Long

h|Default value
|`9223372036854775807` (milliseconds)

h|Kafka property name
|`max.compaction.lag.ms`
|===
--

== Replication

The following topic properties control the behavior of your replicas. Each of these properties impacts every replica created in the topic.

Unclean leader election::
+
--
Unclean leader election allows a follower replica that is not in sync with the partition leader to become the leader of the partition. This property provides a way to retain at least partial data if partition leaders are lost. However, this property can lead to data loss, so it is disabled by default.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Boolean

h|Default value
|`false`

h|Kafka property name
|`unclean.leader.election.enable`
|===
--

== Cleanup

The following topic properties control the cleanup processing of the log.

Log segment size::
+
--
Log segment size is the size of the log segment files that constitute the log. Log processing actions, such as deletion and compaction, operate on old log segments. A larger setting results in fewer files but less frequent log processing.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|Yes

h|Type
|Integer

h|Default value
|`1073741824` (bytes)

h|Supported values
| 52428800 bytes or greater

h|Kafka property name
|`segment.bytes`
|===
--

Segment time::
+
--
Segment time is the amount of time after which the current log segment is rolled even if the segment file is not full. This property enables the segment to be deleted or compacted as needed, even if the log retention limits have not yet been reached.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|Yes

h|Type
|Long

h|Default value
|`604800000` (milliseconds, 7 days)

h|Supported values
|600000 ms (10 mins) or greater

h|Kafka property name
|`segment.ms`
|===
--

Segment jitter time::
+
--
Segment jitter time is the maximum delay for log segment rolling. This delay prevents bursts of log segment rolling activity.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Long

h|Default value
|`0` (milliseconds)

h|Kafka property name
|`segment.jitter.ms`
|===
--

File delete delay::
+
--
File delete delay is the amount of time that a file is retained in the system before the file is deleted.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Long

h|Default value
|`60000` (milliseconds, 1 minute)

h|Kafka property name
|`file.delete.delay.ms`
|===
--

Preallocate log segment files::
+
--
Preallocate log segment files determines whether to preallocate the file on disk when creating a new log segment. This property ensures sufficient disk space for log segments.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Boolean

h|Default value
|`false`

h|Kafka property name
|`preallocate`
|===
--

== Index

The following topic properties control the indexing of the log.

Index interval size::
+
--
Index interval size is the number of bytes between each index entry to its offset index. The default setting indexes a message about every 4096 bytes. More indexing enables reads to be closer to the exact position in the log but makes the index larger.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Integer

h|Default value
|`4000` (bytes, 4 KB)

h|Kafka property name
|`index.interval.bytes`
|===
--

Segment index size::
+
--
Segment index size is the size of the index that maps offset to file positions.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Integer

h|Default value
|`10485760` (bytes)

h|Kafka property name
|`segment.index.bytes`
|===
--

== Flush

The following topic properties control the frequency of the flushing of the log.

Flush interval messages::
+
--
Flush interval messages is the number of messages between each data flush to the log.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Long

h|Default value
|`9223372036854775807` (messages)

h|Kafka property name
|`flush.messages`
|===
--

Flush interval time::
+
--
Flush interval time is the amount of time between each data flush to the log.

.Property attributes
[cols="25%,75%"]
|===
h|Editable
|No

h|Type
|Long

h|Default value
|`9223372036854775807` (milliseconds)

h|Kafka property name
|`flush.ms`
|===
--

[role="_additional-resources"]
.Additional resources
* https://kafka.apache.org/documentation/#topicconfigs[Topic-Level Configs^] in Kafka documentation
