////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////

//All OpenShift Application Services
:org-name: Application Services
:product-long-rhoas: OpenShift Application Services
:product-rhoas: OpenShift Application Services
:community:
:imagesdir: ./images
:property-file-name: app-services.properties
:samples-git-repo: https://github.com/redhat-developer/app-services-guides
:base-url: https://github.com/redhat-developer/app-services-guides/tree/main/docs/
:sso-token-url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
:cloud-console-url: https://console.redhat.com/
:service-accounts-url: https://console.redhat.com/application-services/service-accounts
:rh-sso-url: https://sso.redhat.com
:rh-customer-portal: Red Hat Customer Portal

//OpenShift
:openshift: OpenShift
:osd-name: OpenShift Dedicated
:osd-name-short: OpenShift Dedicated
:rosa-name: OpenShift Service for AWS
:rosa-name-short: OpenShift Service for AWS

//OpenShift Application Services CLI
:base-url-cli: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:command-ref-url-cli: commands
:installation-guide-url-cli: rhoas/rhoas-cli-installation/README.adoc
:service-contexts-url-cli: rhoas/rhoas-service-contexts/README.adoc

//OpenShift Streams for Apache Kafka
:product-long-kafka: OpenShift Streams for Apache Kafka
:product-kafka: Streams for Apache Kafka
:product-version-kafka: 1
:service-url-kafka: https://console.redhat.com/application-services/streams/
:getting-started-url-kafka: kafka/getting-started-kafka/README.adoc
:kafka-bin-scripts-url-kafka: kafka/kafka-bin-scripts-kafka/README.adoc
:kafkacat-url-kafka: kafka/kcat-kafka/README.adoc
:quarkus-url-kafka: kafka/quarkus-kafka/README.adoc
:nodejs-url-kafka: kafka/nodejs-kafka/README.adoc
:getting-started-rhoas-cli-url-kafka: kafka/rhoas-cli-getting-started-kafka/README.adoc
:topic-config-url-kafka: kafka/topic-configuration-kafka/README.adoc
:consumer-config-url-kafka: kafka/consumer-configuration-kafka/README.adoc
:access-mgmt-url-kafka: kafka/access-mgmt-kafka/README.adoc
:metrics-monitoring-url-kafka: kafka/metrics-monitoring-kafka/README.adoc
:service-binding-url-kafka: kafka/service-binding-kafka/README.adoc
:message-browsing-url-kafka: kafka/message-browsing-kafka/README.adoc

//OpenShift Service Registry
:product-long-registry: OpenShift Service Registry
:product-registry: Service Registry
:registry: Service Registry
:product-version-registry: 1
:service-url-registry: https://console.redhat.com/application-services/service-registry/
:getting-started-url-registry: registry/getting-started-registry/README.adoc
:quarkus-url-registry: registry/quarkus-registry/README.adoc
:getting-started-rhoas-cli-url-registry: registry/rhoas-cli-getting-started-registry/README.adoc
:access-mgmt-url-registry: registry/access-mgmt-registry/README.adoc
:content-rules-registry: https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1/guide/9b0fdf14-f0d6-4d7f-8637-3ac9e2069817[Supported Service Registry content and rules]
:service-binding-url-registry: registry/service-binding-registry/README.adoc

//OpenShift Connectors
:connectors: Connectors
:product-long-connectors: OpenShift Connectors
:product-connectors: Connectors
:product-version-connectors: 1
:service-url-connectors: https://console.redhat.com/application-services/connectors
:getting-started-url-connectors: connectors/getting-started-connectors/README.adoc
:getting-started-rhoas-cli-url-connectors: connectors/rhoas-cli-getting-started-connectors/README.adoc
:addon-url-connectors: https://access.redhat.com/documentation/en-us/openshift_connectors/1/guide/15a79de0-8827-4bf1-b445-8e3b3eef7b01


//OpenShift API Designer
:product-long-api-designer: OpenShift API Designer
:product-api-designer: API Designer
:product-version-api-designer: 1
:service-url-api-designer: https://console.redhat.com/application-services/api-designer/
:getting-started-url-api-designer: api-designer/getting-started-api-designer/README.adoc

//OpenShift API Management
:product-long-api-management: OpenShift API Management
:product-api-management: API Management
:product-version-api-management: 1
:service-url-api-management: https://console.redhat.com/application-services/api-management/

////
END GENERATED ATTRIBUTES
////

[id="chap-getting-started-api-designer"]
= Getting started with {product-long-api-designer}
ifdef::context[:parent-context: {context}]
:context: getting-started-ad

// Purpose statement for the assembly
[role="_abstract"]
As an API owner or developer, you can use {product-long-api-designer} to design event schemas and API definitions that comply with vendor-neutral and portable open specifications.
{product-long-api-designer} is a managed cloud service that enables you to design schemas and API definitions without having to install, configure, run, and maintain your own {product-api-designer} infrastructure. 

For more overview information, see the https://access.redhat.com/documentation/en-us/red_hat_openshift_api-designer/1[{product-long-api-designer} user documentation^].

ifndef::community[]
.Prerequisites
* You have a {org-name} account.
* If you plan to store your designs in {product-long-registry}, you have a running {registry} instance (see {base-url}{getting-started-url-registry}[Getting started with {product-long-registry}^]).
//For more information about signing up, see *<@SME: Where to link?>*.
endif::[]

// Condition out QS-only content so that it doesn't appear in docs.
// All QS anchor IDs must be in this alternate anchor ID format `[#anchor-id]` because the ascii splitter relies on the other format `[id="anchor-id"]` to generate module files.
ifdef::qs[]
[#description]
====
Use the web console to create an API or schema design in {product-long-api-designer}.
====

[#introduction]
====
Welcome to the quick start for {product-long-api-designer}.
In this quick start, you'll learn how to create an API definition or event schema from a simple or detailed template, import an existing design to edit it, test a design against rules configured in {product-long-registry}, and export a finished design to {product-registry}.
====
endif::[]

[id="proc-creating-api-design_{context}"]
== Creating an API design

[role="_abstract"]
Use the {product-long-api-designer} web console to create an OpenAPI or AsyncAPI definition.

ifndef::qs[]
.Prerequisites
* You're logged in to the {product-long-api-designer} web console at {service-url-api-designer}[^].
endif::[]


.Procedure
. In the {service-url-api-designer}[{product-long-api-designer} web console^], click *Create design*.
. Complete the form to provide the following details for the new design:
* *Name*: Enter a unique design name, such as `My API Design`.
* *Description* _(Optional)_: Enter a short description of the design.
* *Type*: Accept the default value *OpenAPI*, or select another API type from the list.
* *Version* _(OpenAPI only)_: Accept the default value *3.0.2*, or select another version from the list.
* *Template*: Select the *Pet Store Example* template, or select another template from the list.
. Click *Create*. The new API design opens in the design editor.
. Select the design title and click the pen icon. Change the design title to *Orders* and click the *Save changes* icon.
+
NOTE: Editing the design _title_ does not change the design _name_. To rename a design, click *Actions > Edit design metadata*, edit the design name, and click *Save*.
+
. Click the *Design* tab, and optionally edit the design as follows:
* Provide a version number and a description.
* _(AsyncAPI only)_ Define terms of service.
* Add your contact information: name, email address, and URL.
* Select a license.
* _(OpenAPI only)_ Define tags.
* Define one or more servers.
* Configure a security scheme.
* _(OpenAPI only)_ Specify security requirements.
* _(OpenAPI only)_ Configure vendor extensions.
. Click the *Source* tab, and review the live preview of the design.
The content of the *Source* tab automatically updates when you edit values on the editor page.
. _(Optional)_ To see the changes that you made since the last save, click *Actions > Show design changes*.
. _(Optional)_ In the left pane of the design editor, you can add the following items:
* _(OpenAPI only)_ Resource paths, data types, and responses
* _(AsyncAPI only)_ Channels, data types, messages, operation traits, and message traits
. Click *Save*.
+
The new design is listed on the *API and Schema Designs* page.
You can use the options icon (three vertical dots) to view or edit the design details, edit the design content, export the design to {product-long-registry}, download the design to a file, or delete the design.

.Verification
ifdef::qs[]
* Is the new design listed on the designs page?
* Are the design details correct?
endif::[]
ifndef::qs[]
. Verify that the new design is listed on the designs page.
. Verify that the design details are correct.
endif::[]

[id="proc-creating-schema-design_{context}"]
== Creating a schema design

[role="_abstract"]
Use the {product-long-api-designer} web console to create an Apache Avro, JSON Schema, or Google Protocol Buffers (Protobuf) event schema.

ifndef::qs[]
.Prerequisites
* You're logged in to the {product-long-api-designer} web console at {service-url-api-designer}[^].
endif::[]

.Procedure
. In the {service-url-api-designer}[{product-long-api-designer} web console^], click *Create design*.
. Complete the form to provide the following details for the new design:
* *Name*: Enter a unique design name, such as `My Schema Design`.
* *Description* _(Optional)_: Enter a short description of the design.
* *Type*: From the list, select *Apache Avro*, or select another schema type.
. Click *Create*. The new schema design opens in the design editor.
. Edit the design source to provide your content.
. _(Optional)_ To see the changes that you made since the last save, click *Actions > Show design changes*.
. _(Optional)_ For Apache Avro or JSON Schema designs, you can click *Actions > Format design content* to insert spaces and tabs that align your design content correctly.
. Click *Save*.
+
The new design is listed on the *API and Schema Designs* page.
You can use the options icon (three vertical dots) to view or edit the design details, edit the design content, export the design to {product-long-registry}, download the design to a file, or delete the design.

.Verification
ifdef::qs[]
* Is the new design listed on the designs page?
* Are the design details correct?
endif::[]
ifndef::qs[]
. Verify that the new design is listed on the designs page.
. Verify that the design details are correct.
endif::[]

[id="proc-importing-schema-api-design_{context}"]
== Importing a schema or API design

[role="_abstract"]
You can import an event schema or API definition into {product-long-api-designer} from a URL, from a file, or from a running {product-long-registry} instance.

.Prerequisites
* You're logged in to the {product-long-api-designer} web console at {service-url-api-designer}[^].
* You can access a running {product-registry} instance in your organization, if you want to import from {product-long-registry}.
For more information, see {base-url}{getting-started-url-registry}[Getting started with {product-long-registry}^].

.Procedure
. In the {service-url-api-designer}[{product-long-api-designer} web console^], click *Import design*, and then click one of the following options:
* *Import from {registry}*: From the instances list, select a {registry} instance.
Browse the list of artifacts for that instance, and select an artifact.
* *Import from URL*: Enter a valid and accessible URL, and click *Fetch*.
* *Import from file*: Click *Browse* and select a file, or drag and drop a file.
. When prompted, provide additional information such as version (_OpenAPI only_), name, type, and description in the import dialog. You can overwrite any autopopulated values.
. Click *Import*.
The design editor opens automatically.

When you finish editing, you can export the updated design to {registry} as a new artifact or as a new version of the existing artifact.
You can export the design from the design editor or from the *API and Schema Designs* page.
You can also save your changes locally, or download the content to a file.

.Verification
ifdef::qs[]
* Is the imported design listed on the designs page?
* Are the design details correct?
endif::[]
ifndef::qs[]
. Verify that the imported design is listed on the designs page.
. Verify that the design details are correct.
endif::[]

[id="proc-testing-schema-api-design_{context}"]
== Testing a schema or API design

[role="_abstract"]
You can test that your schema or API design content is valid and compatible with existing content by applying the rules of an existing {product-long-registry} instance.
You can test the design while working in the {product-long-api-designer} editor, without exporting the design to {product-long-registry}.

.Prerequisites
* You're logged in to the {product-long-api-designer} web console at {service-url-api-designer}[^].
* You've created or imported a design in {product-api-designer}.
* You can access a running {product-registry} instance in your organization.
Within that instance, you know the artifact ID of an artifact with the required rules configured.
For more information, see {base-url}{getting-started-url-registry}[Getting started with {product-long-registry}^].

.Procedure
. On the *API and Schema Designs* page of the {service-url-api-designer}[{product-long-api-designer} web console^], select the design that you want to test.
. Click the options icon (three vertical dots), and click *Edit design content* to open the design editor.
. From the *Actions* menu, click *Run {registry} check*.
. From the *Registry instance* list, select a {registry} instance.
. In the *Group* and *ID* fields, specify the artifact details.
. Click *Test*.

A new pane in the design editor window shows the registration issues found by the test:

* If the design content obeys the specified rules, the registration issues pane contains the following text:
`Registry Test completed with no issues`

* If the registration issues pane provides details of any issues, resolve the issues and click *Retry* to retest the content using the same artifact rules.

.Verification
ifdef::qs[]
* Is the registration issues pane shown in the design editor?
* Are the test results correct?
endif::[]
ifndef::qs[]
. Verify that the registration issues pane is shown in the design editor.
. Verify that the test results are correct.
endif::[]

[id="proc-exporting-schema-api-design_{context}"]
== Exporting a schema or API design

[role="_abstract"]
When you're happy with the changes to your {product-long-api-designer} event schema or API definition, and you want to use the design in your application, you can export the content to an existing {product-long-registry} instance.

.Prerequisites
* You're logged in to the {product-long-api-designer} web console at {service-url-api-designer}[^].
* You've created or imported a design in {product-api-designer}.
* You can access a running {product-registry} instance in your organization.
For more information, see {base-url}{getting-started-url-registry}[Getting started with {product-long-registry}^].

.Procedure
. On the *API and Schema Designs* page of the {service-url-api-designer}[{product-long-api-designer} web console^], select the design that you want to export.
. Click the options icon (three vertical dots), and click *Export design to {registry}*.
+
NOTE: You can also select *Export design to {registry}* from the *Actions* menu in the design editor.
+
. Complete the form to specify where to save the new design. Provide the following details:
+
NOTE: If the design was originally imported from {product-long-registry}, the fields are prepopulated with the details of the original {product-registry} instance, and the *Version* field is blank.
+
* *Registry Instance*: Select the required instance from the list.
* *Group* _(Optional)_: Enter a unique group name such as `my-org` to organize the artifact in a named collection.
Each group contains a logically related set of schemas or API designs, typically managed by a single entity, belonging to a particular application or organization.
+
NOTE:  Specifying a group is optional when using the web console. If no group is specified, {registry} uses the `default` group.
+
* *ID* _(Optional)_: Enter a unique ID for this artifact, such as `my-ID`.
If you don't specify a unique artifact ID, {registry} generates one automatically as a UUID.
* *Version* _(Optional)_: Specify the version number.
If you don't specify a version number, {registry} sets the version to 1 for the first version, or increments the latest version by 1 for subsequent versions.
. Click *Export*.
The exported design is listed on the artifacts page of the specified {registry} instance.

You can use {product-long-registry} to manage the versions of a design from {product-long-api-designer}.
You can also download a design from {product-api-designer} to a file, either for local client code generation or to import the design into {product-long-api-management}.

.Verification
ifdef::qs[]
* Is the design listed as an artifact in {product-long-registry}?
* Are the artifact details correct?
endif::[]
ifndef::qs[]
* Verify that the design is listed as an artifact in {product-long-registry}.
* Verify that the artifact details are correct.
endif::[]


[role="_additional-resources"]
== Additional resources
* https://access.redhat.com/documentation/en-us/red_hat_openshift_api_designer/1[{product-long-api-designer} user documentation^]
* https://access.redhat.com/documentation/en-us/red_hat_openshift_api_management/1[{product-long-api-management} user documentation^]
* https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1[{product-long-registry} user documentation^]
* https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/1[{product-long-kafka} user documentation^]

ifdef::qs[]
[#conclusion]
====
Congratulations!
You successfully completed the {product-long-api-designer} Getting Started quick start, and are now ready to use the service.
====
endif::[]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
