////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////

//All OpenShift Application Services
:org-name: Application Services
:product-long-rhoas: OpenShift Application Services
:product-rhoas: OpenShift Application Services
:community:
:imagesdir: ./images
:property-file-name: app-services.properties
:samples-git-repo: https://github.com/redhat-developer/app-services-guides
:base-url: https://github.com/redhat-developer/app-services-guides/tree/main/docs/
:sso-token-url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
:cloud-console-url: https://console.redhat.com/
:service-accounts-url: https://console.redhat.com/application-services/service-accounts
:rh-sso-url: https://sso.redhat.com
:rh-customer-portal: Red Hat Customer Portal

//OpenShift
:openshift: OpenShift
:osd-name: OpenShift Dedicated
:osd-name-short: OpenShift Dedicated
:rosa-name: OpenShift Service on AWS
:rosa-name-short: OpenShift Service on AWS

//OpenShift Application Services CLI
:base-url-cli: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:command-ref-url-cli: commands
:installation-guide-url-cli: rhoas/rhoas-cli-installation/README.adoc
:service-contexts-url-cli: rhoas/rhoas-service-contexts/README.adoc

//OpenShift Streams for Apache Kafka
:product-long-kafka: OpenShift Streams for Apache Kafka
:product-kafka: Streams for Apache Kafka
:product-version-kafka: 1
:service-url-kafka: https://console.redhat.com/application-services/streams/
:getting-started-url-kafka: kafka/getting-started-kafka/README.adoc
:kafka-bin-scripts-url-kafka: kafka/kafka-bin-scripts-kafka/README.adoc
:kafkacat-url-kafka: kafka/kcat-kafka/README.adoc
:quarkus-url-kafka: kafka/quarkus-kafka/README.adoc
:nodejs-url-kafka: kafka/nodejs-kafka/README.adoc
:getting-started-rhoas-cli-url-kafka: kafka/rhoas-cli-getting-started-kafka/README.adoc
:topic-config-url-kafka: kafka/topic-configuration-kafka/README.adoc
:consumer-config-url-kafka: kafka/consumer-configuration-kafka/README.adoc
:access-mgmt-url-kafka: kafka/access-mgmt-kafka/README.adoc
:metrics-monitoring-url-kafka: kafka/metrics-monitoring-kafka/README.adoc
:service-binding-url-kafka: kafka/service-binding-kafka/README.adoc
:message-browsing-url-kafka: kafka/message-browsing-kafka/README.adoc

//OpenShift Service Registry
:product-long-registry: OpenShift Service Registry
:product-registry: Service Registry
:registry: Service Registry
:product-version-registry: 1
:service-url-registry: https://console.redhat.com/application-services/service-registry/
:getting-started-url-registry: registry/getting-started-registry/README.adoc
:quarkus-url-registry: registry/quarkus-registry/README.adoc
:getting-started-rhoas-cli-url-registry: registry/rhoas-cli-getting-started-registry/README.adoc
:access-mgmt-url-registry: registry/access-mgmt-registry/README.adoc
:content-rules-registry: https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1/guide/9b0fdf14-f0d6-4d7f-8637-3ac9e2069817[Supported Service Registry content and rules]
:service-binding-url-registry: registry/service-binding-registry/README.adoc

//OpenShift Connectors
:connectors: Connectors
:product-long-connectors: OpenShift Connectors
:product-connectors: Connectors
:product-version-connectors: 1
:service-url-connectors: https://console.redhat.com/application-services/connectors
:getting-started-url-connectors: connectors/getting-started-connectors/README.adoc
:getting-started-rhoas-cli-url-connectors: connectors/rhoas-cli-getting-started-connectors/README.adoc
:addon-url-connectors: https://access.redhat.com/documentation/en-us/openshift_connectors/1/guide/15a79de0-8827-4bf1-b445-8e3b3eef7b01


//OpenShift API Designer
:product-long-api-designer: OpenShift API Designer
:product-api-designer: API Designer
:product-version-api-designer: 1
:service-url-api-designer: https://console.redhat.com/application-services/api-designer/
:getting-started-url-api-designer: api-designer/getting-started-api-designer/README.adoc

//OpenShift API Management
:product-long-api-management: OpenShift API Management
:product-api-management: API Management
:product-version-api-management: 1
:service-url-api-management: https://console.redhat.com/application-services/api-management/

////
END GENERATED ATTRIBUTES
////

[id="chap-getting-started-rhoas-cli-registry"]
= Managing {product-registry} by using the {product-rhoas} CLI
:context: getting-started-rhoas-service-registry

[role="_abstract"]
With the {product-long-rhoas} `rhoas` command-line interface (CLI), you can manage {product-long-registry} from a terminal.

As a developer of applications and services,
you can use `rhoas` to create {registry} instances and connect your applications and services to these instances.
You can also manage artifacts.
Artifacts are items stored in {registry}, such as schemas and API specifications.


//Additional line break to resolve mod docs generation error

[id="ref-service-registry-cli-prereqs_{context}"]
== Prerequisites

[role="_abstract"]
* You've installed the `rhoas` CLI.
For more information, see {base-url}{installation-guide-url-cli}[_Installing and configuring the {product-rhoas} CLI_^].

[id="proc-creating-service-registry-instance-cli_{context}"]
== Creating a {registry} instance

[role="_abstract"]
A {registry} instance serves as a central location for storing artifacts.

.Prerequisites

* You're logged in to `rhoas`.

.Procedure

. Create a {registry} instance with default values.
+
--
This example creates a {registry} instance called `my-registry`.

.Creating a {registry} instance
[source,shell,subs="attributes"]
----
$ rhoas service-registry create --name my-registry
----

The CLI uses service contexts to group service instances against which commands are executed.
The current context is automatically updated so that the created {registry} instance is set as the current instance.

[NOTE]
====
If you do not want to use the default values, enter the following command: `rhoas service-registry create`.
You are prompted to enter the `Name` and optional `Description` for the {registry} instance.
====
--

. Verify that the {registry} instance is ready to use.
+
--
.Reviewing the {registry} instance details
[source,shell]
----
$ rhoas context status service-registry
----

This command shows that the {registry} instance is ready to use,
because the `Status` field is `ready`.

[NOTE]
====
By default, many of the `rhoas` commands provide output in JSON format. You can use the `-o` option to specify a different output format. For more information, see {base-url}{getting-started-rhoas-cli-url-registry}#proc-commands-managing-registry_getting-started-rhoas-service-registry[Commands for managing {registry}].
====
--


[id="proc-specifying-default-service-registry-instance-cli_{context}"]
== Specifying the default {registry} instance

[role="_abstract"]
If you have multiple {registry} instances, you can configure a default {registry} instance.

.Prerequisites

* You've created a {registry} instance, and it has a `ready` status.

.Procedure

. Configure the default {registry} instance in one of the following ways:

** Use the `rhoas context set-service-registry` command:
+
--
.Selecting a {registry} instance into the current context
[source,shell]
----
$ rhoas context set-service-registry --name=my-registry
----
--

** Use the `rhoas service-registry use` command:
+
--
.Selecting a {registry} instance to use
[source,shell]
----
$ rhoas service-registry use --name=my-registry
----

[NOTE]
====
You can run the `rhoas service-registry use` command without specifying the instance name, and then select the instance name from the generated list of instances.
====
--

. Verify that the specified {registry} instance is set as the default instance.
+
--
.Reviewing the details of the default {registry} instance
[source,shell]
----
$ rhoas context status service-registry
----

This command shows the name of the default {registry} instance for all `rhoas service-registry` commands.

[NOTE]
====
You can override the default value by specifying a different target instance in the `rhoas service-registry` commands.
====
--

[id="proc-creating-service-registry-account_{context}"]
== Creating a service account

[role="_abstract"]
To connect your applications or services to a {registry} instance, you must first create a service account with credentials.
The credentials are exported to a file on your computer,
which you can use to authenticate your application with your {registry} instance.

.Prerequisites

* You've created a {registry} instance, and it has a `ready` status.

.Procedure

. Create a service account.
+
--
This example creates a service account and saves the credentials in a JSON file.

.Creating a service account
[source,shell]
----
$ rhoas service-account create --short-description="rhoas-service-account" --file-format json
----

[NOTE]
====
When creating a service account, you can choose the file format and location to save the credentials.
For more information, run the `rhoas service-account create -h` command to view the command help.
====
--

. To verify your service account credentials,
view the `credentials.json` file that you created.
+
--
.Example `credentials.json` file
[source,json,subs="+attributes,+quotes"]
----
{
	"clientID":"_<client-id>_",
	"clientSecret":"_<client-secret>_",
    "oauthTokenUrl": "{sso-token-url}"
}
----
You use these credentials and the {registry} URL to connect your applications and services to your {registry} instance.

[NOTE]
====
By connecting your applications to your {registry} instance, you can retrieve artifacts and use them directly in your service.
====
--

. Create a role for the new service account that can read and write artifacts.
+
--
This example creates a role called `manager` for the service account.

.Creating a role for the service account
[source,shell,subs="+quotes"]
----
$ rhoas service-registry role add --role=manager --service-account=_<client-id>_
----

[NOTE]
====
For more information about the different roles, run the `rhoas service-registry role -h` command to view the command help.
====
--


[id="proc-uploading-service-registry-artifacts_{context}"]
== Uploading {registry} artifacts

[role="_abstract"]
After creating a {registry} instance, you can start uploading {registry} artifacts.
Artifacts might include, for example, schemas that define the structure of Kafka data or OpenAPI documents to define a REST API.

.Prerequisites

* You've created a {registry} instance, and it has a `ready` status.
* Your {registry} instance is the default instance, as described in {base-url}{getting-started-rhoas-cli-url-registry}#proc-specifying-default-service-registry-instance-cli_getting-started-rhoas-service-registry[Specifying the default {registry} instance].

.Procedure

. Upload the artifact in one of the following ways:

* Upload the artifact from a file:

.. Download an example schema.
+
--
This example downloads an Apache Avro schema in JSON format.

.Downloading an example schema
[source,shell]
----
$ wget https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/docs/resources/avro-userInfo.json
----
--

.. Upload the schema as a {registry} artifact.
+
--
This example creates a {registry} artifact called `my-artifact` from the Avro schema that you downloaded in the previous step, and uploads the artifact to the {registry} instance.

.Creating and uploading an artifact from a file
[source,shell]
----
$ rhoas service-registry artifact create --type=AVRO --artifact-id=my-artifact avro-userInfo.json
----
--

* Upload the artifact directly from a URL:
+
--
.Creating and uploading an artifact from a URL
[source,shell]
----
$ rhoas service-registry artifact create --type=AVRO --artifact-id=my-artifact https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/docs/resources/avro-userInfo.json
----
--

. Verify that the artifact was registered.
+
--
This example lists all artifacts in the default group for the {registry} instance.

.Listing artifact details for a {registry} instance
[source,shell]
----
$ rhoas service-registry artifact list
----

[NOTE]
====
You can use the `-a` option to list all artifacts in _all_ groups for the {registry} instance.
====
--

. Check the version information for the artifact.
+
--
This example lists information about each version of the artifact.

.Checking the version information of an artifact
[source,shell]
----
$ rhoas service-registry artifact versions --artifact-id=my-artifact
----
--

. Check the metadata information for the artifact.
+
--
This example lists additional information about the latest version of the artifact.

.Checking the metadata information of an artifact
[source,shell]
----
$ rhoas service-registry artifact metadata-get --artifact-id=my-artifact
----

[NOTE]
====
You can use additional options, such as `--group` and `--description`, to modify the metadata of the artifact you're creating.
For more information about any of the options, run the `rhoas service-registry artifact metadata-set -h` command to view the command help.
====
--

[id="proc-downloading-service-registry-artifacts_{context}"]
== Downloading {registry} artifacts

[role="_abstract"]
After you register a {registry} artifact, you can download the artifact to update it.

.Prerequisites

* You've created a {registry} instance with at least one artifact.
* Your {registry} instance is the default instance, as described in {base-url}{getting-started-rhoas-cli-url-registry}#proc-specifying-default-service-registry-instance-cli_getting-started-rhoas-service-registry[Specifying the default {registry} instance].

.Procedure

. Download the artifact in one of the following ways:

** Use the `rhoas service-registry artifact get` command and specify the artifact ID.
+
--
To find the artifact ID, use the `rhoas service-registry artifact list` command.

.Downloading an artifact by using the artifact ID
[source,shell]
----
$ rhoas service-registry artifact get --artifact-id=my-artifact
----
--

** Use the `rhoas service-registry artifact download` command and specify the global ID.
+
--
To find the global ID, see the output of the `rhoas service-registry artifact metadata-get --artifact-id=my-artifact` command.

.Downloading an artifact by using the global ID
[source,shell]
----
$ rhoas service-registry artifact download --global-id=28
----
--

. Verify that the artifact was downloaded.

[NOTE]
====
You can use additional options, such as `--group` and `--instance-id`, to specify the artifact to download.
For more information about any of the options, run the `rhoas service-registry artifact download -h` command and the `rhoas service-registry artifact get -h` command to view the command help.
====

[id="proc-updating-service-registry-artifacts_{context}"]
== Updating {registry} artifacts

[role="_abstract"]
You can update an artifact with content from a file or from standard input.

.Prerequisites

* You've created a {registry} instance with at least one artifact.
* Your {registry} instance is the default instance, as described in {base-url}{getting-started-rhoas-cli-url-registry}#proc-specifying-default-service-registry-instance-cli_getting-started-rhoas-service-registry[Specifying the default {registry} instance].
* The type of the updated content is compatible with the current artifact type.

.Procedure

. Update a {registry} artifact.
+
--
This example updates a {registry} artifact called `my-artifact` with content from a file in JSON format.

.Updating an artifact from a file
[source,shell]
----
$ rhoas service-registry artifact update --artifact-id=my-artifact my-artifact.json
----

[NOTE]
====
To update the artifact from standard input, use the `rhoas service-registry artifact update --artifact-id=my-artifact` command.

Paste the updated artifact content on the command line, and then press Ctrl+D to save.
====
--

. Verify that the artifact was updated. The updated artifact is saved as a new version.
+
--
.Checking the version number and modified date of an artifact
[source,shell]
----
$ rhoas service-registry artifact metadata-get --artifact-id=my-artifact
----

[NOTE]
====
You can use additional options, such as `--group` and `--version`, to specify the artifact to update.
For more information about any of the options, run the `rhoas service-registry artifact update -h` command to view the command help.
====
--

[id="proc-configuring-service-registry-rules_{context}"]
== Configuring {registry} rules

[role="_abstract"]
To prevent invalid content from being added to {registry}, you can configure optional rules to check the artifact content. Global rules apply to all artifacts in a particular {registry} instance. Artifact rules apply to the specified artifact only, and cannot be configured until the artifact is created. Configured artifact rules override any configured global rules.

When you create an instance, the global rules are disabled by default. When you create an artifact, the artifact rules are disabled by default. To configure a global rule or artifact rule, you must ensure that the rule is enabled. An artifact cannot be updated if the new content violates any of the enabled rules; in such cases, the registration fails.

.Prerequisites

* You've created a {registry} instance with at least one artifact.
* Your {registry} instance is the default instance, as described in {base-url}{getting-started-rhoas-cli-url-registry}#proc-specifying-default-service-registry-instance-cli_getting-started-rhoas-service-registry[Specifying the default {registry} instance].

.Procedure

. Identify the rule that you want to configure.
+
--
To show a list of global rules, run the following command:

[source,shell]
----
$ rhoas service-registry rule list
----

To show a list of artifact rules, specify the artifact ID as shown in the following example:

[source,shell]
----
$ rhoas service-registry rule list --artifact-id=my-artifact
----

--
. Configure or update the rule in one of the following ways:
* If the rule that you want to configure is disabled, use the `rhoas service-registry rule enable` command.
+
--
When you enable a rule, you must specify the configuration value. If the rule is not currently enabled, you can enable the rule and specify its configuration in the same command.

This example enables and configures the global compatibility rule for all artifacts in the current {registry} instance:

[source,shell]
----
$ rhoas service-registry rule enable --rule-type=compatibility --config=full
----

This example enables and configures the validity rule for a specific artifact:

[source,shell]
----
$ rhoas service-registry rule enable --rule-type=validity --config=full --artifact-id=my-artifact
----

[NOTE]
====
You can use additional options, such as `--group` and `--instance-id`, to specify the {registry} group or instance to which the updated rules apply.
For more information about any of the options, run the `rhoas service-registry rule enable -h` command to view the command help.
====
--
* If the rule is already enabled, use the `rhoas service-registry rule update` command.
+
--
You can update a rule by specifying the rule type and the new configuration.

This example updates the global compatibility rule for all artifacts in the current {registry} instance:

[source,shell]
----
$ rhoas service-registry rule update --rule-type=compatibility --config=backward
----

This example updates the validity rule for a specific artifact:

[source,shell]
----
$ rhoas service-registry rule update --rule-type=validity --config=syntax-only --artifact-id=my-artifact
----

[NOTE]
====
For more information about {registry} rule types and rule maturity, see {content-rules-registry}.
====

--

. Verify that the rule updated correctly.
+
--
This example displays the details of the global compatibility rule:

[source,shell]
----
$ rhoas service-registry rule describe --rule-type=compatibility
----

This example displays the details of the artifact validity rule:

[source,shell]
----
$ rhoas service-registry rule describe --rule-type=validity --artifact-id=my-artifact
----
--

. Optional: If you no longer want to apply a rule, you can disable the rule.
+
--
This example disables the global compatibility rule:

[source,shell]
----
$ rhoas service-registry rule disable --rule-type=compatibility
----

This example disables the artifact validity rule:

[source,shell]
----
$ rhoas service-registry rule disable --rule-type=validity --artifact-id=my-artifact
----

[NOTE]
====
You can use additional options, such as `--group` and `--instance-id`, to specify the {registry} group or instance to which the updated rules apply.
For more information about any of the options, run the `rhoas service-registry rule disable -h` command to view the command help.
====
--

[id="proc-generating-registry-configs_{context}"]
== Generating configurations for {registry} instance

[role="_abstract"]
After creating a {registry} instance, you can generate a configuration file that your applications can use to connect to your {registry} instance.

.Prerequisites

* You've created a {registry} instance.
* Your user account and org have quota for creating service accounts.

.Procedure

. Ensure that your {registry} instance is the default instance, as described in {base-url}{getting-started-rhoas-cli-url-registry}#proc-specifying-default-service-registry-instance-cli_getting-started-rhoas-service-registry[Specifying the default {registry} instance].

. Generate a configuration file for the current service context.
+
--
This example generates a JSON file with configurations for the {registry} instance.

.Generating a configuration file
[source,shell]
----
$ rhoas generate-config --type json
----
--


[id="proc-commands-managing-registry_{context}"]
== Commands for managing {registry}

[role="_abstract"]
For more information about the `rhoas` commands that you can use to manage your {registry} instance, run the following commands to view the command help:

* `rhoas service-registry -h` for {registry} instances
* `rhoas service-account -h` for service accounts
* `rhoas service-registry artifact -h` for {registry} artifacts
* `rhoas service-registry role -h` for {registry} roles
* `rhoas service-registry rule -h` for {registry} rules
* `rhoas service-registry setting -h` for {registry} settings

[role="_additional-resources"]
.Additional resources
* {base-url-cli}{command-ref-url-cli}[_{product-rhoas} CLI command reference_^]
