////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////

//OpenShift Application Services
:org-name: Application Services
:product-long-rhoas: OpenShift Application Services
:community:
:imagesdir: ./images
:property-file-name: app-services.properties
:samples-git-repo: https://github.com/redhat-developer/app-services-guides
:base-url: https://github.com/redhat-developer/app-services-guides/tree/main/docs/

//OpenShift Application Services CLI
:rhoas-cli-base-url: https://github.com/redhat-developer/app-services-cli/tree/main/docs/
:rhoas-cli-ref-url: commands
:rhoas-cli-installation-url: rhoas/rhoas-cli-installation/README.adoc

//OpenShift Streams for Apache Kafka
:product-long-kafka: OpenShift Streams for Apache Kafka
:product-kafka: Streams for Apache Kafka
:product-version-kafka: 1
:service-url-kafka: https://console.redhat.com/application-services/streams/
:getting-started-url-kafka: kafka/getting-started-kafka/README.adoc
:kafka-bin-scripts-url-kafka: kafka/kafka-bin-scripts-kafka/README.adoc
:kafkacat-url-kafka: kafka/kcat-kafka/README.adoc
:quarkus-url-kafka: kafka/quarkus-kafka/README.adoc
:nodejs-url-kafka: kafka/nodejs-kafka/README.adoc
:rhoas-cli-getting-started-url-kafka: kafka/rhoas-cli-getting-started-kafka/README.adoc
:topic-config-url-kafka: kafka/topic-configuration-kafka/README.adoc
:consumer-config-url-kafka: kafka/consumer-configuration-kafka/README.adoc
:access-mgmt-url-kafka: kafka/access-mgmt-kafka/README.adoc
:metrics-monitoring-url-kafka: kafka/metrics-monitoring-kafka/README.adoc
:service-binding-url-kafka: kafka/service-binding-kafka/README.adoc

//OpenShift Service Registry
:product-long-registry: OpenShift Service Registry
:product-registry: Service Registry
:registry: Service Registry
:product-version-registry: 1
:service-url-registry: https://console.redhat.com/application-services/service-registry/
:getting-started-url-registry: registry/getting-started-registry/README.adoc
:quarkus-url-registry: registry/quarkus-registry/README.adoc
:rhoas-cli-getting-started-url-registry: registry/rhoas-cli-getting-started-registry/README.adoc
:access-mgmt-url-registry: registry/access-mgmt-registry/README.adoc
:content-rules-registry: https://access.redhat.com/documentation/en-us/red_hat_openshift_service_registry/1/guide/9b0fdf14-f0d6-4d7f-8637-3ac9e2069817[Supported Service Registry content and rules]
:service-binding-url-registry: registry/service-binding-registry/README.adoc

////
END GENERATED ATTRIBUTES
////

[id="chap-getting-started-rhoas-cli-registry"]
= Getting started with the rhoas CLI for {product-long-registry}
:context: getting-started-rhoas-service-registry

[role="_abstract"]
With the {product-long-rhoas} `rhoas` command-line interface (CLI), you can manage {product-long-registry} from a terminal.

As a developer of applications and services,
you can use `rhoas` to create {registry} instances and connect your applications and services to these instances.
You can also manage artifacts.
Artifacts are items stored in {registry}, such as schemas and API specifications.

You can get started with {product-long-registry} by doing the following tasks:

* {base-url}{rhoas-cli-getting-started-url-registry}#proc-creating-service-registry-instance-cli_getting-started-rhoas-service-registry[Create a {registry} instance]
* {base-url}{rhoas-cli-getting-started-url-registry}#proc-creating-service-registry-account_getting-started-rhoas-service-registry[Create a service account]
* {base-url}{rhoas-cli-getting-started-url-registry}#proc-uploading-service-registry-artifacts_getting-started-rhoas-service-registry[Upload {registry} artifacts]
* {base-url}{rhoas-cli-getting-started-url-registry}#proc-downloading-service-registry-artifacts_getting-started-rhoas-service-registry[Download {registry} artifacts]
* {base-url}{rhoas-cli-getting-started-url-registry}#proc-updating-service-registry-artifacts_getting-started-rhoas-service-registry[Update {registry} artifacts]
* {base-url}{rhoas-cli-getting-started-url-registry}#proc-configuring-service-registry-rules_getting-started-rhoas-service-registry[Configure {registry} rules]
* {base-url}{rhoas-cli-getting-started-url-registry}#proc-commands-managing-registry_getting-started-rhoas-service-registry[Use `rhoas` to manage your {registry} instance, service accounts, and artifacts]

//Additional line break to resolve mod docs generation error

[id="ref-service-registry-cli-prereqs_{context}"]
== Prerequisites

[role="_abstract"]
* You've installed the `rhoas` CLI. For more information, see {base-url}{rhoas-cli-installation-url}[_Installing the rhoas CLI_^].

[id="proc-creating-service-registry-instance-cli_{context}"]
== Creating a {registry} instance

[role="_abstract"]
A {registry} instance serves as a central location for storing artifacts.

.Prerequisites

* You're logged in to `rhoas`.

.Procedure

. Create a {registry} instance with default values.
+
--
This example creates a {registry} instance called `my-registry`.

.Creating a {registry} instance
[source,shell,subs="attributes"]
----
$ rhoas service-registry create --name my-registry
----

[NOTE]
====
If you do not want to use the default values,
enter the following command: `rhoas service-registry create`.
You are prompted to enter the `Name` for the {registry} instance.
====
--

. Verify that the {registry} instance is ready to use.
+
--
.Reviewing details of a {registry} instance
[source,shell]
----
$ rhoas status service-registry
----

This command shows that the {registry} instance is ready to use,
because the `Status` field is `ready`.

[NOTE]
====
When you created the {registry} instance, it was set as the current instance automatically.
If you have multiple {registry} instances,
you can switch to a different instance by using the `rhoas service-registry use` command.
====
--

[id="proc-creating-service-registry-account_{context}"]
== Creating a service account

[role="_abstract"]
To connect your applications or services to a {registry} instance, you must first create a service account with credentials.
The credentials are exported to a file on your computer,
which you can use to authenticate your application with your {registry} instance.

.Prerequisites

* You've created a {registry} instance, and it has a `ready` status.

.Procedure

. Create a service account.
+
--
This example creates a service account and saves the credentials in a JSON file.

.Creating a service account
[source,shell]
----
$ rhoas service-account create --short-description="rhoas-service-account" --file-format json
----

[NOTE]
====
When creating a service account, you can choose the file format and location to save the credentials.
For more information, see the `rhoas service-account create` command help.
====
--

. To verify your service account credentials,
view the `credentials.json` file that you created.
+
--
.Example `credentials.json` file
[source,json]
----
{
	"clientID":"srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1",
	"clientSecret":"facf3df1-ab97-2253-aa87-ab97",
    "oauthTokenUrl": "https://identity.api.openshift.com/auth/realms/rhoas/protocol/openid-connect/token"
}
----
You use these credentials and the {registry} URL to connect your applications and services to your {registry} instance.

[NOTE]
====
By connecting your applications to your {registry} instance, you can retrieve artifacts and use them directly in your service.
====
--

. Create a role for the new service account that can read and write artifacts.
+
--
This example creates a role called `manager` for the service account.

.Creating a role for the service account
[source,shell]
----
$ rhoas service-registry role add --role=manager --service-account=srvc-acct-8c95ca5e1225-94a-41f1-ab97-aacf3df1
----
--

[id="proc-uploading-service-registry-artifacts_{context}"]
== Uploading {registry} artifacts

[role="_abstract"]
After creating a {registry} instance, you can start uploading {registry} artifacts.
Artifacts might include, for example, schemas that define the structure of Kafka data or OpenAPI documents to define an API.

.Prerequisites

* You've created a {registry} instance, and it has a `ready` status.

[NOTE]
====
You can use `rhoas service-registry use` to switch to a specific {registry} instance.

.Selecting a {registry} instance to use
[source,shell]
----
$ rhoas service-registry use --name=my-registry
----
====

.Procedure

. Upload a {registry} artifact.
+
--
This example uploads a {registry} artifact called `my-artifact` to the {registry} instance.
The artifact is an Apache Kafka Avro schema in JSON format.

.Uploading an artifact
[source,shell]
----
$ wget https://raw.githubusercontent.com/redhat-developer/app-services-cli/main/docs/resources/avro-userInfo.json
----
--

. Create the {registry} artifact from the Avro schema that you uploaded.
+
.Creating an artifact
[source,shell]
----
$ rhoas service-registry artifact create --type=AVRO --artifact-id=my-artifact avro-userInfo.json
----

. Verify that the artifact was registered.
+
--
This example lists all artifacts belonging to the {registry} instance.

.Listing artifact details for a {registry} instance
[source,shell]
----
$ rhoas service-registry artifact list
----
--

. Check the version information for the artifact.
+
.Checking the version information of an artifact
[source,shell]
----
$ rhoas service-registry artifact versions --artifact-id=my-artifact
----

. Check the metadata information for the artifact.
+
--
.Checking the metadata information of an artifact
[source,shell]
----
$ rhoas service-registry artifact metadata-get --artifact-id=my-artifact
----

[NOTE]
====
You can use additional options, such as `--group`, `--version`, and  `--description`, to modify the metadata of the artifact you're creating.
For more information about any of the options, view the command help `rhoas service-registry artifact metadata-set -h`.
====
--

[id="proc-downloading-service-registry-artifacts_{context}"]
== Downloading {registry} artifacts

[role="_abstract"]
After you register a {registry} artifact, you can download the artifact to update it.

.Prerequisites

* You've created a {registry} instance with at least one artifact.

.Procedure

* Download the artifact in one of the following ways:

** Use the `rhoas service-registry artifact get` command and specify the artifact ID.
+
--
.Downloading an artifact by using the artifact ID
[source,shell]
----
$ rhoas service-registry artifact get --artifact-id=my-artifact
----

[NOTE]
====
To find the artifact ID, use the `rhoas service-registry artifact list` command.
====
--

** Use the `rhoas service-registry artifact download` command and specify the global ID.
+
--
.Downloading an artifact by using the global ID
[source,shell]
----
$ rhoas service-registry artifact download --global-id=28
----

[NOTE]
====
To find the global ID, see the Kafka message payload.
====
--

[NOTE]
====
You can use additional options, such as `--group` and `--instance-id`, to specify the artifact to download.
For more information about any of the options, view the command help `rhoas service-registry artifact download -h` and `rhoas service-registry artifact get -h`.
====

[id="proc-updating-service-registry-artifacts_{context}"]
== Updating {registry} artifacts

[role="_abstract"]
You can update an artifact with content from a file or from standard input.

.Prerequisites

* You've created a {registry} instance with at least one artifact.
* The type of the updated content is compatible with the current artifact type.

.Procedure

. Update a {registry} artifact.
+
--
This example updates a {registry} artifact called `my-artifact` with content from a file in JSON format.

.Updating an artifact from a file
[source,shell]
----
$ rhoas service-registry artifact update --artifact-id=my-artifact my-artifact.json
----

[NOTE]
====
To update the artifact from standard input, use the `rhoas service-registry artifact update --artifact-id=my_artifact` command.

Paste the updated artifact content on the command line, and then press Ctrl+D to save.
====
--

. Verify that the artifact was updated. The updated artifact is saved as a new version.
+
--
.Checking the version number and modified date of an artifact
[source,shell]
----
$ rhoas service-registry artifact metadata-get --artifact-id=my-artifact
----

[NOTE]
====
You can use additional options, such as `--group` and `--version`, to specify the artifact to update.
For more information about any of the options, view the command help `rhoas service-registry artifact update -h`.
====
--

[id="proc-configuring-service-registry-rules_{context}"]
== Configuring {registry} rules

[role="_abstract"]
To prevent invalid content from being added to {registry}, you can configure optional rules to check the artifact content. Artifact rules apply to the specified artifact only. Global rules apply to all artifacts in a particular {registry} instance. Configured artifact rules override any configured global rules. Before a new artifact version can be uploaded to the registry, all configured global rules or artifact rules must pass.

.Prerequisites

* You've created a {registry} instance with at least one artifact.

.Procedure

. Identify the rule that you want to update.
+
--
To show a list of global rules, run the following command:

[source,shell]
----
$ rhoas service-registry rule list
----

To show a list of artifact rules, specify the artifact ID as shown in the following example:

[source,shell]
----
$ rhoas service-registry rule list --artifact-id=my-artifact
----

--
. Update the {registry} rule by specifying the rule type and configuration.
+
--
This example updates the global compatibility rule for all artifacts in the current {registry} instance:

[source,shell]
----
$ rhoas service-registry rule update --rule-type=compatibility --config=full
----

This example updates the validity rule for a specific artifact:

[source,shell]
----
$ rhoas service-registry rule update --rule-type=validity --config=full --artifact-id=my-artifact
----

[NOTE]
====
For more information about {registry} rule types and rule maturity, see {content-rules-registry}.
====

--

. Verify that the rule updated correctly.
+
--
This example displays the details of the global compatibility rule:

[source,shell]
----
$ rhoas service-registry rule describe --rule-type=compatibility
----

This example displays the details of the artifact validity rule:

[source,shell]
----
$ rhoas service-registry rule describe --rule-type=validity --artifact-id=my-artifact
----
--

. Optional: Enable or disable individual rules. When you enable a rule, you must specify the configuration value.
+
--
This example enables the global compatibility rule:

[source,shell]
----
$ rhoas service-registry rule enable --rule-type=compatibility --config=full
----

This example disables the artifact validity rule:

[source,shell]
----
$ rhoas service-registry rule disable --rule-type=validity --artifact-id=my-artifact
----
--

[NOTE]
====
You can use additional options, such as `--group` and `--instance-id`, to specify the {registry} group or instance to which the updated rules apply.
For more information about any of the options, view the command help `rhoas service-registry rule -h`.
====


[id="proc-commands-managing-registry_{context}"]
== Commands for managing {registry}

[role="_abstract"]
For more information about the `rhoas` commands you can use to manage your {registry} instance,
use the following command help:

* `rhoas service-registry -h` for {registry} instances
* `rhoas service-account -h` for service accounts
* `rhoas service-registry artifact -h` for {registry} artifacts

[role="_additional-resources"]
.Additional resources
* {rhoas-cli-base-url}{rhoas-cli-ref-url}[_CLI command reference (rhoas)_^]
