[id='con-product-overview_{context}']
= {product-long}
:imagesdir: ../_images

{product-long} is a fully managed cloud service running on https://www.openshift.com/products/dedicated/[OpenShift Dedicated]. {product} enables you to implement Kafka data-streaming functionality in your applications without having to install, configure, run, and maintain your own Kafka clusters. With {product}, you can share data between microservices and other applications with high throughput and low latency.

{product} also has the following key attributes:

* *Scales with your application needs*: As your applications and services grow and require more Kafka instances, topics, and data, {product} can scale to meet those needs.
* *Provides flexible user control*: You can use the {product} web console UI or the relevant {product} API to configure the service as you desire.
ifndef::community[]
* *Offers a Service Level Agreement (SLA)*: You can rely on the service functionality as defined in the SLA.
endif::[]
