[id='task-3_{context}']
= Consuming messages
Apart from producing messages, Kafkacat can also be used to consume messages.
To consume messages, you simply need to run Kafkacat in _consumer_ mode, which is simply doing by using the `-C` (consumer) switch on the command rather than the `-P` (producer) switch you used in the previous task.

.Prerequisites
* Kafkacat installed on your system.
* A running {Product_short} Kafka instance.
* The bootstrap server location of your Kafka instance.
* The credentials of the Service Account to authenticate against the Kafka instance.
* Messages produced to the `my-topic` topic as described in the previous task.

.Procedure
. Using the information retrieved in the previous task, like the _Bootstrap Server_ of your {product_short} Kafka instance and credentials, set the environment variables BOOTSTRAP_SERVER, USER and PASSWORD like you did in the previous task.
+
[source,bash]
----
$ export BOOTSTRAP_SERVER=<BOOTSTRAP_SERVER>
$ export USER=<CLIENT_ID>
$ export PASSWORD=<CLIENT_SECRET>
----
+
. Start Kafkacat in _consumer_ mode. You will consume messages from the same topic, `my-topic` that you produced messages to in the previous task Note that you will be producing messages to the _my-topic_ topic that you've created in the _Getting Started Guide_. Execute the following command. You should see the 3 messages you produced in the previous task.
+
[source,bash]
----
$ kafkacat -t my-topic -b "$BOOTSTRAP_SERVER" \
 -X security.protocol=SASL_SSL -X sasl.mechanisms=PLAIN \
 -X sasl.username="$USER" \
 -X sasl.password="$PASSWORD" -C
First message
Second message
Third message
% Reached end of topic my-topic [0] at offset 3
----
+
. The Kafkacat consumer has consumed the 3 messages you've sent to the topic earlier, and prints that is has reached the end of _partition 0_ of the `my-topic` topic. Keep the consumer, as you will use it in the next task.

.Verification
. You've a Kafkacat consumer running without any errors printed to your console.
. Kafkacat consumed the 3 messages you've sent to the `my-topic` topic in the previous task.
