[id='task-4_{context}']
= This needs a proper title
Now that you've produced and consumed some messages, and have your Kafkacat producer and Kafkacat consumer still running, we can produce and consume some more messages.

.Prerequisites
* A Kafkacat producer running and connected to your {Product_short} Kafka instance, producing to your `my-topic` topic.
* A Kafkacat consumer running and connected to your {Product_short} Kafka instance, consuming from your `my-topic` topic.

.Procedure
. In your terminal with the running Kafkacat producer, send the following message.
+
[source,bash]
----
My own messsage
----
+
. Switch to the terminal in which you have your Kafkacat consumer running. You should see your message being consumed.
+
[source,bash]
----
First message
Second message
Third message
% Reached end of topic my-topic [0] at offset 3
My own message
% Reached end of topic my-topic [0] at offset 4
----
+
. Produce some more messages to your {Product_short} Kafka instance and see how they are being consumed by your Kafkacat consumer.

.Verification
. You've produced the _My own message_ to your `my-topic` Kafka topic without errors.
. The _My own message_ was successfully consumed by your Kafkacat consumer.

[id=conclusion_{context}]
Congratulations! You've successfully completed the {Product} Kafkacat Guide, and are now ready to produce message to, and consume messages from, the service.

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
