# This workflow will generate any code then check for any git diff

name: Modular docs publish

on:
  push:
    tags:
      - 'v*'
    #branches: [main]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
            - product: RHOSAK
              branch: modular-docs-rhosak
            - product: RHOSR
              branch: modular-docs-rhosr
            - product: RHOAS
              branch: modular-docs-rhoas
            # - product: RHODA
            #  branch: modular-docs-rhoda
            - product: RHOC
              branch: modular-docs-rhoc
            - product: RHOAD
              branch: modular-docs-rhoad
    steps:
      - uses: actions/checkout@v2
        name: Checkout Source
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.6.2
      - name: Set up JDK 9.0.4 for x64
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: 'adopt' # See 'Supported distributions' for available options
      - name: Use Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install Node Dependencies
        run: npm --prefix .build install

      - run: gem install asciidoctor tilt haml
        name: Install Asciidoctor
      - run: npm --prefix .build run generate:modular-docs
        name: Generate modular-docs
        env:
          DOCS_PRODUCT_NAME: ${{matrix.product}}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        env:
          DEPLOY_BRANCH: ${{matrix.branch}}
        with:
          branch: ${{matrix.branch}} # The branch the action should deploy to.
          folder: .build/tmp/post-splitter # The folder the action should deploy.
