# This workflow will generate any code then check for any git diff

name: Modular docs publish

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        name: Checkout Source
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up JDK 9.0.4 for x64
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: 'adopt' # See 'Supported distributions' for available options
      - name: Use Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: npm --prefix .build install
        name: Install Node Dependencies
      - run: gem install asciidoctor tilt haml
        name: Install Asciidoctor
      - run: npm --prefix .build run generate:modular-docs
        name: Generate modular-docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: modular-docs # The branch the action should deploy to.
          folder: .build/tmp/post-splitter # The folder the action should deploy.
